'use client';

import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';

interface MaterialItem {
  id: string;
  name: string;
  quantity: string;
  price: string;
  unit: string;
  scope?: string;
  category?: 'design' | 'construction' | 'general';
  isAutoGenerated?: boolean;
  color?: string;
  source?: string;
}

interface StructuralDesignData {
  // Wall Modifications
  frameNewWall: boolean;
  relocateWall: boolean;
  relocateWallLength: string;
  relocateWallHeight: string;
  removeNonLoadBearingWall: boolean;
  installBlocking: boolean;
  frameShowerNiche: boolean;
  addInsulation: boolean;

  // Floors
  repairSisterFloorJoists: boolean;
  levelFloor: boolean;
  installNewPlywoodSubfloor: boolean;
  plywoodThickness: '1/2' | '5/8' | '3/4';
  replaceRottenSubfloor: boolean;

  // Window & Door Openings
  addNewWindow: boolean;
  enlargeExistingWindow: boolean;
  changeDoorwayOpening: boolean;
  closeOffWindow: boolean;
}

export default function StructuralMaterialsSection() {
  const { getDesignData, getMaterialItems, setMaterialItems, isReloading } =
    useEstimateWorkflowContext();

  const designData = getDesignData('structural') as StructuralDesignData | null;
  const design = useMemo(
    () =>
      designData || {
        // Wall Modifications
        frameNewWall: false,
        relocateWall: false,
        relocateWallLength: '10',
        relocateWallHeight: '8',
        removeNonLoadBearingWall: false,
        installBlocking: false,
        frameShowerNiche: false,
        addInsulation: false,

        // Floors
        repairSisterFloorJoists: false,
        levelFloor: false,
        installNewPlywoodSubfloor: false,
        plywoodThickness: '3/4' as const,
        replaceRottenSubfloor: false,

        // Window & Door Openings
        addNewWindow: false,
        enlargeExistingWindow: false,
        changeDoorwayOpening: false,
        closeOffWindow: false,
      },
    [designData]
  );

  const [localMaterialItems, setLocalMaterialItems] = useState<MaterialItem[]>(
    []
  );
  const [isWallWorkOpen, setIsWallWorkOpen] = useState(true);
  const [isFloorsOpen, setIsFloorsOpen] = useState(true);
  const [isWindowDoorOpen, setIsWindowDoorOpen] = useState(true);
  const userActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Get current items from context
  const contextMaterialItems = getMaterialItems('structural');

  // Calculate stud count for relocate wall
  const studCount = useMemo(() => {
    const length = parseFloat(design.relocateWallLength) || 0;
    return Math.ceil(length * 1.25); // 1.25 studs per foot
  }, [design.relocateWallLength]);

  // Auto-populate material items based on selected tasks
  useEffect(() => {
    if (isReloading || userActionRef.current) {
      userActionRef.current = false;
      return;
    }

    const newMaterialItems: MaterialItem[] = [];

    // Wall Modifications
    if (design.frameNewWall) {
      newMaterialItems.push(
        {
          id: 'frame-new-wall-studs',
          name: '2×4 studs (8ft)',
          quantity: '15',
          price: '3.50',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'frame-new-wall-screws',
          name: 'Framing screws',
          quantity: '1',
          price: '12.00',
          unit: 'box',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.relocateWall) {
      newMaterialItems.push(
        {
          id: 'relocate-wall-studs',
          name: '2×4 studs (8ft)',
          quantity: studCount.toString(),
          price: '3.50',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'relocate-wall-screws',
          name: 'Framing screws',
          quantity: '1',
          price: '12.00',
          unit: 'box',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.installBlocking) {
      newMaterialItems.push({
        id: 'install-blocking-lumber',
        name: '2×6 (8ft)',
        quantity: '2',
        price: '8.50',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.frameShowerNiche) {
      newMaterialItems.push({
        id: 'frame-shower-niche-lumber',
        name: '2×4 (8ft)',
        quantity: '2',
        price: '3.50',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.addInsulation) {
      newMaterialItems.push(
        {
          id: 'add-insulation-batt',
          name: 'R-12 batt insulation',
          quantity: '1',
          price: '45.00',
          unit: 'bag',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'add-insulation-sealant',
          name: 'Acoustic sealant',
          quantity: '1',
          price: '8.50',
          unit: 'tube',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    // Floors
    if (design.repairSisterFloorJoists) {
      newMaterialItems.push(
        {
          id: 'repair-joists-lumber',
          name: '2×8 (12ft)',
          quantity: '2',
          price: '15.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'repair-joists-screws',
          name: 'Structural screws',
          quantity: '1',
          price: '18.00',
          unit: 'box',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        }
      );
    }

    if (design.levelFloor) {
      newMaterialItems.push({
        id: 'level-floor-compound',
        name: 'Self-leveling compound (50lb)',
        quantity: '3',
        price: '25.00',
        unit: 'bag',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.installNewPlywoodSubfloor) {
      const thicknessName =
        design.plywoodThickness === '1/2'
          ? '1/2"'
          : design.plywoodThickness === '5/8'
          ? '5/8"'
          : '3/4"';
      const thicknessPrice =
        design.plywoodThickness === '1/2'
          ? '35.00'
          : design.plywoodThickness === '5/8'
          ? '42.00'
          : '48.00';

      newMaterialItems.push(
        {
          id: 'install-plywood-sheets',
          name: `Plywood subfloor ${thicknessName}`,
          quantity: '4',
          price: thicknessPrice,
          unit: 'sheet',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'install-plywood-screws',
          name: 'Subfloor screws',
          quantity: '1',
          price: '15.00',
          unit: 'box',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        }
      );
    }

    if (design.replaceRottenSubfloor) {
      newMaterialItems.push(
        {
          id: 'replace-subfloor-plywood',
          name: '3/4" plywood',
          quantity: '2',
          price: '48.00',
          unit: 'sheet',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'replace-subfloor-studs',
          name: '2×4 studs (support)',
          quantity: '3',
          price: '3.50',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        }
      );
    }

    // Window & Door Openings
    if (design.addNewWindow) {
      newMaterialItems.push(
        {
          id: 'add-window-header',
          name: '2×6 header',
          quantity: '2',
          price: '8.50',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'purple',
        },
        {
          id: 'add-window-flashing',
          name: 'Flashing tape',
          quantity: '1',
          price: '12.00',
          unit: 'roll',
          category: 'construction',
          isAutoGenerated: true,
          color: 'purple',
        }
      );
    }

    if (design.enlargeExistingWindow) {
      newMaterialItems.push({
        id: 'enlarge-window-header',
        name: '2×6 header',
        quantity: '2',
        price: '8.50',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'purple',
      });
    }

    if (design.changeDoorwayOpening) {
      newMaterialItems.push({
        id: 'change-doorway-studs',
        name: '2×4 studs',
        quantity: '3',
        price: '3.50',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'purple',
      });
    }

    if (design.closeOffWindow) {
      newMaterialItems.push(
        {
          id: 'close-window-studs',
          name: '2×4 studs',
          quantity: '4',
          price: '3.50',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'purple',
        },
        {
          id: 'close-window-sheathing',
          name: '1/2" sheathing',
          quantity: '1',
          price: '28.00',
          unit: 'sheet',
          category: 'construction',
          isAutoGenerated: true,
          color: 'purple',
        },
        {
          id: 'close-window-screws',
          name: 'Screws',
          quantity: '1',
          price: '8.00',
          unit: 'box',
          category: 'construction',
          isAutoGenerated: true,
          color: 'purple',
        }
      );
    }

    // Update context
    setMaterialItems('structural', newMaterialItems);
    setLocalMaterialItems(newMaterialItems);

    // Update processed choices
    const choicesString = JSON.stringify(design);
    processedChoicesRef.current = choicesString;
  }, [design, studCount, isReloading, setMaterialItems]);

  // Sync with context changes
  useEffect(() => {
    if (!isReloading) {
      setLocalMaterialItems(contextMaterialItems);
    }
  }, [contextMaterialItems, isReloading]);

  // Handlers
  const handleAddMaterialItem = useCallback(() => {
    const newItem: MaterialItem = {
      id: `material-${Date.now()}`,
      name: '',
      quantity: '1',
      price: '0',
      unit: '',
      category: 'construction',
      isAutoGenerated: false,
      color: 'gray',
    };

    const updatedItems = [...localMaterialItems, newItem];
    setLocalMaterialItems(updatedItems);
    setMaterialItems('structural', updatedItems);
    userActionRef.current = true;
  }, [localMaterialItems, setMaterialItems]);

  const handleUpdateMaterialItem = useCallback(
    (id: string, field: keyof MaterialItem, value: string) => {
      const updatedItems = localMaterialItems.map((item) =>
        item.id === id ? { ...item, [field]: value } : item
      );
      setLocalMaterialItems(updatedItems);
      setMaterialItems('structural', updatedItems);
      userActionRef.current = true;
    },
    [localMaterialItems, setMaterialItems]
  );

  const handleDeleteMaterialItem = useCallback(
    (id: string) => {
      const updatedItems = localMaterialItems.filter((item) => item.id !== id);
      setLocalMaterialItems(updatedItems);
      setMaterialItems('structural', updatedItems);
      userActionRef.current = true;
    },
    [localMaterialItems, setMaterialItems]
  );

  // Calculate totals
  const materialTotal = useMemo(() => {
    return localMaterialItems.reduce((total, item) => {
      const quantity = parseFloat(item.quantity) || 0;
      const price = parseFloat(item.price) || 0;
      return total + quantity * price;
    }, 0);
  }, [localMaterialItems]);

  // Group items by category
  const wallWorkItems = localMaterialItems.filter(
    (item) => item.color === 'blue'
  );
  const floorsItems = localMaterialItems.filter(
    (item) => item.color === 'green'
  );
  const windowDoorItems = localMaterialItems.filter(
    (item) => item.color === 'purple'
  );
  const customItems = localMaterialItems.filter(
    (item) => item.color === 'gray'
  );

  const renderMaterialItem = (item: MaterialItem) => (
    <div
      key={item.id}
      className={`p-3 rounded-lg border bg-white border-gray-200`}
    >
      <div className='flex items-center gap-3'>
        <div className='flex-1'>
          <Input
            value={item.name}
            onChange={(e) =>
              handleUpdateMaterialItem(item.id, 'name', e.target.value)
            }
            placeholder='Item name'
            className='font-medium'
          />
        </div>
        <div className='w-20'>
          <Input
            type='number'
            value={item.quantity}
            onChange={(e) =>
              handleUpdateMaterialItem(item.id, 'quantity', e.target.value)
            }
            placeholder='Qty'
            className='text-center'
          />
        </div>
        <div className='w-16'>
          <Input
            value={item.unit}
            onChange={(e) =>
              handleUpdateMaterialItem(item.id, 'unit', e.target.value)
            }
            placeholder='Unit'
            className='text-center'
          />
        </div>
        <div className='w-24'>
          <Input
            type='number'
            value={item.price}
            onChange={(e) =>
              handleUpdateMaterialItem(item.id, 'price', e.target.value)
            }
            placeholder='Price'
            className='text-center'
          />
        </div>
        <div className='w-24 text-right font-semibold text-gray-700'>
          ${(parseFloat(item.quantity) * parseFloat(item.price)).toFixed(2)}
        </div>
        {!item.isAutoGenerated && (
          <Button
            onClick={() => handleDeleteMaterialItem(item.id)}
            variant='ghost'
            size='sm'
            className='p-1 text-red-500 hover:text-red-700'
          >
            <Trash2 size={16} />
          </Button>
        )}
      </div>
    </div>
  );

  return (
    <div className='space-y-6'>
      <div className='pt-2'>
        <div className='flex justify-between items-baseline'>
          <h2 className='text-2xl font-bold text-slate-800'>Materials</h2>
          <div className='text-xl font-bold text-blue-600'>
            ${materialTotal.toFixed(2)}
          </div>
        </div>
      </div>

      {/* Wall Work */}
      <Card>
        <CardContent className='p-0'>
          <div
            className='flex items-center justify-between p-4 cursor-pointer hover:bg-gray-50'
            onClick={() => setIsWallWorkOpen(!isWallWorkOpen)}
          >
            <h3 className='text-lg font-semibold text-gray-900'>Wall Work</h3>
            {isWallWorkOpen ? (
              <ChevronDown className='h-5 w-5 text-gray-500' />
            ) : (
              <ChevronRight className='h-5 w-5 text-gray-500' />
            )}
          </div>
          {isWallWorkOpen && (
            <div className='px-4 pb-4 space-y-3'>
              {wallWorkItems.length > 0 ? (
                wallWorkItems.map(renderMaterialItem)
              ) : (
                <div className='text-center py-8 text-gray-500'>
                  No wall work materials yet. Select tasks in the Design section
                  to auto-populate items.
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Floors */}
      <Card>
        <CardContent className='p-0'>
          <div
            className='flex items-center justify-between p-4 cursor-pointer hover:bg-gray-50'
            onClick={() => setIsFloorsOpen(!isFloorsOpen)}
          >
            <h3 className='text-lg font-semibold text-gray-900'>Floors</h3>
            {isFloorsOpen ? (
              <ChevronDown className='h-5 w-5 text-gray-500' />
            ) : (
              <ChevronRight className='h-5 w-5 text-gray-500' />
            )}
          </div>
          {isFloorsOpen && (
            <div className='px-4 pb-4 space-y-3'>
              {floorsItems.length > 0 ? (
                floorsItems.map(renderMaterialItem)
              ) : (
                <div className='text-center py-8 text-gray-500'>
                  No floor materials yet. Select tasks in the Design section to
                  auto-populate items.
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Window & Door Openings */}
      <Card>
        <CardContent className='p-0'>
          <div
            className='flex items-center justify-between p-4 cursor-pointer hover:bg-gray-50'
            onClick={() => setIsWindowDoorOpen(!isWindowDoorOpen)}
          >
            <h3 className='text-lg font-semibold text-gray-900'>
              Window & Door Openings
            </h3>
            {isWindowDoorOpen ? (
              <ChevronDown className='h-5 w-5 text-gray-500' />
            ) : (
              <ChevronRight className='h-5 w-5 text-gray-500' />
            )}
          </div>
          {isWindowDoorOpen && (
            <div className='px-4 pb-4 space-y-3'>
              {windowDoorItems.length > 0 ? (
                windowDoorItems.map(renderMaterialItem)
              ) : (
                <div className='text-center py-8 text-gray-500'>
                  No window/door materials yet. Select tasks in the Design
                  section to auto-populate items.
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Custom Items */}
      <Card>
        <CardContent className='p-0'>
          <div className='flex items-center justify-between p-4'>
            <h3 className='text-lg font-semibold text-gray-900'>
              Custom Items
            </h3>
            <Button
              onClick={handleAddMaterialItem}
              variant='outline'
              size='sm'
              className='flex items-center gap-2'
            >
              <Plus size={16} />
              Add Material Item
            </Button>
          </div>
          <div className='px-4 pb-4 space-y-3'>
            {customItems.length > 0 ? (
              customItems.map(renderMaterialItem)
            ) : (
              <div className='text-center py-8 text-gray-500'>
                No custom items yet. Click &quot;Add Material Item&quot; to
                create one.
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Totals */}
      <Card>
        <CardContent className='p-4'>
          <div className='space-y-2'>
            <div className='flex justify-between items-center'>
              <span className='text-lg font-medium text-gray-700'>
                Materials Total:
              </span>
              <span className='text-xl font-bold text-blue-600'>
                ${materialTotal.toFixed(2)}
              </span>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
