'use client';

import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { STRUCTURAL_MATERIALS_ITEMS } from '@/lib/constants';
import { Plus, Trash2 } from 'lucide-react';

interface MaterialItem {
  id: string;
  name: string;
  quantity: string;
  price: string;
  unit: string;
  scope?: string;
  category?: 'design' | 'construction' | 'general';
  isAutoGenerated?: boolean;
  color?: string;
}

interface StructuralDesignData {
  width: string;
  length: string;
  height: string;
  frameNewWall: boolean;
  removeWall: boolean;
  frameDoorway: boolean;
  frameWindow: boolean;
  wallLength: string;
  doorwayWidth: string;
  windowWidth: string;
  windowHeight: string;
  installBeam: boolean;
  installHeader: boolean;
  reinforceJoists: boolean;
  beamLength: string;
  headerLength: string;
  installPlywood: boolean;
  repairSubfloor: boolean;
  plywoodThickness: '1/2' | '5/8' | '3/4';
  subfloorArea: string;
  installInsulation: boolean;
  installVaporBarrier: boolean;
  insulationArea: string;
}

export default function StructuralMaterialsSection() {
  const { getDesignData, getMaterialItems, setMaterialItems, isReloading } =
    useEstimateWorkflowContext();

  const designData = getDesignData('structural') as StructuralDesignData | null;
  const design = useMemo(
    () =>
      designData || {
        width: '60',
        length: '96',
        height: '96',
        frameNewWall: false,
        removeWall: false,
        frameDoorway: false,
        frameWindow: false,
        wallLength: '',
        doorwayWidth: '',
        windowWidth: '',
        windowHeight: '',
        installBeam: false,
        installHeader: false,
        reinforceJoists: false,
        beamLength: '',
        headerLength: '',
        installPlywood: false,
        repairSubfloor: false,
        plywoodThickness: '5/8' as const,
        subfloorArea: '',
        installInsulation: false,
        installVaporBarrier: false,
        insulationArea: '',
      },
    [designData]
  );

  const [localMaterialItems, setLocalMaterialItems] = useState<MaterialItem[]>(
    []
  );
  const userActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Get current items from context
  const contextMaterialItems = getMaterialItems('structural');

  // Calculate areas and dimensions
  const wallArea = useMemo(() => {
    const w = parseFloat(design.width) || 0;
    const l = parseFloat(design.length) || 0;
    const h = parseFloat(design.height) || 0;
    if (w > 0 && l > 0 && h > 0) {
      return (2 * (w + l) * h) / 144;
    }
    return 0;
  }, [design.width, design.length, design.height]);

  const wallLength = useMemo(() => {
    const length = parseFloat(design.wallLength) || 0;
    return length > 0 ? length : 0;
  }, [design.wallLength]);

  const beamLength = useMemo(() => {
    const length = parseFloat(design.beamLength) || 0;
    return length > 0 ? length : 0;
  }, [design.beamLength]);

  const headerLength = useMemo(() => {
    const length = parseFloat(design.headerLength) || 0;
    return length > 0 ? length : 0;
  }, [design.headerLength]);

  const subfloorArea = useMemo(() => {
    const area = parseFloat(design.subfloorArea) || 0;
    return area > 0 ? area : 0;
  }, [design.subfloorArea]);

  const insulationArea = useMemo(() => {
    const area = parseFloat(design.insulationArea) || 0;
    // If no specific insulation area is set, use wall area
    if (area > 0) return area;
    return wallArea;
  }, [design.insulationArea, wallArea]);

  // Plywood pricing based on thickness
  const plywoodPricing = useMemo(() => {
    const pricing = {
      '1/2': 18.5,
      '5/8': 22.5,
      '3/4': 28.5,
    };
    return pricing[design.plywoodThickness];
  }, [design.plywoodThickness]);

  // Generate materials based on design choices
  const generateMaterials = useCallback(() => {
    const materials: MaterialItem[] = [];
    const materialsMap = STRUCTURAL_MATERIALS_ITEMS;

    // Framing Materials
    if (design.frameNewWall && wallLength > 0) {
      // 2x4 lumber for studs (every 16" on center + top/bottom plates)
      const studs = Math.ceil((wallLength * 12) / 16) + 2; // +2 for plates
      materials.push({
        ...materialsMap.lumber2x4,
        quantity: studs.toString(),
        isAutoGenerated: true,
      });

      // Hardware
      materials.push({
        ...materialsMap.framingNails,
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.constructionScrews,
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.metalBrackets,
        isAutoGenerated: true,
      });
    }

    if (design.removeWall) {
      // Basic cleanup materials
      materials.push({
        ...materialsMap.framingNails,
        isAutoGenerated: true,
      });
    }

    if (design.frameDoorway) {
      // Header beam for doorway
      materials.push({
        ...materialsMap.lumber2x8,
        quantity: '2', // Double header
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.constructionScrews,
        isAutoGenerated: true,
      });
    }

    if (design.frameWindow) {
      // Header beam for window
      materials.push({
        ...materialsMap.lumber2x6,
        quantity: '2', // Double header
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.constructionScrews,
        isAutoGenerated: true,
      });
    }

    // Structural Support Materials
    if (design.installBeam && beamLength > 0) {
      materials.push({
        ...materialsMap.steelBeam,
        quantity: beamLength.toString(),
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.beamPockets,
        isAutoGenerated: true,
      });
    }

    if (design.installHeader && headerLength > 0) {
      materials.push({
        ...materialsMap.lumber2x10,
        quantity: '2', // Double header
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.constructionScrews,
        isAutoGenerated: true,
      });
    }

    if (design.reinforceJoists) {
      materials.push({
        ...materialsMap.lumber2x8,
        quantity: '4', // Reinforcement lumber
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.constructionScrews,
        isAutoGenerated: true,
      });
    }

    // Subfloor Materials
    if (design.installPlywood && subfloorArea > 0) {
      const sheets = Math.ceil(subfloorArea / 32); // 32 sq/ft per sheet
      materials.push({
        ...materialsMap.plywoodSubfloor,
        quantity: sheets.toString(),
        price: plywoodPricing.toString(),
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.subfloorScrews,
        isAutoGenerated: true,
      });
    }

    if (design.repairSubfloor) {
      materials.push({
        ...materialsMap.plywoodSubfloor,
        quantity: '2', // Repair sheets
        price: plywoodPricing.toString(),
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.subfloorScrews,
        isAutoGenerated: true,
      });
    }

    // Insulation Materials
    if (design.installInsulation && insulationArea > 0) {
      materials.push({
        ...materialsMap.wallInsulation,
        quantity: insulationArea.toString(),
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.insulationTape,
        isAutoGenerated: true,
      });
    }

    if (design.installVaporBarrier && insulationArea > 0) {
      materials.push({
        ...materialsMap.vaporBarrier,
        quantity: insulationArea.toString(),
        isAutoGenerated: true,
      });
    }

    // Drywall Materials (if any wall work is done)
    if (
      design.frameNewWall ||
      design.removeWall ||
      design.frameDoorway ||
      design.frameWindow
    ) {
      const drywallArea = wallArea > 0 ? wallArea : 100; // Default area if not calculated
      const sheets = Math.ceil(drywallArea / 32); // 32 sq/ft per sheet

      materials.push({
        ...materialsMap.drywallSheets,
        quantity: sheets.toString(),
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.drywallScrews,
        isAutoGenerated: true,
      });
      materials.push({
        ...materialsMap.cornerBead,
        quantity: Math.ceil((wallLength * 12) / 96).toString(), // 8ft pieces
        isAutoGenerated: true,
      });
    }

    return materials;
  }, [
    design,
    wallArea,
    wallLength,
    beamLength,
    headerLength,
    subfloorArea,
    insulationArea,
    plywoodPricing,
  ]);

  // Auto-generate materials when design changes
  useEffect(() => {
    if (isReloading) return;

    const currentChoices = JSON.stringify({
      frameNewWall: design.frameNewWall,
      removeWall: design.removeWall,
      frameDoorway: design.frameDoorway,
      frameWindow: design.frameWindow,
      installBeam: design.installBeam,
      installHeader: design.installHeader,
      reinforceJoists: design.reinforceJoists,
      installPlywood: design.installPlywood,
      repairSubfloor: design.repairSubfloor,
      installInsulation: design.installInsulation,
      installVaporBarrier: design.installVaporBarrier,
      wallLength: design.wallLength,
      beamLength: design.beamLength,
      headerLength: design.headerLength,
      subfloorArea: design.subfloorArea,
      insulationArea: design.insulationArea,
      plywoodThickness: design.plywoodThickness,
    });

    // Only regenerate if choices have changed and it's not a user action
    if (
      currentChoices !== processedChoicesRef.current &&
      !userActionRef.current
    ) {
      const generatedMaterials = generateMaterials();

      // Preserve existing custom items
      const existingCustomMaterials = contextMaterialItems.filter(
        (item) => !item.isAutoGenerated
      );
      const mergedMaterials = [
        ...generatedMaterials,
        ...existingCustomMaterials,
      ];

      setLocalMaterialItems(mergedMaterials);
      setMaterialItems('structural', mergedMaterials);

      processedChoicesRef.current = currentChoices;
    }

    // Reset user action flag
    userActionRef.current = false;
  }, [
    design,
    generateMaterials,
    contextMaterialItems,
    setMaterialItems,
    isReloading,
  ]);

  // Sync with context when context changes
  useEffect(() => {
    if (!isReloading) {
      setLocalMaterialItems(contextMaterialItems);
    }
  }, [contextMaterialItems, isReloading]);

  // Handlers
  const handleAddMaterialItem = useCallback(() => {
    userActionRef.current = true;
    const newItem: MaterialItem = {
      id: `custom-mat-${Date.now()}`,
      name: '',
      quantity: '0',
      unit: 'each',
      price: '0',
      scope: 'construction',
      category: 'construction',
      isAutoGenerated: false,
    };

    const updatedItems = [...localMaterialItems, newItem];
    setLocalMaterialItems(updatedItems);
    setMaterialItems('structural', updatedItems);
  }, [localMaterialItems, setMaterialItems]);

  const handleChangeMaterialItem = useCallback(
    (id: string, field: keyof MaterialItem, value: string) => {
      userActionRef.current = true;
      const updatedItems = localMaterialItems.map((item) =>
        item.id === id ? { ...item, [field]: value } : item
      );
      setLocalMaterialItems(updatedItems);
      setMaterialItems('structural', updatedItems);
    },
    [localMaterialItems, setMaterialItems]
  );

  const handleDeleteMaterialItem = useCallback(
    (id: string) => {
      userActionRef.current = true;
      const updatedItems = localMaterialItems.filter((item) => item.id !== id);
      setLocalMaterialItems(updatedItems);
      setMaterialItems('structural', updatedItems);
    },
    [localMaterialItems, setMaterialItems]
  );

  // Calculate totals
  const materialsTotal = useMemo(() => {
    return localMaterialItems.reduce((sum, item) => {
      const quantity = parseFloat(item.quantity) || 0;
      const price = parseFloat(item.price) || 0;
      return sum + quantity * price;
    }, 0);
  }, [localMaterialItems]);

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-center'>
        <h2 className='text-2xl font-bold text-slate-800'>
          Materials & Supplies
        </h2>
        <div className='text-right'>
          <p className='font-bold text-blue-600 text-lg'>
            ${materialsTotal.toFixed(2)}
          </p>
        </div>
      </div>
      <Card>
        <CardContent className='p-3 space-y-3'>
          {localMaterialItems.length > 0 ? (
            localMaterialItems.map((item) => (
              <div
                key={item.id}
                className={`p-3 bg-white rounded-lg border ${
                  item.isAutoGenerated
                    ? 'bg-blue-50 border-blue-200'
                    : 'border-slate-300'
                }`}
              >
                <div className='flex items-center gap-2 mb-2'>
                  <Input
                    type='text'
                    value={item.name}
                    onChange={(e) =>
                      handleChangeMaterialItem(item.id, 'name', e.target.value)
                    }
                    placeholder='Supply Name'
                    className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none`}
                  />
                  <Button
                    onClick={() => handleDeleteMaterialItem(item.id)}
                    variant='ghost'
                    size='sm'
                    className='text-red-500 hover:text-red-700 p-1 h-auto'
                  >
                    <Trash2 size={16} />
                  </Button>
                </div>
                <div className='grid grid-cols-3 gap-3'>
                  <div>
                    <label className='text-xs text-slate-500'>Quantity</label>
                    <Input
                      type='number'
                      value={item.quantity}
                      onChange={(e) =>
                        handleChangeMaterialItem(
                          item.id,
                          'quantity',
                          e.target.value
                        )
                      }
                      placeholder='0'
                      className={`text-center border-blue-300 focus:border-blue-500`}
                    />
                  </div>
                  <div>
                    <label className='text-xs text-slate-500'>Unit</label>
                    <Input
                      type='text'
                      value={item.unit}
                      onChange={(e) =>
                        handleChangeMaterialItem(
                          item.id,
                          'unit',
                          e.target.value
                        )
                      }
                      placeholder='sq/ft'
                      className={`text-center border-blue-300 focus:border-blue-500`}
                    />
                  </div>
                  <div>
                    <label className='text-xs text-slate-500'>
                      Price/Unit ($)
                    </label>
                    <Input
                      type='number'
                      value={item.price}
                      onChange={(e) =>
                        handleChangeMaterialItem(
                          item.id,
                          'price',
                          e.target.value
                        )
                      }
                      placeholder='0.00'
                      className={`text-center border-blue-300 focus:border-blue-500`}
                    />
                  </div>
                </div>
                <div className='mt-2'>
                  <label className='text-xs text-slate-500'>Total</label>
                  <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
                    $
                    {(
                      (parseFloat(item.quantity) || 0) *
                      (parseFloat(item.price) || 0)
                    ).toFixed(2)}
                  </div>
                </div>
              </div>
            ))
          ) : (
            <p className='text-sm text-slate-500 text-center py-4'>
              No materials added yet.
            </p>
          )}

          <div className='flex justify-center'>
            <Button
              onClick={handleAddMaterialItem}
              variant='default'
              className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
            >
              <Plus size={16} />
              Add Item
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
