'use client';

import React, {
  useMemo,
  useCallback,
  useState,
  useEffect,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { MaterialItem as ContextMaterialItem } from '@/types/estimate';

type MaterialItem = ContextMaterialItem & {
  source?: string;
  isAutoGenerated?: boolean;
};

export default function FloorsMaterialsSection() {
  const { getMaterialItems, setMaterialItems } =
    useEstimateWorkflowContext();

  // Get context data
  const contextMaterials = getMaterialItems('floors');

  // Local state for immediate UI updates
  const [localMaterials, setLocalMaterials] = useState<MaterialItem[]>([]);
  const [isDesignOpen, setIsDesignOpen] = useState(true);
  const [isHeatedFloorOpen, setIsHeatedFloorOpen] = useState(true);
  const [isConstructionOpen, setIsConstructionOpen] = useState(true);

  // Ref to track user actions and prevent context updates during user edits
  const isUserActionRef = useRef(false);

  // Sync local state with context
  useEffect(() => {
    setLocalMaterials(contextMaterials);
  }, [contextMaterials]);

  // Note: Auto-generation is handled by EstimateWorkflowContext
  // This component just syncs local state with context and allows manual editing
  // The context generates items with 'fl-' prefix IDs when design changes

  // Handle adding new materials
  const handleAddDesignMaterial = useCallback(() => {
    const newItem: MaterialItem = {
      id: `material-design-${Date.now()}-${Math.random()
        .toString(36)
        .substring(2, 11)}`,
      name: 'Custom Design Material',
      quantity: '1',
      unit: '',
      price: '0',
      scope: 'design',
      source: 'custom',
      isAutoGenerated: false,
    };

    isUserActionRef.current = true;
    setLocalMaterials((prev) => {
      const updatedMaterials = [...prev, newItem];

      setTimeout(() => {
        setMaterialItems('floors', updatedMaterials);
        isUserActionRef.current = false;
      }, 100);

      return updatedMaterials;
    });
  }, [setMaterialItems]);

  const handleAddHeatedFloorMaterial = useCallback(() => {
    const newItem: MaterialItem = {
      id: `material-heated-${Date.now()}-${Math.random()
        .toString(36)
        .substring(2, 11)}`,
      name: 'Custom Heated Floor Material',
      quantity: '1',
      unit: '',
      price: '0',
      scope: 'heated_floor',
      source: 'custom',
      isAutoGenerated: false,
    };

    isUserActionRef.current = true;
    setLocalMaterials((prev) => {
      const updatedMaterials = [...prev, newItem];

      setTimeout(() => {
        setMaterialItems('floors', updatedMaterials);
        isUserActionRef.current = false;
      }, 100);

      return updatedMaterials;
    });
  }, [setMaterialItems]);

  const handleAddConstructionMaterial = useCallback(() => {
    const newItem: MaterialItem = {
      id: `material-construction-${Date.now()}-${Math.random()
        .toString(36)
        .substring(2, 11)}`,
      name: 'Custom Construction Material',
      quantity: '1',
      unit: '',
      price: '0',
      scope: 'construction',
      source: 'custom',
      isAutoGenerated: false,
    };

    isUserActionRef.current = true;
    setLocalMaterials((prev) => {
      const updatedMaterials = [...prev, newItem];

      setTimeout(() => {
        setMaterialItems('floors', updatedMaterials);
        isUserActionRef.current = false;
      }, 100);

      return updatedMaterials;
    });
  }, [setMaterialItems]);

  // Handle material changes
  const handleMaterialChange = useCallback(
    (id: string, field: keyof MaterialItem, value: string) => {
      isUserActionRef.current = true;

      // Update local state immediately - also mark as no longer auto-generated to preserve edits
      setLocalMaterials((prev) => {
        const updatedMaterials = prev.map((item) =>
          item.id === id
            ? { ...item, [field]: value, isAutoGenerated: false, source: 'custom' }
            : item
        );

        // Update context with the latest materials
        setTimeout(() => {
          setMaterialItems('floors', updatedMaterials);
          isUserActionRef.current = false;
        }, 100);

        return updatedMaterials;
      });
    },
    [setMaterialItems]
  );

  // Handle deleting material
  const handleDeleteMaterial = useCallback(
    (id: string) => {
      isUserActionRef.current = true;

      setLocalMaterials((prev) => {
        const updatedMaterials = prev.filter((item) => item.id !== id);

        setTimeout(() => {
          setMaterialItems('floors', updatedMaterials);
          isUserActionRef.current = false;
        }, 100);

        return updatedMaterials;
      });
    },
    [setMaterialItems]
  );

  const materials = localMaterials;

  const renderMaterialItem = useCallback(
    (material: MaterialItem) => {
      return (
        <div
          key={material.id}
          className={`p-3 bg-white rounded-lg border border-slate-300`}
        >
          <div className='flex items-center gap-2 mb-2'>
            <Input
              type='text'
              value={material.name}
              onChange={(e) =>
                handleMaterialChange(material.id, 'name', e.target.value)
              }
              placeholder='Supply Name'
              className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none`}
            />
            <Button
              onClick={() => handleDeleteMaterial(material.id)}
              variant='ghost'
              size='sm'
              className='text-red-500 hover:text-red-700 p-1 h-auto'
            >
              <Trash2 size={16} />
            </Button>
          </div>
          <div className='grid grid-cols-2 gap-3'>
            <div>
              <label className='text-xs text-slate-500'>Quantity{material.unit ? ` (${material.unit})` : ''}</label>
              <Input
                type='number'
                value={material.quantity}
                onChange={(e) =>
                  handleMaterialChange(material.id, 'quantity', e.target.value)
                }
                placeholder='0'
                className={`text-center border-blue-300 focus:border-blue-500`}
              />
            </div>
            <div>
              <label className='text-xs text-slate-500'>Price/Unit ($)</label>
              <Input
                type='number'
                value={material.price}
                onChange={(e) =>
                  handleMaterialChange(material.id, 'price', e.target.value)
                }
                placeholder='0.00'
                className={`text-center border-blue-300 focus:border-blue-500`}
              />
            </div>
            <div className='col-span-2'>
              <label className='text-xs text-slate-500'>Total</label>
              <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
                $
                {(
                  (parseFloat(material.quantity) || 0) *
                  (parseFloat(material.price) || 0)
                ).toFixed(2)}
              </div>
            </div>
          </div>
        </div>
      );
    },
    [handleMaterialChange, handleDeleteMaterial]
  );

  // Separate materials by scope
  const designMaterials = useMemo(() => {
    return materials.filter((item) => item.scope === 'design');
  }, [materials]);

  const heatedFloorMaterials = useMemo(() => {
    return materials.filter(
      (item) =>
        item.scope === 'heated_floor' ||
        item.name.toLowerCase().includes('heated') ||
        item.name.toLowerCase().includes('thermostat') ||
        item.name.toLowerCase().includes('ditra-heat') ||
        item.name.toLowerCase().includes('nuheat') ||
        item.id?.startsWith('fl-mat-ditra-heat') ||
        item.id?.startsWith('fl-mat-nuheat') ||
        item.id?.startsWith('fl-mat-custom-heated')
    );
  }, [materials]);

  const constructionMaterials = useMemo(() => {
    return materials.filter(
      (item) =>
        item.scope === 'construction' &&
        !item.name.toLowerCase().includes('heated') &&
        !item.name.toLowerCase().includes('thermostat') &&
        !item.name.toLowerCase().includes('ditra-heat') &&
        !item.name.toLowerCase().includes('nuheat') &&
        !item.id?.startsWith('fl-mat-ditra-heat') &&
        !item.id?.startsWith('fl-mat-nuheat') &&
        !item.id?.startsWith('fl-mat-custom-heated')
    );
  }, [materials]);

  // Calculate totals for design materials
  const designTotal = designMaterials.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  // Calculate totals for heated floor materials
  const heatedFloorTotal = heatedFloorMaterials.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  // Calculate totals for construction materials
  const constructionTotal = constructionMaterials.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  // Calculate overall total
  const total = materials.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-center'>
        <h2 className='text-2xl font-bold text-slate-800'>
          Materials & Supplies
        </h2>
        <div className='text-right'>
          <p className='font-bold text-blue-600 text-lg'>${total.toFixed(2)}</p>
        </div>
      </div>

      <div className='space-y-4'>
        {/* Design Materials Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsDesignOpen(!isDesignOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isDesignOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Design Materials
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${designTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isDesignOpen && (
              <>
                {designMaterials.length > 0 ? (
                  <div className='space-y-2'>
                    {designMaterials.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No design materials added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddDesignMaterial}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        {/* Heated Floor Materials Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsHeatedFloorOpen(!isHeatedFloorOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isHeatedFloorOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Heated Floor Materials
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${heatedFloorTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isHeatedFloorOpen && (
              <>
                {heatedFloorMaterials.length > 0 ? (
                  <div className='space-y-2'>
                    {heatedFloorMaterials.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No heated floor materials added yet.
                  </p>
                )}

                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddHeatedFloorMaterial}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        {/* Construction Materials Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsConstructionOpen(!isConstructionOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isConstructionOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Construction Materials
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${constructionTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isConstructionOpen && (
              <>
                {constructionMaterials.length > 0 ? (
                  <div className='space-y-2'>
                    {constructionMaterials.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No construction materials added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddConstructionMaterial}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
