/* eslint-disable react-hooks/exhaustive-deps */
'use client';

import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
} from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { TRADE_CATEGORIES, TRADE_TASKS } from '@/lib/constants';
import { LaborItem } from '@/types/estimate';
import { Trash2, Plus } from 'lucide-react';

interface TradeDesignData {
  selectedTrades: string[];
  tradeRates: Record<string, number>;
  projectChoices: Record<string, Array<{ id: string; quantity: number }>>;
  taskInfo: Record<
    string,
    {
      pricingModel: 'flat' | 'hourly';
      price: number;
      hours: number;
      quantity: number;
    }
  >;
  [key: string]: unknown;
}

export default function TradeLaborSection() {
  const { getDesignData, getLaborItems, setLaborItems, isReloading } =
    useEstimateWorkflowContext();

  const designData = getDesignData('trade') as TradeDesignData | null;
  const design = useMemo(
    () =>
      designData || {
        selectedTrades: [],
        tradeRates: {},
        projectChoices: {},
        taskInfo: {},
      },
    [designData]
  );

  const [localLaborItems, setLocalLaborItems] = useState<LaborItem[]>([]);
  const [newItemName, setNewItemName] = useState('');
  const [newItemHours, setNewItemHours] = useState('');
  const [newItemRate, setNewItemRate] = useState('');

  // Refs to track user actions
  const userActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Get current items from context
  const contextLaborItems = getLaborItems('trade');

  // Effect to handle design changes and context sync
  useEffect(() => {
    if (isReloading) {
      setLocalLaborItems(contextLaborItems);
      return;
    }

    // Always prioritize context data when available
    if (contextLaborItems.length > 0) {
      setLocalLaborItems(contextLaborItems);
      return;
    }

    // Only auto-generate if there's no context data and no user action
    if (!userActionRef.current) {
      // Check if design choices have changed
      const choicesString = JSON.stringify({
        selectedTrades: design.selectedTrades,
        projectChoices: design.projectChoices,
        taskInfo: design.taskInfo,
        tradeRates: design.tradeRates,
      });

      if (choicesString !== processedChoicesRef.current) {
        processedChoicesRef.current = choicesString;

        // Generate labor items inline to avoid dependency issues
        const laborItems: LaborItem[] = [];
        design.selectedTrades.forEach((tradeId) => {
          const category =
            TRADE_CATEGORIES[tradeId as keyof typeof TRADE_CATEGORIES];
          const tasks = TRADE_TASKS[tradeId as keyof typeof TRADE_TASKS] || [];
          const selectedTasks = design.projectChoices?.[tradeId] || [];
          const tradeRate =
            design.tradeRates?.[tradeId] || category.defaultRate;

          selectedTasks.forEach((choice) => {
            const task = tasks.find((t) => t.id === choice.id);
            if (!task) return;

            const taskInfo = design.taskInfo?.[task.id];
            const pricingModel = taskInfo?.pricingModel || task.pricingModel;

            if (pricingModel === 'flat') {
              // Flat rate pricing
              const price = taskInfo?.price || task.defaultPrice;

              const laborItem = {
                id: `lab-${task.id}`,
                name: task.name,
                hours: '0',
                rate: price.toString(),
                scope: 'construction',
                category: 'construction' as const,
                isAutoGenerated: true,
              };

              laborItems.push(laborItem);
            } else {
              // Hourly pricing
              const hours = taskInfo?.hours || task.defaultHours;
              const rate = tradeRate;

              const laborItem = {
                id: `lab-${task.id}`,
                name: task.name,
                hours: hours.toString(),
                rate: rate.toString(),
                scope: 'construction',
                category: 'construction' as const,
                isAutoGenerated: true,
              };

              laborItems.push(laborItem);
            }
          });
        });

        setLocalLaborItems(laborItems);
        setLaborItems('trade', laborItems);
      }
    }
  }, [
    design.selectedTrades,
    design.projectChoices,
    design.taskInfo,
    design.tradeRates,
    isReloading,
  ]);

  const handleItemChange = useCallback(
    (id: string, field: 'name' | 'hours' | 'rate', value: string) => {
      userActionRef.current = true;
      const updatedItems = localLaborItems.map((item) => {
        if (item.id === id) {
          return { ...item, [field]: value };
        }
        return item;
      });

      setLocalLaborItems(updatedItems);
      setLaborItems('trade', updatedItems);
    },
    [localLaborItems, setLaborItems]
  );

  const handleDeleteItem = useCallback(
    (id: string) => {
      userActionRef.current = true;
      const updatedItems = localLaborItems.filter((item) => item.id !== id);

      setLocalLaborItems(updatedItems);
      setLaborItems('trade', updatedItems);
    },
    [localLaborItems, setLaborItems]
  );

  const handleAddCustomItem = useCallback(() => {
    if (!newItemName.trim()) {
      return;
    }

    const newItem: LaborItem = {
      id: `custom-${Date.now()}`,
      name: newItemName,
      hours: newItemHours,
      rate: newItemRate,
      scope: 'construction',
      category: 'construction' as const,
      isAutoGenerated: false,
    };

    const updatedItems = [...localLaborItems, newItem];
    setLocalLaborItems(updatedItems);
    setLaborItems('trade', updatedItems);

    // Reset form
    setNewItemName('');
    setNewItemHours('');
    setNewItemRate('');
  }, [newItemName, newItemHours, newItemRate, localLaborItems, setLaborItems]);

  const totalLaborCost = useMemo(() => {
    return localLaborItems.reduce((sum, item) => {
      const hours = parseFloat(item.hours) || 0;
      const rate = parseFloat(item.rate) || 0;
      return sum + hours * rate;
    }, 0);
  }, [localLaborItems]);

  const totalHours = useMemo(() => {
    return localLaborItems.reduce((sum, item) => {
      return sum + (parseFloat(item.hours) || 0);
    }, 0);
  }, [localLaborItems]);

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-baseline'>
        <h2 className='text-2xl font-bold text-slate-800'>Labor</h2>
      </div>
      <div className='space-y-4'>
        {localLaborItems.length > 0 && (
          <Card>
            <CardContent className='p-3 space-y-3'>
              <div className='flex justify-between items-center'>
                <div className='flex items-center gap-2 justify-between w-full'>
                  <div className='flex items-center gap-2'>
                    <h3 className='text-lg font-semibold text-slate-700'>
                      Hourly Labor
                    </h3>
                  </div>
                  <span className='text-sm text-slate-500'>
                    {totalHours.toFixed(1)} hrs
                  </span>
                  <p className='font-bold text-blue-600 text-sm'>
                    ${totalLaborCost.toFixed(2)}
                  </p>
                </div>
              </div>
              {localLaborItems.map((item) => (
                <div
                  key={item.id}
                  className={`p-3 rounded-lg border bg-white shadow-sm w-full ${
                    item.color || 'border-slate-200'
                  }`}
                >
                  <div className='flex items-center gap-2 mb-2 w-full'>
                    <Input
                      type='text'
                      value={item.name}
                      onChange={(e) =>
                        handleItemChange(item.id, 'name', e.target.value)
                      }
                      placeholder='Labor item name'
                      className='border-b-2 border-t-0 border-l-0 border-r-0 border-blue-300 focus:border-blue-500 focus:outline-none bg-transparent w-44 sm:w-full'
                    />
                    <Button
                      onClick={() => handleDeleteItem(item.id)}
                      variant='ghost'
                      size='sm'
                      className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
                    >
                      <Trash2 size={16} />
                    </Button>
                  </div>
                  <div className='grid grid-cols-3 gap-3 w-full'>
                    <div className='w-full'>
                      <label className='text-xs text-slate-500'>Hours</label>
                      <Input
                        type='number'
                        value={item.hours}
                        onChange={(e) =>
                          handleItemChange(item.id, 'hours', e.target.value)
                        }
                        placeholder='0'
                        className='text-center w-full border-blue-300 focus:border-blue-500'
                      />
                    </div>
                    <div className='w-full'>
                      <label className='text-xs text-slate-500'>
                        Rate ($/hr)
                      </label>
                      <Input
                        type='number'
                        value={item.rate}
                        onChange={(e) =>
                          handleItemChange(item.id, 'rate', e.target.value)
                        }
                        placeholder='0'
                        className='text-center w-full border-blue-300 focus:border-blue-500'
                      />
                    </div>
                    <div className='w-full'>
                      <label className='text-xs text-slate-500'>Total</label>
                      <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
                        $
                        {(
                          (parseFloat(item.hours) || 0) *
                          (parseFloat(item.rate) || 0)
                        ).toFixed(2)}
                      </div>
                    </div>
                  </div>
                </div>
              ))}

              <div className='flex justify-center'>
                <Button
                  onClick={handleAddCustomItem}
                  className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                >
                  <Plus size={16} />
                  Add Item
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
