'use client';

import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { useContractorContext } from '@/contexts/ContractorContext';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';
import { LaborItem } from '@/types/estimate';
import {
  TradeDesignData,
  DEFAULT_TRADE_DESIGN,
  FLAT_PRICES,
  DEFAULT_HOURS,
} from '../design/TradeSection';

// Freestanding tub bundle discount constants
const TUB_BUNDLE_FLAT_DISCOUNT = 150;
const TUB_BUNDLE_HOURS_DISCOUNT = 1.0;

export default function TradeLaborSection() {
  const { getDesignData, getLaborItems, setLaborItems, isReloading } =
    useEstimateWorkflowContext();

  const { hourlyRate: contractorHourlyRate } = useContractorContext();

  const designData = getDesignData('trade') as TradeDesignData | null;
  const design = useMemo(
    () => ({
      ...DEFAULT_TRADE_DESIGN,
      ...designData,
      pricingModes: {
        ...DEFAULT_TRADE_DESIGN.pricingModes,
        ...(designData?.pricingModes || {}),
      },
      tradeRates: {
        ...DEFAULT_TRADE_DESIGN.tradeRates,
        ...(designData?.tradeRates || {}),
      },
      priceOverrides: {
        ...DEFAULT_TRADE_DESIGN.priceOverrides,
        ...(designData?.priceOverrides || {}),
      },
      hoursOverrides: {
        ...DEFAULT_TRADE_DESIGN.hoursOverrides,
        ...(designData?.hoursOverrides || {}),
      },
      rateOverrides: {
        ...DEFAULT_TRADE_DESIGN.rateOverrides,
        ...(designData?.rateOverrides || {}),
      },
    }),
    [designData]
  );

  const [localLaborItems, setLocalLaborItems] = useState<LaborItem[]>([]);
  const [isPlumbingOpen, setIsPlumbingOpen] = useState(true);
  const [isElectricalOpen, setIsElectricalOpen] = useState(true);
  const [isCustomOpen, setIsCustomOpen] = useState(true);

  // Refs to track user actions
  const userActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Get current items from context
  const contextLaborItems = getLaborItems('trade');

  // Helper to get effective price (considering overrides)
  const getEffectivePrice = useCallback(
    (taskId: string, defaultPrice: number): number => {
      if (design.priceOverrides[taskId] !== undefined) {
        return design.priceOverrides[taskId];
      }
      return defaultPrice;
    },
    [design.priceOverrides]
  );

  // Helper to get effective hours (considering overrides)
  const getEffectiveHours = useCallback(
    (taskId: string, defaultHours: number): number => {
      if (design.hoursOverrides[taskId] !== undefined) {
        return design.hoursOverrides[taskId];
      }
      return defaultHours;
    },
    [design.hoursOverrides]
  );

  // Helper to get effective rate (considering overrides)
  const getEffectiveRate = useCallback(
    (taskId: string, category: 'plumbing' | 'electrical'): number => {
      if (design.rateOverrides[taskId] !== undefined) {
        return design.rateOverrides[taskId];
      }
      return design.tradeRates[category];
    },
    [design.rateOverrides, design.tradeRates]
  );

  // Auto-populate labor items based on selected tasks
  useEffect(() => {
    if (isReloading || userActionRef.current) {
      userActionRef.current = false;
      return;
    }

    // Create a key based on all design choices to detect changes
    const choicesKey = JSON.stringify(design);

    // Skip if choices haven't changed
    if (processedChoicesRef.current === choicesKey) return;

    // Preserve custom items (non-auto-generated)
    const contextLabor = contextLaborItems || [];
    const customLaborItems = contextLabor.filter(
      (item) => item.isAutoGenerated === false
    );

    const newLaborItems: LaborItem[] = [];

    const plumbingMode = design.pricingModes.plumbing;
    const electricalMode = design.pricingModes.electrical;
    const plumbingRate = design.tradeRates.plumbing;
    const electricalRate = design.tradeRates.electrical;

    // =========================================================================
    // PLUMBING - ROUGH-IN
    // =========================================================================

    if (design.moveToiletDrainSupply) {
      const taskId = 'move_toilet_drain';
      newLaborItems.push({
        id: 'move-toilet-drain-supply',
        taskId,
        name: 'Move toilet drain and supply',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: design.moveToiletDrainSupplyQuantity || 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.relocateFixtureDrain) {
      const taskId = 'move_drain';
      newLaborItems.push({
        id: 'relocate-fixture-drain',
        taskId,
        name: 'Relocate Fixture Drain (Sink / Shower / Tub)',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: design.relocateFixtureDrainQuantity || 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installNewShowerValve) {
      const taskId = 'install_new_shower_valve';
      newLaborItems.push({
        id: 'install-new-shower-valve',
        taskId,
        name: 'Replace / Install Shower Valve',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.roughInDiverter) {
      const taskId = 'rough_in_diverter';
      newLaborItems.push({
        id: 'rough-in-diverter',
        taskId,
        name: 'Add Shower Diverter (Handheld / Rainhead)',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.addVanityPlumbingRoughIn) {
      const taskId = 'rough_in_vanity';
      newLaborItems.push({
        id: 'add-vanity-plumbing-rough-in',
        taskId,
        name: 'Add Vanity Plumbing Rough-In',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: design.addVanityPlumbingRoughInQuantity || 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.addFreestandingTubRoughIn) {
      const taskId = 'install_standalone_tub_roughin';
      newLaborItems.push({
        id: 'add-freestanding-tub-rough-in',
        taskId,
        name: 'Add Freestanding Tub Rough-In',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.addBidetPlumbingRoughIn) {
      const taskId = 'rough_in_bidet';
      newLaborItems.push({
        id: 'add-bidet-plumbing-rough-in',
        taskId,
        name: 'Add Bidet Plumbing Rough-In',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: design.addBidetPlumbingRoughInQuantity || 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // =========================================================================
    // PLUMBING - FIXTURE INSTALLATION
    // =========================================================================

    // Vanity Cabinet Installation
    if (design.vanityInstallationType !== 'none') {
      const isDouble = design.vanityInstallationType === 'double';
      const taskId = isDouble ? 'install_vanity_double' : 'install_vanity_single';
      newLaborItems.push({
        id: 'install-vanity-cabinet',
        taskId,
        name: `Install Vanity Cabinet (${isDouble ? 'Double' : 'Single'})`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Connect Sink Drain(s) - standalone with quantity
    if (design.connectSinkDrains) {
      const taskId = 'install_vanity_plumbing';
      newLaborItems.push({
        id: 'connect-sink-drains',
        taskId,
        name: 'Connect Sink Drain(s)',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: design.connectSinkDrainsQuantity || 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Install Vanity Faucet & Supply Lines - standalone with quantity
    if (design.installVanityFaucetSupplyLines) {
      const taskId = 'install_faucet';
      newLaborItems.push({
        id: 'install-vanity-faucet-supply',
        taskId,
        name: 'Install Vanity Faucet & Supply Lines',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: design.installVanityFaucetSupplyLinesQuantity || 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Shower Trim Components - base package (valve + head, optionally with spout)
    const hasBaseTrim = design.showerTrimValve || design.showerTrimShowerHead;
    if (hasBaseTrim) {
      // Spout included in trim package → use higher price, disable separate spout
      const includesSpout = design.showerTrimSpout;
      const taskId = includesSpout ? 'install_shower_trim_with_spout' : 'install_shower_trim';
      newLaborItems.push({
        id: 'install-shower-trim',
        taskId,
        name: `Shower Trim Components${includesSpout ? ' (incl. Spout)' : ''}`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Separate tub spout - only when spout is selected without base trim
    if (design.showerTrimSpout && !hasBaseTrim) {
      const taskId = 'install_tub_spout';
      newLaborItems.push({
        id: 'install-tub-spout',
        taskId,
        name: 'Install Tub Spout',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Handheld add-on
    if (design.showerTrimHandheld) {
      const taskId = 'install_handheld';
      newLaborItems.push({
        id: 'install-shower-trim-handheld',
        taskId,
        name: 'Install Handheld Shower',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Rainhead add-on
    if (design.showerTrimRainhead) {
      const taskId = 'install_rainhead';
      newLaborItems.push({
        id: 'install-shower-trim-rainhead',
        taskId,
        name: 'Install Rainhead Shower',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installToilet) {
      const taskId = 'install_toilet';
      newLaborItems.push({
        id: 'install-toilet',
        taskId,
        name: 'Install Toilet',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installBidetSeat) {
      const taskId = 'install_bidet';
      newLaborItems.push({
        id: 'install-bidet-seat',
        taskId,
        name: 'Install Bidet / Bidet Seat',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Freestanding Tub Finishing - with bundle discount if rough-in is also selected
    if (design.installFreestandingTubFaucet) {
      const taskId = 'install_standalone_tub_finishing';
      const hasRoughIn = design.addFreestandingTubRoughIn;

      // Check if user has overridden - if so, don't apply discount
      const hasHoursOverride = design.hoursOverrides[taskId] !== undefined;
      const hasPriceOverride = design.priceOverrides[taskId] !== undefined;

      let effectiveHours = getEffectiveHours(taskId, DEFAULT_HOURS[taskId]);
      let effectivePrice = getEffectivePrice(taskId, FLAT_PRICES[taskId]);

      // Apply bundle discount only if rough-in is selected AND no override exists
      if (hasRoughIn) {
        if (!hasHoursOverride) {
          effectiveHours = Math.max(0, effectiveHours - TUB_BUNDLE_HOURS_DISCOUNT);
        }
        if (!hasPriceOverride) {
          effectivePrice = Math.max(0, effectivePrice - TUB_BUNDLE_FLAT_DISCOUNT);
        }
      }

      newLaborItems.push({
        id: 'install-freestanding-tub-faucet',
        taskId,
        name: `Finish-only: Freestanding Tub + Faucet Connections${hasRoughIn ? ' (Bundle)' : ''}`,
        hours: effectiveHours.toString(),
        rate: getEffectiveRate(taskId, 'plumbing').toString(),
        flatPrice: effectivePrice.toString(),
        pricingMode: plumbingMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // =========================================================================
    // ELECTRICAL - ROUGH-IN
    // =========================================================================

    if (design.heatedFloorThermostatPower) {
      const taskId = 'elec_heated_floor_stat';
      newLaborItems.push({
        id: 'heated-floor-thermostat-power',
        taskId,
        name: 'Heated Floor Thermostat & Power',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.potLightQuantity > 0) {
      const taskId = 'install_pot_light';
      newLaborItems.push({
        id: 'add-recessed-pot-lights',
        taskId,
        name: `Add Recessed Pot Light(s) (x${design.potLightQuantity})`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: design.potLightQuantity,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.gfciOutletQuantity > 0) {
      const taskId = 'install_new_gfci';
      newLaborItems.push({
        id: 'add-vanity-gfci-outlets',
        taskId,
        name: `Add Vanity GFCI Outlet(s) (x${design.gfciOutletQuantity})`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: design.gfciOutletQuantity,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.bidetOutletQuantity > 0) {
      const taskId = 'elec_bidet_outlet';
      newLaborItems.push({
        id: 'add-toilet-bidet-power-outlet',
        taskId,
        name: `Add Toilet / Bidet Power Outlet(s) (x${design.bidetOutletQuantity})`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: design.bidetOutletQuantity,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.ledMirrorQuantity > 0) {
      const taskId = 'elec_led_mirror_power';
      newLaborItems.push({
        id: 'led-mirror-cabinet-power',
        taskId,
        name: `LED Mirror / Medicine Cabinet Power (x${design.ledMirrorQuantity})`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: design.ledMirrorQuantity,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // =========================================================================
    // ELECTRICAL - FIXTURE INSTALLATION
    // =========================================================================

    if (design.replaceBathroomExhaustFan) {
      const taskId = 'elec_exhaust_fan_rough_in';
      newLaborItems.push({
        id: 'replace-bathroom-exhaust-fan',
        taskId,
        name: 'Replace Bathroom Exhaust Fan',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.exhaustFanControl) {
      const taskId = 'elec_fan_control_upgrade';
      newLaborItems.push({
        id: 'exhaust-fan-control',
        taskId,
        name: 'Exhaust Fan Control (Timer / Humidity Sensor)',
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: 1,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.vanityWallLightQuantity > 0) {
      const taskId = 'elec_vanity_wall_light';
      newLaborItems.push({
        id: 'vanity-wall-light-fixtures',
        taskId,
        name: `Vanity / Wall Light Fixture(s) (finish-only) (x${design.vanityWallLightQuantity})`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: design.vanityWallLightQuantity,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.dimmerQuantity > 0) {
      const taskId = 'install_dimmer';
      newLaborItems.push({
        id: 'replace-light-switch-dimmer',
        taskId,
        name: `Replace Light Switch with Dimmer (finish-only) (x${design.dimmerQuantity})`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: design.dimmerQuantity,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.switchOutletQuantity > 0) {
      const taskId = 'replace_switch_outlet_finish';
      newLaborItems.push({
        id: 'replace-switch-or-outlet',
        taskId,
        name: `Replace Switch or Outlet (Finish-Only) (x${design.switchOutletQuantity})`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: design.switchOutletQuantity,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.showerPotLightQuantity > 0) {
      const taskId = 'replace_pot_light_wet';
      newLaborItems.push({
        id: 'replace-shower-pot-light',
        taskId,
        name: `Replace Shower Pot Light (Wet-Rated) (finish-only) (x${design.showerPotLightQuantity})`,
        hours: getEffectiveHours(taskId, DEFAULT_HOURS[taskId]).toString(),
        rate: getEffectiveRate(taskId, 'electrical').toString(),
        flatPrice: getEffectivePrice(taskId, FLAT_PRICES[taskId]).toString(),
        pricingMode: electricalMode,
        quantity: design.showerPotLightQuantity,
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // Merge custom items with auto-generated items
    const mergedLaborItems = [...customLaborItems, ...newLaborItems];

    // Update context
    setLaborItems('trade', mergedLaborItems);
    setLocalLaborItems(mergedLaborItems);

    // Update processed choices
    processedChoicesRef.current = choicesKey;
  }, [design, isReloading, setLaborItems, contextLaborItems, getEffectiveHours, getEffectivePrice, getEffectiveRate]);

  // Sync with context changes
  useEffect(() => {
    if (!isReloading) {
      setLocalLaborItems(contextLaborItems as LaborItem[]);
    }
  }, [contextLaborItems, isReloading]);

  // Handlers
  const handleAddLaborItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `labor-${Date.now()}`,
      name: '',
      hours: '1',
      rate: contractorHourlyRate.toString(),
      flatPrice: '0',
      pricingMode: 'hourly',
      quantity: 1,
      category: 'construction',
      isAutoGenerated: false,
      color: 'gray',
    };

    const updatedItems = [...localLaborItems, newItem];
    setLocalLaborItems(updatedItems);
    setLaborItems('trade', updatedItems);
    userActionRef.current = true;
  }, [localLaborItems, contractorHourlyRate, setLaborItems]);

  const handleUpdateLaborItem = useCallback(
    (id: string, field: keyof LaborItem, value: string | number) => {
      const updatedItems = localLaborItems.map((item) =>
        item.id === id ? { ...item, [field]: value } : item
      );
      setLocalLaborItems(updatedItems);
      setLaborItems('trade', updatedItems);
      userActionRef.current = true;
    },
    [localLaborItems, setLaborItems]
  );

  const handleDeleteLaborItem = useCallback(
    (id: string) => {
      const updatedItems = localLaborItems.filter((item) => item.id !== id);
      setLocalLaborItems(updatedItems);
      setLaborItems('trade', updatedItems);
      userActionRef.current = true;
    },
    [localLaborItems, setLaborItems]
  );

  // Calculate item cost based on pricing mode
  const calculateItemCost = useCallback((item: LaborItem): number => {
    const quantity = item.quantity || 1;

    if (item.pricingMode === 'flat') {
      const flatPrice = parseFloat(item.flatPrice || '0') || 0;
      return flatPrice * quantity;
    } else {
      const hours = parseFloat(item.hours) || 0;
      const rate = parseFloat(item.rate) || 0;
      return hours * rate * quantity;
    }
  }, []);

  // Calculate totals
  const laborTotal = useMemo(() => {
    return localLaborItems.reduce((total, item) => {
      return total + calculateItemCost(item);
    }, 0);
  }, [localLaborItems, calculateItemCost]);

  const totalHours = useMemo(() => {
    return localLaborItems.reduce((total, item) => {
      if (item.pricingMode === 'hourly') {
        const hours = parseFloat(item.hours) || 0;
        const quantity = item.quantity || 1;
        return total + hours * quantity;
      }
      return total;
    }, 0);
  }, [localLaborItems]);

  // Group items by category
  const plumbingItems = localLaborItems.filter((item) => item.color === 'blue');
  const electricalItems = localLaborItems.filter(
    (item) => item.color === 'green'
  );
  const customItems = localLaborItems.filter((item) => item.color === 'gray');

  // Calculate totals for each category
  const plumbingHours = plumbingItems.reduce(
    (sum, item) => {
      if (item.pricingMode === 'hourly') {
        return sum + (parseFloat(item.hours) || 0) * (item.quantity || 1);
      }
      return sum;
    },
    0
  );
  const plumbingTotal = plumbingItems.reduce(
    (sum, item) => sum + calculateItemCost(item),
    0
  );

  const electricalHours = electricalItems.reduce(
    (sum, item) => {
      if (item.pricingMode === 'hourly') {
        return sum + (parseFloat(item.hours) || 0) * (item.quantity || 1);
      }
      return sum;
    },
    0
  );
  const electricalTotal = electricalItems.reduce(
    (sum, item) => sum + calculateItemCost(item),
    0
  );

  const customHours = customItems.reduce(
    (sum, item) => {
      if (item.pricingMode === 'hourly') {
        return sum + (parseFloat(item.hours) || 0) * (item.quantity || 1);
      }
      return sum;
    },
    0
  );
  const customTotal = customItems.reduce(
    (sum, item) => sum + calculateItemCost(item),
    0
  );

  const renderLaborItem = useCallback(
    (item: LaborItem) => {
      const itemCost = calculateItemCost(item);
      const isFlat = item.pricingMode === 'flat';

      return (
        <div
          key={item.id}
          className='p-3 bg-white rounded-lg border border-slate-200 shadow-sm w-full'
        >
          <div className='flex items-center gap-2 mb-2 w-full'>
            <Input
              type='text'
              value={item.name}
              onChange={(e) =>
                handleUpdateLaborItem(item.id, 'name', e.target.value)
              }
              placeholder='Labor Task'
              className='border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full'
            />
            <Button
              onClick={() => handleDeleteLaborItem(item.id)}
              variant='ghost'
              size='sm'
              className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
            >
              <Trash2 size={16} />
            </Button>
          </div>

          {/* Pricing mode indicator */}
          <div className='text-xs text-slate-500 mb-2'>
            Mode: {isFlat ? 'Flat Rate' : 'Hourly'}
            {(item.quantity || 1) > 1 && ` | Qty: ${item.quantity}`}
          </div>

          <div className='grid grid-cols-2 gap-3'>
            {isFlat ? (
              <div className='w-full col-span-2'>
                <label className='text-xs text-slate-500'>Flat Price ($)</label>
                <Input
                  type='number'
                  value={item.flatPrice || '0'}
                  onChange={(e) =>
                    handleUpdateLaborItem(item.id, 'flatPrice', e.target.value)
                  }
                  placeholder='0'
                  className='text-center w-full border-blue-300 focus:border-blue-500'
                />
              </div>
            ) : (
              <>
                <div className='w-full'>
                  <label className='text-xs text-slate-500'>Hours</label>
                  <Input
                    type='number'
                    value={item.hours}
                    onChange={(e) =>
                      handleUpdateLaborItem(item.id, 'hours', e.target.value)
                    }
                    placeholder='0'
                    className='text-center w-full border-blue-300 focus:border-blue-500'
                  />
                </div>
                <div className='w-full'>
                  <label className='text-xs text-slate-500'>Rate ($/hr)</label>
                  <Input
                    type='number'
                    value={item.rate}
                    onChange={(e) =>
                      handleUpdateLaborItem(item.id, 'rate', e.target.value)
                    }
                    placeholder='0'
                    className='text-center w-full border-blue-300 focus:border-blue-500'
                  />
                </div>
              </>
            )}
            <div className='col-span-2 w-full'>
              <label className='text-xs text-slate-500'>Total</label>
              <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
                ${itemCost.toFixed(2)}
              </div>
            </div>
          </div>
        </div>
      );
    },
    [handleUpdateLaborItem, handleDeleteLaborItem, calculateItemCost]
  );

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-baseline'>
        <h2 className='text-2xl font-bold text-slate-800'>Labor</h2>
        {totalHours > 0 && (
          <div className='flex items-center gap-2 text-sm text-slate-600'>
            <span className='font-semibold text-xl text-slate-800'>
              {totalHours.toFixed(1)} hrs
            </span>
          </div>
        )}
        <div className='flex items-center gap-2 text-sm text-slate-600'>
          <span className='font-semibold text-xl text-blue-600'>
            ${laborTotal.toFixed(2)}
          </span>
        </div>
      </div>

      <div className='space-y-4'>
        {/* Plumbing */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsPlumbingOpen(!isPlumbingOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isPlumbingOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Plumbing
                  </h3>
                </div>
                {design.pricingModes.plumbing === 'hourly' && (
                  <span className='text-sm text-slate-500'>
                    {plumbingHours.toFixed(1)} hrs
                  </span>
                )}
                <p className='font-bold text-blue-600 text-sm'>
                  ${plumbingTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isPlumbingOpen && (
              <>
                {plumbingItems.length > 0 ? (
                  <div className='space-y-2'>
                    {plumbingItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No plumbing items added yet. Select tasks in Design section.
                  </p>
                )}
              </>
            )}
          </CardContent>
        </Card>

        {/* Electrical */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsElectricalOpen(!isElectricalOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isElectricalOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Electrical
                  </h3>
                </div>
                {design.pricingModes.electrical === 'hourly' && (
                  <span className='text-sm text-slate-500'>
                    {electricalHours.toFixed(1)} hrs
                  </span>
                )}
                <p className='font-bold text-blue-600 text-sm'>
                  ${electricalTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isElectricalOpen && (
              <>
                {electricalItems.length > 0 ? (
                  <div className='space-y-2'>
                    {electricalItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No electrical items added yet. Select tasks in Design section.
                  </p>
                )}
              </>
            )}
          </CardContent>
        </Card>

        {/* Custom Items */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsCustomOpen(!isCustomOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isCustomOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Custom Items
                  </h3>
                </div>
                <span className='text-sm text-slate-500'>
                  {customHours.toFixed(1)} hrs
                </span>
                <p className='font-bold text-blue-600 text-sm'>
                  ${customTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isCustomOpen && (
              <>
                {customItems.length > 0 ? (
                  <div className='space-y-2'>
                    {customItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No custom items added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddLaborItem}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
