'use client';

import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { useContractorContext } from '@/contexts/ContractorContext';
import {
  Plus,
  Trash2,
  ChevronDown,
  ChevronRight,
  DollarSign,
} from 'lucide-react';
import { Label } from '@/components/ui/label';

interface LaborItem {
  id: string;
  name: string;
  hours: string;
  rate: string;
  price: string;
  quantity: string;
  pricingModel: 'hourly' | 'flat';
  scope?: string;
  category?: 'design' | 'construction' | 'general';
  isAutoGenerated?: boolean;
  color?: string;
}

interface TradeDesignData {
  // Plumbing - Rough-in
  roughInNewPlumbing: boolean;
  moveToiletDrainSupply: boolean;
  installNewShowerValve: boolean;
  moveDrain: boolean;
  roughInStandaloneTub: boolean;

  // Plumbing - Finishing
  installVanitySinkPlumbing: boolean;
  installVanityFaucetSupply: boolean;
  installShowerTubTrimKit: boolean;
  installNewToilet: boolean;
  installStandaloneTubFaucet: boolean;

  // Electrical - Rough-in
  installNewOutlet: boolean;
  installNewGFCIOutlet: boolean;
  installNewPotLight: boolean;

  // Electrical - Finishing
  installNewLightFixture: boolean;
  installNewExhaustFan: boolean;
}

export default function TradeLaborSection() {
  const { getDesignData, getLaborItems, setLaborItems, isReloading } =
    useEstimateWorkflowContext();

  const { hourlyRate: contractorHourlyRate } = useContractorContext();

  const designData = getDesignData('trade') as TradeDesignData | null;
  const design = useMemo(
    () =>
      designData || {
        // Plumbing - Rough-in
        roughInNewPlumbing: false,
        moveToiletDrainSupply: false,
        installNewShowerValve: false,
        moveDrain: false,
        roughInStandaloneTub: false,

        // Plumbing - Finishing
        installVanitySinkPlumbing: false,
        installVanityFaucetSupply: false,
        installShowerTubTrimKit: false,
        installNewToilet: false,
        installStandaloneTubFaucet: false,

        // Electrical - Rough-in
        installNewOutlet: false,
        installNewGFCIOutlet: false,
        installNewPotLight: false,

        // Electrical - Finishing
        installNewLightFixture: false,
        installNewExhaustFan: false,
      },
    [designData]
  );

  const [localLaborItems, setLocalLaborItems] = useState<LaborItem[]>([]);
  const [isPlumbingOpen, setIsPlumbingOpen] = useState(true);
  const [isElectricalOpen, setIsElectricalOpen] = useState(true);
  const [showEditRatesModal, setShowEditRatesModal] = useState(false);
  const [tradeRates, setTradeRates] = useState({
    plumbing: 110,
    electrical: 95,
  });

  // Refs to track user actions
  const userActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Get current items from context
  const contextLaborItems = getLaborItems('trade');

  // Load trade rates from localStorage on mount
  useEffect(() => {
    const savedRates = localStorage.getItem('tradeRates');
    if (savedRates) {
      setTradeRates(JSON.parse(savedRates));
    }
  }, []);

  // Save trade rates to localStorage when changed
  useEffect(() => {
    localStorage.setItem('tradeRates', JSON.stringify(tradeRates));
  }, [tradeRates]);

  // Auto-populate labor items based on selected tasks
  useEffect(() => {
    if (isReloading || userActionRef.current) {
      userActionRef.current = false;
      return;
    }

    const newLaborItems: LaborItem[] = [];

    // Plumbing - Rough-in
    if (design.roughInNewPlumbing) {
      newLaborItems.push({
        id: 'rough-in-new-plumbing',
        name: 'Rough-in new plumbing',
        hours: '16',
        rate: tradeRates.plumbing.toString(),
        price: '0',
        quantity: '1',
        pricingModel: 'hourly',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.moveToiletDrainSupply) {
      newLaborItems.push({
        id: 'move-toilet-drain-supply',
        name: 'Move toilet drain and supply',
        hours: '5',
        rate: tradeRates.plumbing.toString(),
        price: '0',
        quantity: '1',
        pricingModel: 'hourly',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installNewShowerValve) {
      newLaborItems.push({
        id: 'install-new-shower-valve',
        name: 'Install new shower valve',
        hours: '4',
        rate: tradeRates.plumbing.toString(),
        price: '500',
        quantity: '1',
        pricingModel: 'flat',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.moveDrain) {
      newLaborItems.push({
        id: 'move-drain',
        name: 'Move drain',
        hours: '4',
        rate: tradeRates.plumbing.toString(),
        price: '0',
        quantity: '1',
        pricingModel: 'hourly',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.roughInStandaloneTub) {
      newLaborItems.push({
        id: 'rough-in-standalone-tub',
        name: 'Rough-in for stand-alone tub',
        hours: '6',
        rate: tradeRates.plumbing.toString(),
        price: '0',
        quantity: '1',
        pricingModel: 'hourly',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Plumbing - Finishing
    if (design.installVanitySinkPlumbing) {
      newLaborItems.push({
        id: 'install-vanity-sink-plumbing',
        name: 'Install vanity sink plumbing',
        hours: '2',
        rate: tradeRates.plumbing.toString(),
        price: '220',
        quantity: '1',
        pricingModel: 'flat',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installVanityFaucetSupply) {
      newLaborItems.push({
        id: 'install-vanity-faucet-supply',
        name: 'Install vanity faucet & supply lines',
        hours: '3',
        rate: tradeRates.plumbing.toString(),
        price: '0',
        quantity: '1',
        pricingModel: 'hourly',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installShowerTubTrimKit) {
      newLaborItems.push({
        id: 'install-shower-tub-trim-kit',
        name: 'Install shower & tub trim kit',
        hours: '4',
        rate: tradeRates.plumbing.toString(),
        price: '0',
        quantity: '1',
        pricingModel: 'hourly',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installNewToilet) {
      newLaborItems.push({
        id: 'install-new-toilet',
        name: 'Install new toilet',
        hours: '2',
        rate: tradeRates.plumbing.toString(),
        price: '0',
        quantity: '1',
        pricingModel: 'hourly',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installStandaloneTubFaucet) {
      newLaborItems.push({
        id: 'install-standalone-tub-faucet',
        name: 'Install stand-alone tub & faucet',
        hours: '4',
        rate: tradeRates.plumbing.toString(),
        price: '0',
        quantity: '1',
        pricingModel: 'hourly',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Electrical - Rough-in
    if (design.installNewOutlet) {
      newLaborItems.push({
        id: 'install-new-outlet',
        name: 'Install new outlet',
        hours: '2',
        rate: tradeRates.electrical.toString(),
        price: '150',
        quantity: '1',
        pricingModel: 'flat',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.installNewGFCIOutlet) {
      newLaborItems.push({
        id: 'install-new-gfci-outlet',
        name: 'Install new GFCI outlet',
        hours: '3',
        rate: tradeRates.electrical.toString(),
        price: '0',
        quantity: '1',
        pricingModel: 'hourly',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.installNewPotLight) {
      newLaborItems.push({
        id: 'install-new-pot-light',
        name: 'Install new pot light',
        hours: '2',
        rate: tradeRates.electrical.toString(),
        price: '180',
        quantity: '1',
        pricingModel: 'flat',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // Electrical - Finishing
    if (design.installNewLightFixture) {
      newLaborItems.push({
        id: 'install-new-light-fixture',
        name: 'Install new light fixture',
        hours: '2',
        rate: tradeRates.electrical.toString(),
        price: '145',
        quantity: '1',
        pricingModel: 'flat',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.installNewExhaustFan) {
      newLaborItems.push({
        id: 'install-new-exhaust-fan',
        name: 'Install new exhaust fan',
        hours: '3',
        rate: tradeRates.electrical.toString(),
        price: '300',
        quantity: '1',
        pricingModel: 'flat',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // Update context
    setLaborItems('trade', newLaborItems);
    setLocalLaborItems(newLaborItems);

    // Update processed choices
    const choicesString = JSON.stringify(design);
    processedChoicesRef.current = choicesString;
  }, [design, tradeRates, isReloading, setLaborItems]);

  // Sync with context changes
  useEffect(() => {
    if (!isReloading) {
      setLocalLaborItems(contextLaborItems as LaborItem[]);
    }
  }, [contextLaborItems, isReloading]);

  // Handlers
  const handleAddLaborItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `labor-${Date.now()}`,
      name: '',
      hours: '1',
      rate: contractorHourlyRate.toString(),
      price: '0',
      quantity: '1',
      pricingModel: 'hourly',
      category: 'construction',
      isAutoGenerated: false,
      color: 'gray',
    };

    const updatedItems = [...localLaborItems, newItem];
    setLocalLaborItems(updatedItems);
    setLaborItems('trade', updatedItems);
    userActionRef.current = true;
  }, [localLaborItems, contractorHourlyRate, setLaborItems]);

  const handleUpdateLaborItem = useCallback(
    (id: string, field: keyof LaborItem, value: string) => {
      const updatedItems = localLaborItems.map((item) =>
        item.id === id ? { ...item, [field]: value } : item
      );
      setLocalLaborItems(updatedItems);
      setLaborItems('trade', updatedItems);
      userActionRef.current = true;
    },
    [localLaborItems, setLaborItems]
  );

  const handleDeleteLaborItem = useCallback(
    (id: string) => {
      const updatedItems = localLaborItems.filter((item) => item.id !== id);
      setLocalLaborItems(updatedItems);
      setLaborItems('trade', updatedItems);
      userActionRef.current = true;
    },
    [localLaborItems, setLaborItems]
  );

  const handleUpdateTradeRate = useCallback(
    (trade: 'plumbing' | 'electrical', rate: number) => {
      setTradeRates((prev) => ({ ...prev, [trade]: rate }));
    },
    []
  );

  // Calculate totals
  const laborTotal = useMemo(() => {
    return localLaborItems.reduce((total, item) => {
      if (item.pricingModel === 'hourly') {
        const hours = parseFloat(item.hours) || 0;
        const rate = parseFloat(item.rate) || 0;
        const quantity = parseFloat(item.quantity) || 0;
        return total + hours * rate * quantity;
      } else {
        const price = parseFloat(item.price) || 0;
        const quantity = parseFloat(item.quantity) || 0;
        return total + price * quantity;
      }
    }, 0);
  }, [localLaborItems]);

  /* const totalHours = useMemo(() => {
    return localLaborItems.reduce((total, item) => {
      if (item.pricingModel === 'hourly') {
        const hours = parseFloat(item.hours) || 0;
        const quantity = parseFloat(item.quantity) || 0;
        return total + hours * quantity;
      }
      return total;
    }, 0);
  }, [localLaborItems]); */

  // Group items by category
  const plumbingItems = localLaborItems.filter((item) => item.color === 'blue');
  const electricalItems = localLaborItems.filter(
    (item) => item.color === 'green'
  );
  const customItems = localLaborItems.filter((item) => item.color === 'gray');

  const renderLaborItem = (item: LaborItem) => (
    <div
      key={item.id}
      className={`p-3 rounded-lg border bg-white border-gray-200`}
    >
      <div className='flex items-center justify-between mb-3'>
        <h4 className='font-medium text-gray-900'>{item.name}</h4>
        {!item.isAutoGenerated && (
          <Button
            onClick={() => handleDeleteLaborItem(item.id)}
            variant='ghost'
            size='sm'
            className='p-1 text-red-500 hover:text-red-700'
          >
            <Trash2 size={16} />
          </Button>
        )}
      </div>

      <div className='space-y-3'>
        {/* Pricing Model Toggle */}
        <div className='flex gap-2'>
          <Button
            onClick={() =>
              handleUpdateLaborItem(item.id, 'pricingModel', 'flat')
            }
            variant={item.pricingModel === 'flat' ? 'default' : 'outline'}
            size='sm'
            className={
              item.pricingModel === 'flat'
                ? 'bg-blue-600 text-white'
                : 'border-blue-200 text-blue-600 hover:bg-blue-50'
            }
          >
            Flat Rate
          </Button>
          <Button
            onClick={() =>
              handleUpdateLaborItem(item.id, 'pricingModel', 'hourly')
            }
            variant={item.pricingModel === 'hourly' ? 'default' : 'outline'}
            size='sm'
            className={
              item.pricingModel === 'hourly'
                ? 'bg-blue-600 text-white'
                : 'border-blue-200 text-blue-600 hover:bg-blue-50'
            }
          >
            Hourly
          </Button>
        </div>

        {/* Input Fields */}
        <div className='grid grid-cols-2 gap-3'>
          {item.pricingModel === 'hourly' ? (
            <>
              <div>
                <Label className='text-sm text-gray-600 mb-1 block'>
                  Hours
                </Label>
                <Input
                  type='number'
                  value={item.hours}
                  onChange={(e) =>
                    handleUpdateLaborItem(item.id, 'hours', e.target.value)
                  }
                  placeholder='Hours'
                  className='text-center'
                />
              </div>
              <div>
                <Label className='text-sm text-gray-600 mb-1 block'>
                  Rate ($/hr)
                </Label>
                <Input
                  type='number'
                  value={item.rate}
                  onChange={(e) =>
                    handleUpdateLaborItem(item.id, 'rate', e.target.value)
                  }
                  placeholder='Rate'
                  className='text-center'
                />
              </div>
            </>
          ) : (
            <>
              <div>
                <Label className='text-sm text-gray-600 mb-1 block'>
                  Price per Item
                </Label>
                <Input
                  type='number'
                  value={item.price}
                  onChange={(e) =>
                    handleUpdateLaborItem(item.id, 'price', e.target.value)
                  }
                  placeholder='Price'
                  className='text-center'
                />
              </div>
              <div>
                <Label className='text-sm text-gray-600 mb-1 block'>
                  Quantity
                </Label>
                <Input
                  type='number'
                  value={item.quantity}
                  onChange={(e) =>
                    handleUpdateLaborItem(item.id, 'quantity', e.target.value)
                  }
                  placeholder='Qty'
                  className='text-center'
                />
              </div>
            </>
          )}
        </div>

        {/* Total */}
        <div className='flex justify-between items-center pt-2 border-t'>
          <span className='text-sm font-medium text-gray-700'>Total</span>
          <span className='text-lg font-bold text-blue-600'>
            $
            {item.pricingModel === 'hourly'
              ? (
                  parseFloat(item.hours) *
                  parseFloat(item.rate) *
                  parseFloat(item.quantity)
                ).toFixed(2)
              : (parseFloat(item.price) * parseFloat(item.quantity)).toFixed(2)}
          </span>
        </div>
      </div>
    </div>
  );

  return (
    <div className='space-y-6'>
      <div className='pt-2'>
        <div className='flex justify-between items-baseline'>
          <h2 className='text-2xl font-bold text-slate-800'>Labor</h2>
          <div className='text-xl font-bold text-blue-600'>
            ${laborTotal.toFixed(2)}
          </div>
        </div>
        <div className='mt-4'>
          <Button
            onClick={() => setShowEditRatesModal(true)}
            className='flex items-center gap-2'
          >
            <DollarSign size={16} />
            Edit Trade Rates
          </Button>
        </div>
      </div>

      {/* Plumbing */}
      <Card>
        <CardContent className='p-0'>
          <div
            className='flex items-center justify-between p-4 cursor-pointer hover:bg-gray-50'
            onClick={() => setIsPlumbingOpen(!isPlumbingOpen)}
          >
            <h3 className='text-lg font-semibold text-gray-900'>Plumbing</h3>
            {isPlumbingOpen ? (
              <ChevronDown className='h-5 w-5 text-gray-500' />
            ) : (
              <ChevronRight className='h-5 w-5 text-gray-500' />
            )}
          </div>
          {isPlumbingOpen && (
            <div className='px-4 pb-4 space-y-3'>
              {plumbingItems.length > 0 ? (
                plumbingItems.map(renderLaborItem)
              ) : (
                <div className='text-center py-8 text-gray-500'>
                  No plumbing items yet. Select tasks in the Design section to
                  auto-populate items.
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Electrical */}
      <Card>
        <CardContent className='p-0'>
          <div
            className='flex items-center justify-between p-4 cursor-pointer hover:bg-gray-50'
            onClick={() => setIsElectricalOpen(!isElectricalOpen)}
          >
            <h3 className='text-lg font-semibold text-gray-900'>Electrical</h3>
            {isElectricalOpen ? (
              <ChevronDown className='h-5 w-5 text-gray-500' />
            ) : (
              <ChevronRight className='h-5 w-5 text-gray-500' />
            )}
          </div>
          {isElectricalOpen && (
            <div className='px-4 pb-4 space-y-3'>
              {electricalItems.length > 0 ? (
                electricalItems.map(renderLaborItem)
              ) : (
                <div className='text-center py-8 text-gray-500'>
                  No electrical items yet. Select tasks in the Design section to
                  auto-populate items.
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Custom Items */}
      <Card>
        <CardContent className='p-0'>
          <div className='flex items-center justify-between p-4'>
            <h3 className='text-lg font-semibold text-gray-900'>
              Custom Items
            </h3>
            <Button
              onClick={handleAddLaborItem}
              variant='outline'
              size='sm'
              className='flex items-center gap-2'
            >
              <Plus size={16} />
              Add Custom Labor
            </Button>
          </div>
          <div className='px-4 pb-4 space-y-3'>
            {customItems.length > 0 ? (
              customItems.map(renderLaborItem)
            ) : (
              <div className='text-center py-8 text-gray-500'>
                No custom items yet. Click &quot;Add Custom Labor&quot; to
                create one.
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Edit Trade Rates Modal */}
      {showEditRatesModal && (
        <div className='fixed inset-0 flex items-center justify-center z-50'>
          <div className='backdrop-overlay' />
          <div className='bg-white rounded-lg p-6 max-w-md w-full mx-4 relative z-10'>
            <div className='flex justify-between items-center mb-4'>
              <h3 className='text-lg font-semibold text-gray-900'>
                Edit Hourly Rates
              </h3>
              <Button
                onClick={() => setShowEditRatesModal(false)}
                variant='ghost'
                size='sm'
              >
                Done
              </Button>
            </div>

            <div className='space-y-4'>
              <div>
                <Label className='text-sm font-medium text-gray-700 mb-2 block'>
                  Plumbing
                </Label>
                <div className='flex items-center gap-2'>
                  <span className='text-gray-500'>$</span>
                  <Input
                    type='number'
                    value={tradeRates.plumbing.toString()}
                    onChange={(e) =>
                      handleUpdateTradeRate(
                        'plumbing',
                        parseFloat(e.target.value) || 0
                      )
                    }
                    className='text-center'
                  />
                  <span className='text-gray-500'>/hr</span>
                </div>
              </div>

              <div>
                <Label className='text-sm font-medium text-gray-700 mb-2 block'>
                  Electrical
                </Label>
                <div className='flex items-center gap-2'>
                  <span className='text-gray-500'>$</span>
                  <Input
                    type='number'
                    value={tradeRates.electrical.toString()}
                    onChange={(e) =>
                      handleUpdateTradeRate(
                        'electrical',
                        parseFloat(e.target.value) || 0
                      )
                    }
                    className='text-center'
                  />
                  <span className='text-gray-500'>/hr</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
