'use client';

import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { useContractorContext } from '@/contexts/ContractorContext';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';

interface LaborItem {
  id: string;
  name: string;
  hours: string;
  rate: string;
  scope?: string;
  category?: 'design' | 'construction' | 'general';
  isAutoGenerated?: boolean;
  color?: string;
}

interface FlatFeeItem {
  id: string;
  name: string;
  unitPrice: string;
  description?: string;
  scope?: string;
  category?: 'design' | 'construction' | 'general';
  isAutoGenerated?: boolean;
  color?: string;
  source?: string;
}

interface StructuralDesignData {
  // Wall Modifications
  frameNewWall: boolean;
  relocateWall: boolean;
  relocateWallLength: string;
  relocateWallHeight: string;
  removeNonLoadBearingWall: boolean;
  installBlocking: boolean;
  frameShowerNiche: boolean;
  addInsulation: boolean;
  changeDoorwayOpening: boolean;

  // Floors
  repairSisterFloorJoists: boolean;
  levelFloor: boolean;
  installNewPlywoodSubfloor: boolean;
  plywoodThickness: '1/2' | '5/8' | '3/4';
  replaceRottenSubfloor: boolean;
}

// Helper function to round to nearest 0.25
const roundToQuarter = (value: number): number => {
  return Math.round(value * 4) / 4;
};

// Helper function to clamp a value between min and max
const clamp = (value: number, min: number, max: number): number => {
  return Math.max(min, Math.min(max, value));
};

// Calculate relocate wall labor hours based on length
// Base: 12 hrs for 10ft baseline
// Formula: rawHours = 12 × (length / 10), clamped 4-24 hrs, rounded to nearest 0.25
const calculateRelocateWallHours = (lengthFt: number): number => {
  const baseHours = 12;
  const baseLength = 10;
  const rawHours = baseHours * (lengthFt / baseLength);
  const clampedHours = clamp(rawHours, 4, 24);
  return roundToQuarter(clampedHours);
};

export default function StructuralLaborSection() {
  const {
    getDesignData,
    getLaborItems,
    getFlatFeeItems,
    setLaborItems,
    setFlatFeeItems,
    isReloading,
  } = useEstimateWorkflowContext();

  const { hourlyRate: contractorHourlyRate } = useContractorContext();

  const designData = getDesignData('structural') as StructuralDesignData | null;
  const design = useMemo(
    () =>
      designData || {
        // Wall Modifications
        frameNewWall: false,
        relocateWall: false,
        relocateWallLength: '8',
        relocateWallHeight: '8',
        removeNonLoadBearingWall: false,
        installBlocking: false,
        frameShowerNiche: false,
        addInsulation: false,
        changeDoorwayOpening: false,

        // Floors
        repairSisterFloorJoists: false,
        levelFloor: false,
        installNewPlywoodSubfloor: false,
        plywoodThickness: '3/4' as const,
        replaceRottenSubfloor: false,
      },
    [designData]
  );

  // Calculate relocate wall hours dynamically based on length
  const relocateWallHours = useMemo(() => {
    const length = parseFloat(design.relocateWallLength) || 8;
    return calculateRelocateWallHours(length);
  }, [design.relocateWallLength]);

  const [localLaborItems, setLocalLaborItems] = useState<LaborItem[]>([]);
  const [localFlatFeeItems, setLocalFlatFeeItems] = useState<FlatFeeItem[]>([]);
  const [isWallWorkOpen, setIsWallWorkOpen] = useState(true);
  const [isFloorsOpen, setIsFloorsOpen] = useState(true);
  const [isCustomOpen, setIsCustomOpen] = useState(true);

  // Refs to track user actions
  const userActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Get current items from context
  const contextLaborItems = getLaborItems('structural');
  const contextFlatFeeItems = getFlatFeeItems('structural');

  // Note: studCount is calculated in materials section for material quantities

  // Auto-populate labor items based on selected tasks
  useEffect(() => {
    if (isReloading || userActionRef.current) {
      userActionRef.current = false;
      return;
    }

    // Create a key based on all design choices to detect changes
    const choicesKey = `${design.frameNewWall}-${design.relocateWall}-${design.relocateWallLength}-${design.relocateWallHeight}-${design.removeNonLoadBearingWall}-${design.installBlocking}-${design.frameShowerNiche}-${design.addInsulation}-${design.changeDoorwayOpening}-${design.repairSisterFloorJoists}-${design.levelFloor}-${design.installNewPlywoodSubfloor}-${design.plywoodThickness}-${design.replaceRottenSubfloor}`;

    // Skip if choices haven't changed
    if (processedChoicesRef.current === choicesKey) return;

    // Preserve custom items (non-auto-generated)
    const contextLabor = contextLaborItems || [];
    const customLaborItems = contextLabor.filter(
      (item) => item.isAutoGenerated === false
    );
    const customFlatFeeItems = (contextFlatFeeItems || []).filter(
      (item) => (item as FlatFeeItem).isAutoGenerated === false
    );

    const newLaborItems: LaborItem[] = [];
    const newFlatFeeItems: FlatFeeItem[] = [];

    // =========================================================================
    // WALL MODIFICATIONS
    // =========================================================================

    // A) Frame new wall(s) - 5 hrs @ rate
    if (design.frameNewWall) {
      newLaborItems.push({
        id: 'frame-new-wall',
        name: 'Frame new wall - 10ft section',
        hours: '5',
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // B) Relocate wall - Dynamic hours based on length
    // Base: 12 hrs for 10ft, scaled by (length/10), clamped 4-24, rounded to 0.25
    if (design.relocateWall) {
      newLaborItems.push({
        id: 'relocate-wall',
        name: `Relocate wall (${design.relocateWallLength || '8'}ft)`,
        hours: relocateWallHours.toFixed(2),
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // C) Remove non-load bearing wall - 4 hrs @ rate
    if (design.removeNonLoadBearingWall) {
      newLaborItems.push({
        id: 'remove-wall',
        name: 'Remove non-load bearing wall',
        hours: '4',
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // D) Install blocking for accessories - 1.5 hrs @ rate
    if (design.installBlocking) {
      newLaborItems.push({
        id: 'install-blocking',
        name: 'Install blocking for accessories',
        hours: '1.5',
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // E) Frame shower niche - 2 hrs @ rate
    if (design.frameShowerNiche) {
      newLaborItems.push({
        id: 'frame-shower-niche',
        name: 'Frame shower niche',
        hours: '2',
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // F) Add insulation - 1.5 hrs @ rate
    if (design.addInsulation) {
      newLaborItems.push({
        id: 'add-insulation',
        name: 'Add insulation',
        hours: '1.5',
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // G) Change doorway opening (non-load bearing) - 6 hrs @ $85/hr
    if (design.changeDoorwayOpening) {
      newLaborItems.push({
        id: 'change-doorway',
        name: 'Change doorway opening (non-load bearing)',
        hours: '6',
        rate: '85',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // =========================================================================
    // FLOORS
    // =========================================================================

    // A) Repair / sister floor joists - 5 hrs @ rate
    if (design.repairSisterFloorJoists) {
      newLaborItems.push({
        id: 'repair-floor-joists',
        name: 'Repair / sister floor joists',
        hours: '5',
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // B) Level floor (self-leveling) - 4 hrs @ rate
    if (design.levelFloor) {
      newLaborItems.push({
        id: 'level-floor',
        name: 'Level floor (self-leveling)',
        hours: '4',
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // C) Install new plywood subfloor - 4 hrs @ rate
    if (design.installNewPlywoodSubfloor) {
      newLaborItems.push({
        id: 'install-plywood',
        name: `Install new plywood subfloor (${design.plywoodThickness}")`,
        hours: '4',
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // D) Replace rotten subfloor - 7 hrs @ rate
    if (design.replaceRottenSubfloor) {
      newLaborItems.push({
        id: 'replace-subfloor',
        name: 'Replace rotten subfloor',
        hours: '7',
        rate: contractorHourlyRate.toString(),
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // Merge custom items with auto-generated items
    const mergedLaborItems = [...customLaborItems, ...newLaborItems];
    const mergedFlatFeeItems = [...customFlatFeeItems, ...newFlatFeeItems];

    // Always update when design changed - use context items for the check
    if (mergedLaborItems.length > 0 || contextLabor.length > 0) {
      setLaborItems('structural', mergedLaborItems);
      setLocalLaborItems(mergedLaborItems);
    }
    if (mergedFlatFeeItems.length > 0 || (contextFlatFeeItems || []).length > 0) {
      setFlatFeeItems('structural', mergedFlatFeeItems);
      setLocalFlatFeeItems(mergedFlatFeeItems);
    }

    // Update processed choices key
    processedChoicesRef.current = choicesKey;
  }, [
    design,
    contractorHourlyRate,
    relocateWallHours,
    isReloading,
    setLaborItems,
    setFlatFeeItems,
    contextLaborItems,
    contextFlatFeeItems,
  ]);

  // Sync with context changes
  useEffect(() => {
    if (!isReloading) {
      setLocalLaborItems(contextLaborItems);
      setLocalFlatFeeItems(contextFlatFeeItems);
    }
  }, [contextLaborItems, contextFlatFeeItems, isReloading]);

  // Handlers
  const handleAddLaborItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `labor-${Date.now()}`,
      name: '',
      hours: '1',
      rate: contractorHourlyRate.toString(),
      category: 'construction',
      isAutoGenerated: false,
      color: 'gray',
    };

    const updatedItems = [...localLaborItems, newItem];
    setLocalLaborItems(updatedItems);
    setLaborItems('structural', updatedItems);
    userActionRef.current = true;
  }, [localLaborItems, contractorHourlyRate, setLaborItems]);

  const handleUpdateLaborItem = useCallback(
    (id: string, field: keyof LaborItem, value: string) => {
      const updatedItems = localLaborItems.map((item) =>
        item.id === id ? { ...item, [field]: value } : item
      );
      setLocalLaborItems(updatedItems);
      setLaborItems('structural', updatedItems);
      userActionRef.current = true;
    },
    [localLaborItems, setLaborItems]
  );

  const handleDeleteLaborItem = useCallback(
    (id: string) => {
      const updatedItems = localLaborItems.filter((item) => item.id !== id);
      setLocalLaborItems(updatedItems);
      setLaborItems('structural', updatedItems);
      userActionRef.current = true;
    },
    [localLaborItems, setLaborItems]
  );

  // Flat fee handlers removed as they're not used in structural workflow

  // Calculate totals
  const laborTotal = useMemo(() => {
    return localLaborItems.reduce((total, item) => {
      const hours = parseFloat(item.hours) || 0;
      const rate = parseFloat(item.rate) || 0;
      return total + hours * rate;
    }, 0);
  }, [localLaborItems]);

  const flatFeeTotal = useMemo(() => {
    return localFlatFeeItems.reduce((total, item) => {
      const price = parseFloat(item.unitPrice) || 0;
      return total + price;
    }, 0);
  }, [localFlatFeeItems]);

  const grandTotal = laborTotal + flatFeeTotal;

  // Calculate total hours
  const totalHours = useMemo(() => {
    return localLaborItems.reduce(
      (sum, item) => sum + (parseFloat(item.hours) || 0),
      0
    );
  }, [localLaborItems]);

  // Group items by category
  const wallWorkItems = localLaborItems.filter((item) => item.color === 'blue');
  const floorsItems = localLaborItems.filter((item) => item.color === 'green');
  const customItems = localLaborItems.filter((item) => item.color === 'gray');

  // Calculate totals for each category
  const wallWorkHours = wallWorkItems.reduce(
    (sum, item) => sum + (parseFloat(item.hours) || 0),
    0
  );
  const wallWorkTotal = wallWorkItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0),
    0
  );

  const floorsHours = floorsItems.reduce(
    (sum, item) => sum + (parseFloat(item.hours) || 0),
    0
  );
  const floorsTotal = floorsItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0),
    0
  );

  const customHours = customItems.reduce(
    (sum, item) => sum + (parseFloat(item.hours) || 0),
    0
  );
  const customTotal = customItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0),
    0
  );

  const renderLaborItem = useCallback(
    (item: LaborItem) => (
      <div
        key={item.id}
        className='p-3 bg-white rounded-lg border border-slate-200 shadow-sm w-full'
      >
        <div className='flex items-center gap-2 mb-2 w-full'>
          <Input
            type='text'
            value={item.name}
            onChange={(e) =>
              handleUpdateLaborItem(item.id, 'name', e.target.value)
            }
            placeholder='Labor Task'
            className='border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full'
          />
          <Button
            onClick={() => handleDeleteLaborItem(item.id)}
            variant='ghost'
            size='sm'
            className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
          >
            <Trash2 size={16} />
          </Button>
        </div>
        <div className='grid grid-cols-2 gap-3'>
          <div className='w-full'>
            <label className='text-xs text-slate-500'>Hours</label>
            <Input
              type='number'
              value={item.hours}
              onChange={(e) =>
                handleUpdateLaborItem(item.id, 'hours', e.target.value)
              }
              placeholder='0'
              className='text-center w-full border-blue-300 focus:border-blue-500'
            />
          </div>
          <div className='w-full'>
            <label className='text-xs text-slate-500'>Rate ($/hr)</label>
            <Input
              type='number'
              value={item.rate}
              onChange={(e) =>
                handleUpdateLaborItem(item.id, 'rate', e.target.value)
              }
              placeholder='0'
              className='text-center w-full border-blue-300 focus:border-blue-500'
            />
          </div>
          <div className='col-span-2 w-full'>
            <label className='text-xs text-slate-500'>Total</label>
            <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
              $
              {(
                (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0)
              ).toFixed(2)}
            </div>
          </div>
        </div>
      </div>
    ),
    [handleUpdateLaborItem, handleDeleteLaborItem]
  );

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-baseline'>
        <h2 className='text-2xl font-bold text-slate-800'>Labor</h2>
        {totalHours > 0 && (
          <div className='flex items-center gap-2 text-sm text-slate-600'>
            <span className='font-semibold text-xl text-slate-800'>
              {totalHours.toFixed(1)} hrs
            </span>
          </div>
        )}
        <div className='flex items-center gap-2 text-sm text-slate-600'>
          <span className='font-semibold text-xl text-blue-600'>
            ${laborTotal.toFixed(2)}
          </span>
        </div>
      </div>

      <div className='space-y-4'>
        {/* Wall Work */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsWallWorkOpen(!isWallWorkOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isWallWorkOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Wall Work
                  </h3>
                </div>
                <span className='text-sm text-slate-500'>
                  {wallWorkHours.toFixed(1)} hrs
                </span>
                <p className='font-bold text-blue-600 text-sm'>
                  ${wallWorkTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isWallWorkOpen && (
              <>
                {wallWorkItems.length > 0 ? (
                  <div className='space-y-2'>
                    {wallWorkItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No wall work items added yet. Select tasks in Design section.
                  </p>
                )}
              </>
            )}
          </CardContent>
        </Card>

        {/* Floors */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsFloorsOpen(!isFloorsOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isFloorsOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Floors
                  </h3>
                </div>
                <span className='text-sm text-slate-500'>
                  {floorsHours.toFixed(1)} hrs
                </span>
                <p className='font-bold text-blue-600 text-sm'>
                  ${floorsTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isFloorsOpen && (
              <>
                {floorsItems.length > 0 ? (
                  <div className='space-y-2'>
                    {floorsItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No floor work items added yet. Select tasks in Design section.
                  </p>
                )}
              </>
            )}
          </CardContent>
        </Card>

        {/* Custom Items */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsCustomOpen(!isCustomOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isCustomOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Custom Items
                  </h3>
                </div>
                <span className='text-sm text-slate-500'>
                  {customHours.toFixed(1)} hrs
                </span>
                <p className='font-bold text-blue-600 text-sm'>
                  ${customTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isCustomOpen && (
              <>
                {customItems.length > 0 ? (
                  <div className='space-y-2'>
                    {customItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No custom items added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddLaborItem}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
