'use client';

import React, {
  useMemo,
  useCallback,
  useState,
  useEffect,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { SHOWER_BASE_LABOR_ITEMS } from '@/lib/constants';
import {
  LaborItem as ContextLaborItem,
  FlatFeeItem as ContextFlatFeeItem,
} from '@/types/estimate';

type LaborItem = ContextLaborItem & {
  source?: string;
  isAutoGenerated?: boolean;
};
type FlatFeeItem = ContextFlatFeeItem & {
  source?: string;
  isAutoGenerated?: boolean;
};

interface ShowerBaseDesignData {
  width: string;
  length: string;
  baseType: string;
  drainType: string;
  waterproofingSystem: string;
  subfloorRepair: boolean;
  joistModification: boolean;
  clientSuppliesBase: string;
  [key: string]: unknown;
}

export default function ShowerBaseLaborSection() {
  const {
    getDesignData,
    getLaborItems,
    getFlatFeeItems,
    setLaborItems,
    isReloading,
  } = useEstimateWorkflowContext();

  // Get design data from context
  const designData = getDesignData('showerBase') as ShowerBaseDesignData | null;
  const design = useMemo(
    () =>
      designData || {
        width: '',
        length: '',
        baseType: 'Select base type',
        drainType: 'regular',
        waterproofingSystem: 'none',
        subfloorRepair: false,
        joistModification: false,
        clientSuppliesBase: 'No',
      },
    [designData]
  );

  // Get contractor hourly rate (default to 75.00 as per business logic)
  const contractorHourlyRate = 75.0;

  // Get context data
  const contextLaborItems = getLaborItems('showerBase');
  const contextFlatFeeItems = getFlatFeeItems('showerBase');

  // Local state for immediate UI updates
  const [localLaborItems, setLocalLaborItems] = useState<LaborItem[]>([]);
  const [localFlatFeeItems, setLocalFlatFeeItems] = useState<FlatFeeItem[]>([]);
  const [isDesignOpen, setIsDesignOpen] = useState(true);
  const [isConstructionOpen, setIsConstructionOpen] = useState(true);

  // Refs to track user actions and prevent auto-generation interference
  const isUserActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Sync local state with context
  useEffect(() => {
    setLocalLaborItems(contextLaborItems);
    setLocalFlatFeeItems(contextFlatFeeItems);
  }, [contextLaborItems, contextFlatFeeItems]);

  // Generate labor items based on design choices
  const generateLaborItems = useCallback(() => {
    const laborItems: LaborItem[] = [];
    const flatFeeItems: FlatFeeItem[] = [];

    const baseType = design.baseType;
    const drainType = design.drainType;
    const waterproofingSystem = design.waterproofingSystem;
    const subfloorRepair = design.subfloorRepair;
    const joistModification = design.joistModification;
    const clientSuppliesBase = design.clientSuppliesBase;

    const laborItemsMap = SHOWER_BASE_LABOR_ITEMS(contractorHourlyRate);

    // Base Type Logic
    if (baseType === 'Tub') {
      if (clientSuppliesBase === 'No') {
        laborItems.push({
          ...laborItemsMap.installTub,
          id: `lab-base-tub-${Date.now()}`,
        });
      }
    } else if (baseType === 'Acrylic Base') {
      if (clientSuppliesBase === 'No') {
        laborItems.push({
          ...laborItemsMap.installAcrylicBase,
          id: `lab-base-acrylic-${Date.now()}`,
        });
      }
    } else if (baseType === 'Tiled Base') {
      // Design Labor for Tiled Base
      laborItems.push({
        ...laborItemsMap.tileBase,
        id: `lab-base-tile-${Date.now()}`,
      });

      // Curb Logic
      if (drainType === 'curb') {
        laborItems.push({
          ...laborItemsMap.buildCurb,
          id: `lab-base-curb-${Date.now()}`,
        });
      } else if (drainType === 'curbless') {
        laborItems.push({
          ...laborItemsMap.buildCurblessEntry,
          id: `lab-base-curbless-${Date.now()}`,
        });
      }

      // Drain Installation
      if (drainType === 'regular') {
        laborItems.push({
          ...laborItemsMap.installRegularDrain,
          id: `lab-base-drain-reg-${Date.now()}`,
        });
      } else if (drainType === 'linear') {
        laborItems.push({
          ...laborItemsMap.installLinearDrain,
          id: `lab-base-drain-linear-${Date.now()}`,
        });
      }

      // Waterproofing System
      if (waterproofingSystem === 'kerdi') {
        laborItems.push({
          ...laborItemsMap.installKerdiSystem,
          id: `lab-base-kerdi-${Date.now()}`,
        });
      } else if (waterproofingSystem === 'liquid') {
        laborItems.push({
          ...laborItemsMap.installLiquidMembrane,
          id: `lab-base-liquid-${Date.now()}`,
        });
      } else if (waterproofingSystem === 'kerdi-board') {
        laborItems.push({
          ...laborItemsMap.installKerdiBoard,
          id: `lab-base-kerdi-board-${Date.now()}`,
        });
      }
    }

    // General Construction
    if (subfloorRepair) {
      laborItems.push({
        ...laborItemsMap.subfloorRepair,
        id: `lab-base-subfloor-${Date.now()}`,
      });
    }

    if (joistModification) {
      laborItems.push({
        ...laborItemsMap.joistModification,
        id: `lab-base-joist-${Date.now()}`,
      });
    }

    return { laborItems, flatFeeItems };
  }, [design, contractorHourlyRate]);

  // Auto-generate labor items when design changes
  useEffect(() => {
    if (isUserActionRef.current || isReloading) return;

    const choicesKey = `${design.baseType}-${design.drainType}-${design.waterproofingSystem}-${design.subfloorRepair}-${design.joistModification}-${design.clientSuppliesBase}`;

    if (processedChoicesRef.current === choicesKey) return;

    // If we have data from context (Supabase), never override it with defaults
    if (contextLaborItems && contextLaborItems.length > 0) {
      return;
    }

    // Check if there are existing auto-generated items (preserve user modifications)
    const currentLabor = localLaborItems || [];
    const existingAutoItems = currentLabor.filter(
      (item) => item.source === 'auto'
    );
    if (existingAutoItems.length > 0) return;

    // Only auto-generate if no items exist
    const { laborItems } = generateLaborItems();

    if (laborItems.length > 0) {
      setLaborItems('showerBase', laborItems);
    }

    processedChoicesRef.current = choicesKey;
  }, [
    design,
    generateLaborItems,
    setLaborItems,
    contextLaborItems,
    localLaborItems,
    isReloading,
  ]);

  // Handle adding new labor items

  const handleAddDesignLaborItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `labor-design-${Date.now()}-${Math.random()
        .toString(36)
        .substr(2, 9)}`,
      name: 'Custom Design Labor',
      hours: '1',
      rate: contractorHourlyRate.toString(),
      scope: 'design',
      source: 'custom',
      isAutoGenerated: false,
    };

    isUserActionRef.current = true;
    setLocalLaborItems((prev) => [...prev, newItem]);

    setTimeout(() => {
      setLaborItems('showerBase', [...localLaborItems, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localLaborItems, setLaborItems, contractorHourlyRate]);

  const handleAddConstructionLaborItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `labor-construction-${Date.now()}-${Math.random()
        .toString(36)
        .substr(2, 9)}`,
      name: 'Custom Construction Labor',
      hours: '1',
      rate: contractorHourlyRate.toString(),
      scope: 'construction',
      source: 'custom',
      isAutoGenerated: false,
    };

    isUserActionRef.current = true;
    setLocalLaborItems((prev) => [...prev, newItem]);

    setTimeout(() => {
      setLaborItems('showerBase', [...localLaborItems, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localLaborItems, setLaborItems, contractorHourlyRate]);

  // Handle labor item changes
  const handleLaborItemChange = useCallback(
    (id: string, field: keyof LaborItem, value: string) => {
      isUserActionRef.current = true;

      setLocalLaborItems((prev) =>
        prev.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        )
      );

      setTimeout(() => {
        const updatedItems = localLaborItems.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        );
        setLaborItems('showerBase', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, setLaborItems]
  );

  // Handle deleting labor item
  const handleDeleteLaborItem = useCallback(
    (id: string) => {
      isUserActionRef.current = true;

      setLocalLaborItems((prev) => prev.filter((item) => item.id !== id));

      setTimeout(() => {
        const updatedItems = localLaborItems.filter((item) => item.id !== id);
        setLaborItems('showerBase', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, setLaborItems]
  );

  // Handle adding new flat fee item
  const handleAddFlatFeeItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `flat-fee-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      name: '',
      hours: '0',
      rate: '0',
      scope: 'construction',
      source: 'custom',
      isAutoGenerated: false,
    };

    isUserActionRef.current = true;
    setLocalFlatFeeItems((prev) => [
      ...prev,
      newItem as unknown as FlatFeeItem,
    ]);

    setTimeout(() => {
      setLaborItems('showerBase', [...localLaborItems, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localLaborItems, setLaborItems]);

  // Handle flat fee item changes
  const handleFlatFeeItemChange = useCallback(
    (id: string, field: keyof FlatFeeItem, value: string) => {
      isUserActionRef.current = true;

      setLocalFlatFeeItems((prev) =>
        prev.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        )
      );

      setTimeout(() => {
        const updatedItems = localLaborItems.map((item) => {
          if (item.id === id) {
            const flatFeeItem = localFlatFeeItems.find((f) => f.id === id);
            if (flatFeeItem) {
              return {
                ...item,
                name: flatFeeItem.name,
                rate: flatFeeItem.unitPrice,
              };
            }
          }
          return item;
        });
        setLaborItems('showerBase', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, localFlatFeeItems, setLaborItems]
  );

  // Handle deleting flat fee item
  const handleDeleteFlatFeeItem = useCallback(
    (id: string) => {
      isUserActionRef.current = true;

      setLocalFlatFeeItems((prev) => prev.filter((item) => item.id !== id));

      setTimeout(() => {
        const updatedItems = localLaborItems.filter((item) => item.id !== id);
        setLaborItems('showerBase', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, setLaborItems]
  );

  const laborItems = localLaborItems;
  const flatFeeItems = localFlatFeeItems;

  const renderLaborItem = useCallback(
    (item: LaborItem) => {
      return (
        <div
          key={item.id}
          className={`p-3 rounded-lg border shadow-sm w-full ${
            item.isAutoGenerated
              ? 'bg-blue-50 border-blue-200'
              : 'bg-white border-slate-200'
          }`}
        >
          <div className='flex items-center gap-2 mb-2 w-full'>
            <Input
              type='text'
              value={item.name}
              onChange={(e) =>
                handleLaborItemChange(item.id, 'name', e.target.value)
              }
              placeholder='Labor Task'
              className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full`}
            />
            <Button
              onClick={() => handleDeleteLaborItem(item.id)}
              variant='ghost'
              size='sm'
              className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
            >
              <Trash2 size={16} />
            </Button>
          </div>
          <div className='grid grid-cols-2 gap-3'>
            <div className='w-full'>
              <label className='text-xs text-slate-500'>Hours</label>
              <Input
                type='number'
                value={item.hours}
                onChange={(e) =>
                  handleLaborItemChange(item.id, 'hours', e.target.value)
                }
                placeholder='0'
                className='text-center w-full border-blue-300 focus:border-blue-500'
              />
            </div>
            <div className='w-full'>
              <label className='text-xs text-slate-500'>Rate ($/hr)</label>
              <Input
                type='number'
                value={item.rate}
                onChange={(e) =>
                  handleLaborItemChange(item.id, 'rate', e.target.value)
                }
                placeholder='0'
                className='text-center w-full border-blue-300 focus:border-blue-500'
              />
            </div>
            <div className='col-span-2 w-full'>
              <label className='text-xs text-slate-500'>Total</label>
              <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
                $
                {(
                  (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0)
                ).toFixed(2)}
              </div>
            </div>
          </div>
        </div>
      );
    },
    [handleLaborItemChange, handleDeleteLaborItem]
  );

  const renderFlatFeeItem = useCallback(
    (item: FlatFeeItem) => {
      return (
        <div
          key={item.id}
          className={`p-3 rounded-lg border shadow-sm w-full ${
            item.isAutoGenerated
              ? 'bg-blue-50 border-blue-200'
              : 'bg-white border-slate-200'
          }`}
        >
          <div className='flex items-center gap-2 mb-2 w-full'>
            <Input
              type='text'
              value={item.name}
              onChange={(e) =>
                handleFlatFeeItemChange(item.id, 'name', e.target.value)
              }
              placeholder='Flat Fee Task'
              className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full`}
            />
            <Button
              onClick={() => handleDeleteFlatFeeItem(item.id)}
              variant='ghost'
              size='sm'
              className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
            >
              <Trash2 size={16} />
            </Button>
          </div>
          <div className='w-full'>
            <label className='text-xs text-slate-500'>Total ($)</label>
            <Input
              type='number'
              value={item.unitPrice}
              onChange={(e) =>
                handleFlatFeeItemChange(item.id, 'unitPrice', e.target.value)
              }
              placeholder='0.00'
              className='text-center w-full border-b-2 border-t-0 border-l-0 border-r-0 border-blue-500 focus:border-blue-500'
            />
          </div>
        </div>
      );
    },
    [handleFlatFeeItemChange, handleDeleteFlatFeeItem]
  );

  // Separate labor items by scope
  const designLaborItems = useMemo(() => {
    return laborItems.filter((item) => item.scope === 'design');
  }, [laborItems]);

  const constructionLaborItems = useMemo(() => {
    return laborItems.filter((item) => item.scope === 'construction');
  }, [laborItems]);

  // Calculate totals for design labor
  const designTotalHours = designLaborItems.reduce(
    (sum, item) => sum + (parseFloat(item.hours) || 0),
    0
  );
  const designLaborTotal = designLaborItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0),
    0
  );

  // Calculate totals for construction labor
  const constructionTotalHours = constructionLaborItems.reduce(
    (sum, item) => sum + (parseFloat(item.hours) || 0),
    0
  );
  const constructionLaborTotal = constructionLaborItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0),
    0
  );

  const flatFeeTotal = flatFeeItems.reduce(
    (sum, item) => sum + (parseFloat(item.unitPrice) || 0),
    0
  );

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-baseline'>
        <h2 className='text-2xl font-bold text-slate-800'>Labor</h2>
      </div>

      <div className='space-y-4'>
        {/* Design Labor Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsDesignOpen(!isDesignOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isDesignOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Design Labor
                  </h3>
                </div>
                <span className='text-sm text-slate-500'>
                  {designTotalHours.toFixed(1)} hrs
                </span>
                <p className='font-bold text-blue-600 text-sm'>
                  ${designLaborTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isDesignOpen && (
              <>
                {designLaborItems.length > 0 ? (
                  <div className='space-y-2'>
                    {designLaborItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No design labor items added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddDesignLaborItem}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        {/* Construction Labor Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsConstructionOpen(!isConstructionOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isConstructionOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Construction Labor
                  </h3>
                </div>
                <span className='text-sm text-slate-500'>
                  {constructionTotalHours.toFixed(1)} hrs
                </span>
                <p className='font-bold text-blue-600 text-sm'>
                  ${constructionLaborTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isConstructionOpen && (
              <>
                {constructionLaborItems.length > 0 ? (
                  <div className='space-y-2'>
                    {constructionLaborItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No construction labor items added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddConstructionLaborItem}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        {/* Flat Fee Section */}
        {flatFeeItems.length > 0 && (
          <Card>
            <CardContent className='p-3 space-y-3'>
              <div className='flex justify-between items-center'>
                <h3 className='text-lg font-semibold text-slate-700'>
                  Flat Fee Items
                </h3>
                <p className='font-bold text-blue-600 text-sm'>
                  ${flatFeeTotal.toFixed(2)}
                </p>
              </div>
              <div className='space-y-2'>
                {flatFeeItems.map(renderFlatFeeItem)}
              </div>
              <div className='flex justify-center'>
                <Button
                  onClick={handleAddFlatFeeItem}
                  variant='default'
                  className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                >
                  <Plus size={16} />
                  Add Item
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
