'use client';

import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
} from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent } from '@/components/ui/card';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { TRADE_MATERIALS } from '@/lib/constants';
import { MaterialItem } from '@/types/estimate';
import { Trash2, Plus } from 'lucide-react';

interface TradeDesignData {
  selectedTrades: string[];
  projectChoices: Record<string, Array<{ id: string; quantity: number }>>;
  [key: string]: unknown;
}

export default function TradeMaterialsSection() {
  const { getDesignData, getMaterialItems, setMaterialItems, isReloading } =
    useEstimateWorkflowContext();

  const designData = getDesignData('trade') as TradeDesignData | null;
  const design = useMemo(
    () =>
      designData || {
        selectedTrades: [],
        projectChoices: {},
      },
    [designData]
  );

  const [localMaterialItems, setLocalMaterialItems] = useState<MaterialItem[]>(
    []
  );
  const [newItemName, setNewItemName] = useState('');
  const [newItemQuantity, setNewItemQuantity] = useState('');
  const [newItemUnit, setNewItemUnit] = useState('');
  const [newItemPrice, setNewItemPrice] = useState('');

  // Refs to track user actions
  const userActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Get current items from context
  const contextMaterialItems = getMaterialItems('trade');

  // Effect to handle design changes and context sync
  useEffect(() => {
    console.log('🔧 TradeMaterialsSection useEffect triggered:', {
      isReloading,
      contextMaterialItemsLength: contextMaterialItems.length,
      userActionRef: userActionRef.current,
      designSelectedTrades: design.selectedTrades,
      designProjectChoices: design.projectChoices,
    });

    if (isReloading) {
      console.log(
        '🔄 TradeMaterialsSection: Reloading, setting context items:',
        contextMaterialItems
      );
      setLocalMaterialItems(contextMaterialItems);
      return;
    }

    // Always prioritize context data when available
    if (contextMaterialItems.length > 0) {
      console.log(
        '📥 TradeMaterialsSection: Context data available, setting local items:',
        contextMaterialItems
      );
      setLocalMaterialItems(contextMaterialItems);
      return;
    }

    // Only auto-generate if there's no context data and no user action
    if (!userActionRef.current) {
      // Check if design choices have changed
      const choicesString = JSON.stringify({
        selectedTrades: design.selectedTrades,
        projectChoices: design.projectChoices,
      });

      console.log('🔍 TradeMaterialsSection: Checking choices change:', {
        choicesString,
        processedChoices: processedChoicesRef.current,
        hasChanged: choicesString !== processedChoicesRef.current,
      });

      if (choicesString !== processedChoicesRef.current) {
        processedChoicesRef.current = choicesString;
        console.log(
          '⚡ TradeMaterialsSection: Choices changed, generating new items'
        );

        // Generate material items inline to avoid dependency issues
        const materialItems: MaterialItem[] = [];
        design.selectedTrades.forEach((tradeId) => {
          const materials =
            TRADE_MATERIALS[tradeId as keyof typeof TRADE_MATERIALS] || [];
          const selectedTasks = design.projectChoices[tradeId] || [];

          console.log(
            `🔨 TradeMaterialsSection: Processing trade ${tradeId}:`,
            {
              materialsCount: materials.length,
              selectedTasksCount: selectedTasks.length,
            }
          );

          // Only add materials if there are selected tasks for this trade
          if (selectedTasks.length > 0) {
            materials.forEach((material) => {
              const materialItem = {
                id: material.id,
                name: material.name,
                quantity: material.quantity,
                unit: material.unit,
                price: material.price,
                scope: 'construction',
                category: 'construction' as const,
                isAutoGenerated: true,
              };

              materialItems.push(materialItem);
            });
          }
        });

        console.log(
          '✅ TradeMaterialsSection: Generated material items:',
          materialItems
        );
        setLocalMaterialItems(materialItems);
        console.log(
          '💾 TradeMaterialsSection: Calling setMaterialItems with:',
          materialItems
        );
        setMaterialItems('trade', materialItems);
      }
    }
  }, [
    design.selectedTrades,
    design.projectChoices,
    setMaterialItems,
    isReloading,
    contextMaterialItems,
  ]);

  const handleItemChange = useCallback(
    (
      id: string,
      field: 'name' | 'quantity' | 'unit' | 'price',
      value: string
    ) => {
      console.log('✏️ TradeMaterialsSection: handleItemChange called:', {
        id,
        field,
        value,
        currentItems: localMaterialItems,
      });

      userActionRef.current = true;
      const updatedItems = localMaterialItems.map((item) => {
        if (item.id === id) {
          const updatedItem = { ...item, [field]: value };
          console.log('🔄 TradeMaterialsSection: Updated item:', updatedItem);
          return updatedItem;
        }
        return item;
      });

      console.log(
        '📝 TradeMaterialsSection: Setting local items:',
        updatedItems
      );
      setLocalMaterialItems(updatedItems);

      console.log(
        '💾 TradeMaterialsSection: Calling setMaterialItems with updated items:',
        updatedItems
      );
      setMaterialItems('trade', updatedItems);
    },
    [localMaterialItems, setMaterialItems]
  );

  const handleDeleteItem = useCallback(
    (id: string) => {
      console.log('🗑️ TradeMaterialsSection: handleDeleteItem called:', {
        id,
        currentItems: localMaterialItems,
      });

      userActionRef.current = true;
      const updatedItems = localMaterialItems.filter((item) => item.id !== id);

      console.log(
        '📝 TradeMaterialsSection: Setting local items after delete:',
        updatedItems
      );
      setLocalMaterialItems(updatedItems);

      console.log(
        '💾 TradeMaterialsSection: Calling setMaterialItems after delete:',
        updatedItems
      );
      setMaterialItems('trade', updatedItems);
    },
    [localMaterialItems, setMaterialItems]
  );

  const handleAddCustomItem = useCallback(() => {
    console.log('➕ TradeMaterialsSection: handleAddCustomItem called:', {
      newItemName,
      newItemQuantity,
      newItemUnit,
      newItemPrice,
      currentItems: localMaterialItems,
    });

    if (!newItemName.trim() || !newItemQuantity || !newItemPrice) {
      console.log(
        '❌ TradeMaterialsSection: Missing required fields, skipping add'
      );
      return;
    }

    const newItem: MaterialItem = {
      id: `custom-${Date.now()}`,
      name: newItemName,
      quantity: newItemQuantity,
      unit: newItemUnit || 'each',
      price: newItemPrice,
      scope: 'construction',
      category: 'construction' as const,
      isAutoGenerated: false,
    };

    console.log('🆕 TradeMaterialsSection: Created new custom item:', newItem);

    const updatedItems = [...localMaterialItems, newItem];
    console.log(
      '📝 TradeMaterialsSection: Setting local items with new custom item:',
      updatedItems
    );
    setLocalMaterialItems(updatedItems);

    console.log(
      '💾 TradeMaterialsSection: Calling setMaterialItems with custom item:',
      updatedItems
    );
    setMaterialItems('trade', updatedItems);

    // Reset form
    setNewItemName('');
    setNewItemQuantity('');
    setNewItemUnit('');
    setNewItemPrice('');
    console.log('🔄 TradeMaterialsSection: Form reset');
  }, [
    newItemName,
    newItemQuantity,
    newItemUnit,
    newItemPrice,
    localMaterialItems,
    setMaterialItems,
  ]);

  const totalMaterialCost = useMemo(() => {
    return localMaterialItems.reduce((sum, item) => {
      const quantity = parseFloat(item.quantity) || 0;
      const price = parseFloat(item.price) || 0;
      return sum + quantity * price;
    }, 0);
  }, [localMaterialItems]);

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-center'>
        <h2 className='text-2xl font-bold text-slate-800'>
          Materials & Supplies
        </h2>
        <div className='text-right'>
          <p className='font-bold text-blue-600 text-lg'>
            ${totalMaterialCost.toFixed(2)}
          </p>
        </div>
      </div>
      <Card>
        <CardContent className='p-3 space-y-3'>
          {localMaterialItems.length > 0 ? (
            localMaterialItems.map((item) => (
              <div
                key={item.id}
                className={`p-3 bg-white rounded-lg border ${
                  item.isAutoGenerated
                    ? 'bg-blue-50 border-blue-200'
                    : 'border-slate-300'
                }`}
              >
                <div className='flex items-center gap-2 mb-2'>
                  <Input
                    type='text'
                    value={item.name}
                    onChange={(e) =>
                      handleItemChange(item.id, 'name', e.target.value)
                    }
                    placeholder='Supply Name'
                    className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none`}
                  />
                  <Button
                    onClick={() => handleDeleteItem(item.id)}
                    variant='ghost'
                    size='sm'
                    className='text-red-500 hover:text-red-700 p-1 h-auto'
                  >
                    <Trash2 size={16} />
                  </Button>
                </div>
                <div className='grid grid-cols-3 gap-3'>
                  <div>
                    <label className='text-xs text-slate-500'>Quantity</label>
                    <Input
                      type='number'
                      value={item.quantity}
                      onChange={(e) =>
                        handleItemChange(item.id, 'quantity', e.target.value)
                      }
                      placeholder='0'
                      className={`text-center border-blue-300 focus:border-blue-500`}
                    />
                  </div>
                  <div>
                    <label className='text-xs text-slate-500'>Unit</label>
                    <Input
                      type='text'
                      value={item.unit}
                      onChange={(e) =>
                        handleItemChange(item.id, 'unit', e.target.value)
                      }
                      placeholder='sq/ft'
                      className={`text-center border-blue-300 focus:border-blue-500`}
                    />
                  </div>
                  <div>
                    <label className='text-xs text-slate-500'>
                      Price/Unit ($)
                    </label>
                    <Input
                      type='number'
                      value={item.price}
                      onChange={(e) =>
                        handleItemChange(item.id, 'price', e.target.value)
                      }
                      placeholder='0.00'
                      className={`text-center border-blue-300 focus:border-blue-500`}
                    />
                  </div>
                </div>
                <div className='mt-2'>
                  <label className='text-xs text-slate-500'>Total</label>
                  <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
                    $
                    {(
                      (parseFloat(item.quantity) || 0) *
                      (parseFloat(item.price) || 0)
                    ).toFixed(2)}
                  </div>
                </div>
              </div>
            ))
          ) : (
            <p className='text-sm text-slate-500 text-center py-4'>
              No materials added yet.
            </p>
          )}
          <div className='flex justify-center'>
            <Button
              onClick={handleAddCustomItem}
              variant='default'
              className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
            >
              <Plus size={16} />
              Add Item
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
