'use client';

import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';
import {
  TradeDesignData,
  DEFAULT_TRADE_DESIGN,
} from '../design/TradeSection';

interface MaterialItem {
  id: string;
  name: string;
  quantity: string;
  price: string;
  unit: string;
  scope?: string;
  category?: 'design' | 'construction' | 'general';
  isAutoGenerated?: boolean;
  color?: string;
  source?: string;
}

export default function TradeMaterialsSection() {
  const { getDesignData, getMaterialItems, setMaterialItems, isReloading } =
    useEstimateWorkflowContext();

  const designData = getDesignData('trade') as TradeDesignData | null;
  const design = useMemo(
    () => ({
      ...DEFAULT_TRADE_DESIGN,
      ...designData,
      pricingModes: {
        ...DEFAULT_TRADE_DESIGN.pricingModes,
        ...(designData?.pricingModes || {}),
      },
      tradeRates: {
        ...DEFAULT_TRADE_DESIGN.tradeRates,
        ...(designData?.tradeRates || {}),
      },
    }),
    [designData]
  );

  const [localMaterialItems, setLocalMaterialItems] = useState<MaterialItem[]>(
    []
  );
  const [isPlumbingOpen, setIsPlumbingOpen] = useState(true);
  const [isElectricalOpen, setIsElectricalOpen] = useState(true);
  const [isCustomOpen, setIsCustomOpen] = useState(true);
  const userActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Get current items from context
  const contextMaterialItems = getMaterialItems('trade');

  // Auto-populate material items based on selected tasks
  useEffect(() => {
    if (isReloading || userActionRef.current) {
      userActionRef.current = false;
      return;
    }

    // Create a key based on all design choices to detect changes
    const choicesKey = JSON.stringify(design);

    // Skip if choices haven't changed
    if (processedChoicesRef.current === choicesKey) return;

    // Preserve custom items (non-auto-generated)
    const contextMaterials = contextMaterialItems || [];
    const customMaterialItems = contextMaterials.filter(
      (item) => item.isAutoGenerated === false
    );

    const newMaterialItems: MaterialItem[] = [];

    // =========================================================================
    // PLUMBING - ROUGH-IN MATERIALS
    // =========================================================================

    if (design.moveToiletDrainSupply) {
      newMaterialItems.push(
        {
          id: 'toilet-drain-pipe',
          name: '3" PVC drain pipe',
          quantity: '10',
          price: '4.50',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'toilet-supply-line',
          name: 'Toilet supply line',
          quantity: '1',
          price: '15.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'toilet-drain-fittings',
          name: 'PVC fittings (elbows, couplings)',
          quantity: '6',
          price: '5.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.addVanityPlumbingRoughIn) {
      newMaterialItems.push(
        {
          id: 'vanity-supply-pipes',
          name: '1/2" copper pipes',
          quantity: '20',
          price: '2.50',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'vanity-drain-pipe',
          name: '1-1/2" PVC drain pipe',
          quantity: '8',
          price: '3.00',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'vanity-shutoff-valves',
          name: 'Shut-off valves',
          quantity: '2',
          price: '18.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.installNewShowerValve) {
      newMaterialItems.push(
        {
          id: 'shower-valve-body',
          name: 'Shower valve body (rough-in)',
          quantity: '1',
          price: '85.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'shower-valve-pipes',
          name: '1/2" copper pipes',
          quantity: '15',
          price: '2.50',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.roughInDiverter) {
      newMaterialItems.push(
        {
          id: 'diverter-valve',
          name: 'Diverter valve body',
          quantity: '1',
          price: '65.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'diverter-pipes',
          name: '1/2" copper pipes',
          quantity: '10',
          price: '2.50',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.addFreestandingTubRoughIn) {
      newMaterialItems.push(
        {
          id: 'tub-supply-pipes',
          name: '1/2" copper pipes',
          quantity: '25',
          price: '2.50',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'tub-drain-assembly',
          name: 'Tub drain rough-in assembly',
          quantity: '1',
          price: '65.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'tub-shutoff-valves',
          name: 'Shut-off valves',
          quantity: '2',
          price: '18.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.relocateFixtureDrain) {
      newMaterialItems.push(
        {
          id: 'relocate-drain-pipe',
          name: '2" PVC drain pipe',
          quantity: '12',
          price: '3.50',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'relocate-drain-fittings',
          name: 'PVC fittings (elbows, wye, couplings)',
          quantity: '8',
          price: '6.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.addBidetPlumbingRoughIn) {
      newMaterialItems.push(
        {
          id: 'bidet-supply-pipe',
          name: '1/2" copper pipe',
          quantity: '10',
          price: '2.50',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'bidet-shutoff-valve',
          name: 'Shut-off valve',
          quantity: '1',
          price: '18.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'bidet-tee-fitting',
          name: 'T-fitting for supply',
          quantity: '1',
          price: '8.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    // =========================================================================
    // PLUMBING - FIXTURE INSTALLATION MATERIALS
    // =========================================================================

    // Vanity cabinet materials (based on type)
    if (design.vanityInstallationType === 'single') {
      newMaterialItems.push({
        id: 'vanity-cabinet-single',
        name: 'Vanity cabinet installation hardware',
        quantity: '1',
        price: '25.00',
        unit: 'set',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.vanityInstallationType === 'double') {
      newMaterialItems.push({
        id: 'vanity-cabinet-double',
        name: 'Vanity cabinet installation hardware (double)',
        quantity: '1',
        price: '35.00',
        unit: 'set',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Vanity sink drain connection materials
    if (design.vanityInstallationType === 'single' && design.connectSinkDrains) {
      newMaterialItems.push(
        {
          id: 'single-sink-p-trap',
          name: 'P-trap assembly',
          quantity: '1',
          price: '25.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'single-sink-tailpiece',
          name: 'Sink tailpiece',
          quantity: '1',
          price: '12.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.vanityInstallationType === 'double' && design.connectSinkDrains) {
      newMaterialItems.push(
        {
          id: 'double-sink-p-trap',
          name: 'P-trap assembly',
          quantity: '2',
          price: '25.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'double-sink-tailpiece',
          name: 'Sink tailpiece',
          quantity: '2',
          price: '12.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'double-sink-tee',
          name: 'Drain tee connector',
          quantity: '1',
          price: '15.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.installVanityFaucetSupplyLines) {
      const qty = design.vanityInstallationType === 'double' ? 2 : 1;
      newMaterialItems.push({
        id: 'vanity-supply-lines',
        name: 'Braided supply lines (hot & cold pair)',
        quantity: qty.toString(),
        price: '24.00',
        unit: 'pair',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Shower Trim materials based on option
    if (design.showerTrimOption === 'valve_head') {
      newMaterialItems.push(
        {
          id: 'shower-valve-trim',
          name: 'Valve trim plate & handle',
          quantity: '1',
          price: '45.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'shower-head',
          name: 'Shower head',
          quantity: '1',
          price: '35.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.showerTrimOption === 'valve_head_spout') {
      newMaterialItems.push(
        {
          id: 'shower-valve-trim',
          name: 'Valve trim plate & handle',
          quantity: '1',
          price: '45.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'shower-head',
          name: 'Shower head',
          quantity: '1',
          price: '35.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'tub-spout-combo',
          name: 'Tub spout',
          quantity: '1',
          price: '28.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    // Shower Trim add-ons
    if (design.showerTrimOption !== 'none' && design.showerTrimHandheld) {
      newMaterialItems.push({
        id: 'handheld-shower',
        name: 'Handheld shower with hose & bracket',
        quantity: '1',
        price: '55.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.showerTrimOption !== 'none' && design.showerTrimRainhead) {
      newMaterialItems.push({
        id: 'rainhead-shower',
        name: 'Rainhead shower head',
        quantity: '1',
        price: '85.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Separate tub spout (only when valve_head and installTubSpout is true)
    if (design.showerTrimOption === 'valve_head' && design.installTubSpout) {
      newMaterialItems.push({
        id: 'tub-spout-separate',
        name: 'Tub spout',
        quantity: '1',
        price: '28.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installToilet) {
      newMaterialItems.push(
        {
          id: 'toilet-wax-ring',
          name: 'Wax ring with flange',
          quantity: '1',
          price: '12.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'toilet-bolts',
          name: 'Toilet bolt set',
          quantity: '1',
          price: '8.00',
          unit: 'set',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        },
        {
          id: 'toilet-supply-connector',
          name: 'Toilet supply connector',
          quantity: '1',
          price: '12.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'blue',
        }
      );
    }

    if (design.installBidetSeat) {
      newMaterialItems.push({
        id: 'bidet-supply-connector',
        name: 'Bidet T-adapter & supply hose',
        quantity: '1',
        price: '25.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installFreestandingTubFaucet) {
      newMaterialItems.push({
        id: 'tub-drain-kit',
        name: 'Tub drain kit (pop-up or toe-tap)',
        quantity: '1',
        price: '45.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // =========================================================================
    // ELECTRICAL - ROUGH-IN MATERIALS
    // =========================================================================

    if (design.heatedFloorThermostatPower) {
      newMaterialItems.push(
        {
          id: 'heated-floor-wire',
          name: '12/2 NM-B wire',
          quantity: '25',
          price: '1.80',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'thermostat-box',
          name: 'Single-gang electrical box',
          quantity: '1',
          price: '3.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        }
      );
    }

    if (design.potLightQuantity > 0) {
      newMaterialItems.push(
        {
          id: 'pot-light-wire',
          name: '14/2 NM-B wire',
          quantity: (30 * design.potLightQuantity).toString(),
          price: '1.50',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'pot-light-housing',
          name: 'Canless LED recessed light',
          quantity: design.potLightQuantity.toString(),
          price: '35.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        }
      );
    }

    if (design.gfciOutletQuantity > 0) {
      newMaterialItems.push(
        {
          id: 'gfci-wire',
          name: '12/2 NM-B wire',
          quantity: (30 * design.gfciOutletQuantity).toString(),
          price: '1.80',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'gfci-outlet-box',
          name: 'Single-gang electrical box',
          quantity: design.gfciOutletQuantity.toString(),
          price: '3.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'gfci-outlet',
          name: 'GFCI outlet',
          quantity: design.gfciOutletQuantity.toString(),
          price: '22.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        }
      );
    }

    if (design.bidetOutletQuantity > 0) {
      newMaterialItems.push(
        {
          id: 'bidet-outlet-wire',
          name: '12/2 NM-B wire',
          quantity: (25 * design.bidetOutletQuantity).toString(),
          price: '1.80',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'bidet-outlet-box',
          name: 'Single-gang electrical box',
          quantity: design.bidetOutletQuantity.toString(),
          price: '3.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'bidet-outlet',
          name: 'Standard outlet',
          quantity: design.bidetOutletQuantity.toString(),
          price: '5.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        }
      );
    }

    if (design.ledMirrorQuantity > 0) {
      newMaterialItems.push(
        {
          id: 'mirror-power-wire',
          name: '14/2 NM-B wire',
          quantity: (20 * design.ledMirrorQuantity).toString(),
          price: '1.50',
          unit: 'ft',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        },
        {
          id: 'mirror-junction-box',
          name: 'Junction box',
          quantity: design.ledMirrorQuantity.toString(),
          price: '5.00',
          unit: 'each',
          category: 'construction',
          isAutoGenerated: true,
          color: 'green',
        }
      );
    }

    // =========================================================================
    // ELECTRICAL - FIXTURE INSTALLATION MATERIALS
    // =========================================================================

    if (design.replaceBathroomExhaustFan) {
      newMaterialItems.push({
        id: 'exhaust-fan-unit',
        name: 'Bathroom exhaust fan',
        quantity: '1',
        price: '85.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.exhaustFanControl) {
      newMaterialItems.push({
        id: 'fan-timer-control',
        name: 'Timer / Humidity sensor control',
        quantity: '1',
        price: '45.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.vanityWallLightQuantity > 0) {
      newMaterialItems.push({
        id: 'light-mounting-hardware',
        name: 'Light fixture mounting hardware',
        quantity: design.vanityWallLightQuantity.toString(),
        price: '8.00',
        unit: 'set',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.dimmerQuantity > 0) {
      newMaterialItems.push({
        id: 'dimmer-switch',
        name: 'Dimmer switch',
        quantity: design.dimmerQuantity.toString(),
        price: '28.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.switchOutletQuantity > 0) {
      newMaterialItems.push({
        id: 'switch-outlet-device',
        name: 'Switch or outlet device',
        quantity: design.switchOutletQuantity.toString(),
        price: '8.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.showerPotLightQuantity > 0) {
      newMaterialItems.push({
        id: 'wet-rated-pot-light',
        name: 'Wet-rated LED recessed light',
        quantity: design.showerPotLightQuantity.toString(),
        price: '55.00',
        unit: 'each',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // Merge custom items with auto-generated items
    const mergedMaterialItems = [...customMaterialItems, ...newMaterialItems];

    // Update context
    setMaterialItems('trade', mergedMaterialItems);
    setLocalMaterialItems(mergedMaterialItems);

    // Update processed choices
    processedChoicesRef.current = choicesKey;
  }, [design, isReloading, setMaterialItems, contextMaterialItems]);

  // Sync with context changes
  useEffect(() => {
    if (!isReloading) {
      setLocalMaterialItems(contextMaterialItems);
    }
  }, [contextMaterialItems, isReloading]);

  // Handlers
  const handleAddMaterialItem = useCallback(() => {
    const newItem: MaterialItem = {
      id: `material-${Date.now()}`,
      name: '',
      quantity: '1',
      price: '0',
      unit: '',
      category: 'construction',
      isAutoGenerated: false,
      color: 'gray',
    };

    const updatedItems = [...localMaterialItems, newItem];
    setLocalMaterialItems(updatedItems);
    setMaterialItems('trade', updatedItems);
    userActionRef.current = true;
  }, [localMaterialItems, setMaterialItems]);

  const handleUpdateMaterialItem = useCallback(
    (id: string, field: keyof MaterialItem, value: string) => {
      const updatedItems = localMaterialItems.map((item) =>
        item.id === id ? { ...item, [field]: value } : item
      );
      setLocalMaterialItems(updatedItems);
      setMaterialItems('trade', updatedItems);
      userActionRef.current = true;
    },
    [localMaterialItems, setMaterialItems]
  );

  const handleDeleteMaterialItem = useCallback(
    (id: string) => {
      const updatedItems = localMaterialItems.filter((item) => item.id !== id);
      setLocalMaterialItems(updatedItems);
      setMaterialItems('trade', updatedItems);
      userActionRef.current = true;
    },
    [localMaterialItems, setMaterialItems]
  );

  // Calculate totals
  const materialTotal = useMemo(() => {
    return localMaterialItems.reduce((total, item) => {
      const quantity = parseFloat(item.quantity) || 0;
      const price = parseFloat(item.price) || 0;
      return total + quantity * price;
    }, 0);
  }, [localMaterialItems]);

  // Group items by category
  const plumbingItems = localMaterialItems.filter(
    (item) => item.color === 'blue'
  );
  const electricalItems = localMaterialItems.filter(
    (item) => item.color === 'green'
  );
  const customItems = localMaterialItems.filter(
    (item) => item.color === 'gray'
  );

  // Calculate totals for each category
  const plumbingTotal = plumbingItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  const electricalTotal = electricalItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  const customTotal = customItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  const renderMaterialItem = useCallback(
    (item: MaterialItem) => (
      <div
        key={item.id}
        className='p-3 bg-white rounded-lg border border-slate-200 shadow-sm w-full'
      >
        <div className='flex items-center gap-2 mb-2 w-full'>
          <Input
            type='text'
            value={item.name}
            onChange={(e) =>
              handleUpdateMaterialItem(item.id, 'name', e.target.value)
            }
            placeholder='Material Name'
            className='border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full'
          />
          <Button
            onClick={() => handleDeleteMaterialItem(item.id)}
            variant='ghost'
            size='sm'
            className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
          >
            <Trash2 size={16} />
          </Button>
        </div>
        <div className='grid grid-cols-2 gap-3'>
          <div className='w-full'>
            <label className='text-xs text-slate-500'>Quantity</label>
            <Input
              type='number'
              value={item.quantity}
              onChange={(e) =>
                handleUpdateMaterialItem(item.id, 'quantity', e.target.value)
              }
              placeholder='0'
              className='text-center w-full border-blue-300 focus:border-blue-500'
            />
          </div>
          <div className='w-full'>
            <label className='text-xs text-slate-500'>Price/Unit ($)</label>
            <Input
              type='number'
              value={item.price}
              onChange={(e) =>
                handleUpdateMaterialItem(item.id, 'price', e.target.value)
              }
              placeholder='0.00'
              className='text-center w-full border-blue-300 focus:border-blue-500'
            />
          </div>
          <div className='col-span-2 w-full'>
            <label className='text-xs text-slate-500'>Total</label>
            <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
              $
              {(
                (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0)
              ).toFixed(2)}
            </div>
          </div>
        </div>
      </div>
    ),
    [handleUpdateMaterialItem, handleDeleteMaterialItem]
  );

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-center'>
        <h2 className='text-2xl font-bold text-slate-800'>
          Materials & Supplies
        </h2>
        <div className='text-right'>
          <p className='font-bold text-blue-600 text-lg'>
            ${materialTotal.toFixed(2)}
          </p>
        </div>
      </div>

      <div className='space-y-4'>
        {/* Plumbing */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsPlumbingOpen(!isPlumbingOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isPlumbingOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Plumbing
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${plumbingTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isPlumbingOpen && (
              <>
                {plumbingItems.length > 0 ? (
                  <div className='space-y-2'>
                    {plumbingItems.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No plumbing materials added yet. Select tasks in Design section.
                  </p>
                )}
              </>
            )}
          </CardContent>
        </Card>

        {/* Electrical */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsElectricalOpen(!isElectricalOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isElectricalOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Electrical
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${electricalTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isElectricalOpen && (
              <>
                {electricalItems.length > 0 ? (
                  <div className='space-y-2'>
                    {electricalItems.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No electrical materials added yet. Select tasks in Design section.
                  </p>
                )}
              </>
            )}
          </CardContent>
        </Card>

        {/* Custom Items */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsCustomOpen(!isCustomOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isCustomOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Custom Items
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${customTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isCustomOpen && (
              <>
                {customItems.length > 0 ? (
                  <div className='space-y-2'>
                    {customItems.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No custom materials added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddMaterialItem}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
