'use client';

import React, {
  useState,
  useEffect,
  useCallback,
  useMemo,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';
import {
  TradeDesignData,
  DEFAULT_TRADE_DESIGN,
} from '../design/TradeSection';

interface MaterialItem {
  id: string;
  name: string;
  quantity: string;
  price: string;
  unit: string;
  scope?: string;
  category?: 'design' | 'construction' | 'general';
  isAutoGenerated?: boolean;
  color?: string;
  source?: string;
}

export default function TradeMaterialsSection() {
  const { getDesignData, getMaterialItems, setMaterialItems, isReloading } =
    useEstimateWorkflowContext();

  const designData = getDesignData('trade') as TradeDesignData | null;
  const design = useMemo(
    () => ({
      ...DEFAULT_TRADE_DESIGN,
      ...designData,
      pricingModes: {
        ...DEFAULT_TRADE_DESIGN.pricingModes,
        ...(designData?.pricingModes || {}),
      },
      tradeRates: {
        ...DEFAULT_TRADE_DESIGN.tradeRates,
        ...(designData?.tradeRates || {}),
      },
    }),
    [designData]
  );

  const [localMaterialItems, setLocalMaterialItems] = useState<MaterialItem[]>(
    []
  );
  const [isPlumbingOpen, setIsPlumbingOpen] = useState(true);
  const [isElectricalOpen, setIsElectricalOpen] = useState(true);
  const [isCustomOpen, setIsCustomOpen] = useState(true);
  const userActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Get current items from context
  const contextMaterialItems = getMaterialItems('trade');

  // Auto-populate material items based on selected tasks
  useEffect(() => {
    if (isReloading || userActionRef.current) {
      userActionRef.current = false;
      return;
    }

    // Create a key based on all design choices to detect changes
    const choicesKey = JSON.stringify(design);

    // Skip if choices haven't changed
    if (processedChoicesRef.current === choicesKey) return;

    // Preserve custom items (non-auto-generated)
    const contextMaterials = contextMaterialItems || [];
    const customMaterialItems = contextMaterials.filter(
      (item) => item.isAutoGenerated === false
    );

    const newMaterialItems: MaterialItem[] = [];

    // =========================================================================
    // PLUMBING - ROUGH-IN MATERIALS (Allowance-based)
    // =========================================================================

    if (design.moveToiletDrainSupply) {
      const qty = design.moveToiletDrainSupplyQuantity || 1;
      newMaterialItems.push({
        id: 'toilet-roughin-allowance',
        name: 'Toilet rough-in materials (drain + flange + shutoff)',
        quantity: qty.toString(),
        price: '150.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.relocateFixtureDrain) {
      const qty = design.relocateFixtureDrainQuantity || 1;
      newMaterialItems.push({
        id: 'drain-relocate-allowance',
        name: 'Drain relocate materials (pipe + fittings)',
        quantity: qty.toString(),
        price: '110.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installNewShowerValve) {
      newMaterialItems.push({
        id: 'shower-valve-allowance',
        name: 'Shower valve install materials (pipe + fittings)',
        quantity: '1',
        price: '85.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.roughInDiverter) {
      newMaterialItems.push({
        id: 'diverter-allowance',
        name: 'Diverter install materials (pipe + fittings)',
        quantity: '1',
        price: '75.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.addVanityPlumbingRoughIn) {
      const qty = design.addVanityPlumbingRoughInQuantity || 1;
      newMaterialItems.push({
        id: 'vanity-roughin-allowance',
        name: 'Vanity rough-in materials (shutoffs + drain parts)',
        quantity: qty.toString(),
        price: '90.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.addFreestandingTubRoughIn) {
      newMaterialItems.push({
        id: 'tub-roughin-allowance',
        name: 'Tub rough-in materials (drain/supply parts)',
        quantity: '1',
        price: '220.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.addBidetPlumbingRoughIn) {
      const qty = design.addBidetPlumbingRoughInQuantity || 1;
      newMaterialItems.push({
        id: 'bidet-roughin-allowance',
        name: 'Bidet rough-in materials (tee + shutoff + flex)',
        quantity: qty.toString(),
        price: '35.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // =========================================================================
    // PLUMBING - FIXTURE INSTALLATION MATERIALS (Allowance-based)
    // =========================================================================

    if (design.vanityInstallationType === 'single') {
      newMaterialItems.push({
        id: 'vanity-install-allowance',
        name: 'Vanity install supplies (shims + fasteners + sealant)',
        quantity: '1',
        price: '25.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.vanityInstallationType === 'double') {
      newMaterialItems.push({
        id: 'vanity-install-allowance',
        name: 'Double vanity install supplies (shims + fasteners + sealant)',
        quantity: '1',
        price: '35.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.connectSinkDrains) {
      const qty = design.connectSinkDrainsQuantity || 1;
      newMaterialItems.push({
        id: 'sink-drain-allowance',
        name: 'Sink drain hookup supplies (trap + adapters)',
        quantity: qty.toString(),
        price: '15.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installVanityFaucetSupplyLines) {
      const qty = design.installVanityFaucetSupplyLinesQuantity || 1;
      newMaterialItems.push({
        id: 'faucet-hookup-allowance',
        name: 'Faucet hookup supplies (supply lines + sealants)',
        quantity: qty.toString(),
        price: '20.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Shower Trim - combined allowance based on selections
    const hasBaseTrim = design.showerTrimValve || design.showerTrimShowerHead;
    if (hasBaseTrim) {
      const includesSpout = design.showerTrimSpout;
      newMaterialItems.push({
        id: 'shower-trim-allowance',
        name: includesSpout
          ? 'Shower trim install supplies incl. spout (tape + silicone + hardware)'
          : 'Shower trim install supplies (tape + silicone + small hardware)',
        quantity: '1',
        price: includesSpout ? '25.00' : '20.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // Separate tub spout - only when spout selected without base trim
    if (design.showerTrimSpout && !hasBaseTrim) {
      newMaterialItems.push({
        id: 'tub-spout-allowance',
        name: 'Tub spout install supplies (tape + set-screw/caulk)',
        quantity: '1',
        price: '10.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.showerTrimHandheld) {
      newMaterialItems.push({
        id: 'handheld-allowance',
        name: 'Handheld install supplies (mounting + tape + sealant)',
        quantity: '1',
        price: '20.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.showerTrimRainhead) {
      newMaterialItems.push({
        id: 'rainhead-allowance',
        name: 'Rainhead install supplies (arm/adapter + tape + sealant)',
        quantity: '1',
        price: '25.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installToilet) {
      newMaterialItems.push({
        id: 'toilet-install-allowance',
        name: 'Toilet install supplies (wax ring + bolts + caulk)',
        quantity: '1',
        price: '25.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installBidetSeat) {
      newMaterialItems.push({
        id: 'bidet-install-allowance',
        name: 'Bidet hookup supplies (tee + shutoff + flex)',
        quantity: '1',
        price: '20.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    if (design.installFreestandingTubFaucet) {
      newMaterialItems.push({
        id: 'tub-finishing-allowance',
        name: 'Tub hookup supplies (drain parts + supplies + sealants)',
        quantity: '1',
        price: '150.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'blue',
      });
    }

    // =========================================================================
    // ELECTRICAL - ROUGH-IN MATERIALS (Allowance-based)
    // =========================================================================

    if (design.heatedFloorThermostatPower) {
      newMaterialItems.push({
        id: 'heated-floor-allowance',
        name: 'Thermostat Hookup Materials Allowance (wire + box/plate + connectors)',
        quantity: '1',
        price: '50.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.potLightQuantity > 0) {
      newMaterialItems.push({
        id: 'pot-light-allowance',
        name: 'Pot Light Materials Allowance (LED pot light + wire + connectors)',
        quantity: design.potLightQuantity.toString(),
        price: '55.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.gfciOutletQuantity > 0) {
      newMaterialItems.push({
        id: 'gfci-allowance',
        name: 'GFCI Outlet Materials Allowance (GFCI + box/plate + wire)',
        quantity: design.gfciOutletQuantity.toString(),
        price: '55.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.bidetOutletQuantity > 0) {
      newMaterialItems.push({
        id: 'bidet-outlet-allowance',
        name: 'Outlet Materials Allowance (receptacle + box/plate + wire)',
        quantity: design.bidetOutletQuantity.toString(),
        price: '45.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.ledMirrorQuantity > 0) {
      newMaterialItems.push({
        id: 'mirror-power-allowance',
        name: 'Mirror Power Materials Allowance (receptacle/kit + box/plate + wire)',
        quantity: design.ledMirrorQuantity.toString(),
        price: '50.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // =========================================================================
    // ELECTRICAL - FIXTURE INSTALLATION MATERIALS (Allowance-based)
    // =========================================================================

    if (design.replaceBathroomExhaustFan) {
      newMaterialItems.push({
        id: 'exhaust-fan-allowance',
        name: 'Fan Replacement Materials Allowance (misc hardware + connectors)',
        quantity: '1',
        price: '75.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.exhaustFanControl) {
      newMaterialItems.push({
        id: 'fan-control-allowance',
        name: 'Fan Control Switch Allowance (timer/humidity switch + wall plate)',
        quantity: '1',
        price: '55.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.vanityWallLightQuantity > 0) {
      newMaterialItems.push({
        id: 'wall-light-allowance',
        name: 'Light Fixture Install Allowance (connectors + mounting hardware)',
        quantity: design.vanityWallLightQuantity.toString(),
        price: '10.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.dimmerQuantity > 0) {
      newMaterialItems.push({
        id: 'dimmer-allowance',
        name: 'Dimmer Switch Allowance (dimmer + wall plate)',
        quantity: design.dimmerQuantity.toString(),
        price: '45.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.switchOutletQuantity > 0) {
      newMaterialItems.push({
        id: 'switch-outlet-allowance',
        name: 'Switch/Outlet Allowance (device + wall plate)',
        quantity: design.switchOutletQuantity.toString(),
        price: '20.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    if (design.showerPotLightQuantity > 0) {
      newMaterialItems.push({
        id: 'wet-light-allowance',
        name: 'Wet-Rated Shower Light Allowance (trim/fixture + connectors)',
        quantity: design.showerPotLightQuantity.toString(),
        price: '90.00',
        unit: 'allowance',
        category: 'construction',
        isAutoGenerated: true,
        color: 'green',
      });
    }

    // Merge custom items with auto-generated items
    const mergedMaterialItems = [...customMaterialItems, ...newMaterialItems];

    // Update context
    setMaterialItems('trade', mergedMaterialItems);
    setLocalMaterialItems(mergedMaterialItems);

    // Update processed choices
    processedChoicesRef.current = choicesKey;
  }, [design, isReloading, setMaterialItems, contextMaterialItems]);

  // Sync with context changes
  useEffect(() => {
    if (!isReloading) {
      setLocalMaterialItems(contextMaterialItems);
    }
  }, [contextMaterialItems, isReloading]);

  // Handlers
  const handleAddMaterialItem = useCallback(() => {
    const newItem: MaterialItem = {
      id: `material-${Date.now()}`,
      name: '',
      quantity: '1',
      price: '0',
      unit: '',
      category: 'construction',
      isAutoGenerated: false,
      color: 'gray',
    };

    const updatedItems = [...localMaterialItems, newItem];
    setLocalMaterialItems(updatedItems);
    setMaterialItems('trade', updatedItems);
    userActionRef.current = true;
  }, [localMaterialItems, setMaterialItems]);

  const handleUpdateMaterialItem = useCallback(
    (id: string, field: keyof MaterialItem, value: string) => {
      const updatedItems = localMaterialItems.map((item) =>
        item.id === id ? { ...item, [field]: value } : item
      );
      setLocalMaterialItems(updatedItems);
      setMaterialItems('trade', updatedItems);
      userActionRef.current = true;
    },
    [localMaterialItems, setMaterialItems]
  );

  const handleDeleteMaterialItem = useCallback(
    (id: string) => {
      const updatedItems = localMaterialItems.filter((item) => item.id !== id);
      setLocalMaterialItems(updatedItems);
      setMaterialItems('trade', updatedItems);
      userActionRef.current = true;
    },
    [localMaterialItems, setMaterialItems]
  );

  // Calculate totals
  const materialTotal = useMemo(() => {
    return localMaterialItems.reduce((total, item) => {
      const quantity = parseFloat(item.quantity) || 0;
      const price = parseFloat(item.price) || 0;
      return total + quantity * price;
    }, 0);
  }, [localMaterialItems]);

  // Group items by category
  const plumbingItems = localMaterialItems.filter(
    (item) => item.color === 'blue'
  );
  const electricalItems = localMaterialItems.filter(
    (item) => item.color === 'green'
  );
  const customItems = localMaterialItems.filter(
    (item) => item.color === 'gray'
  );

  // Calculate totals for each category
  const plumbingTotal = plumbingItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  const electricalTotal = electricalItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  const customTotal = customItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  const renderMaterialItem = useCallback(
    (item: MaterialItem) => (
      <div
        key={item.id}
        className='p-3 bg-white rounded-lg border border-slate-200 shadow-sm w-full'
      >
        <div className='flex items-center gap-2 mb-2 w-full'>
          <Input
            type='text'
            value={item.name}
            onChange={(e) =>
              handleUpdateMaterialItem(item.id, 'name', e.target.value)
            }
            placeholder='Material Name'
            className='border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full'
          />
          <Button
            onClick={() => handleDeleteMaterialItem(item.id)}
            variant='ghost'
            size='sm'
            className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
          >
            <Trash2 size={16} />
          </Button>
        </div>
        <div className='grid grid-cols-2 gap-3'>
          <div className='w-full'>
            <label className='text-xs text-slate-500'>Quantity</label>
            <Input
              type='number'
              value={item.quantity}
              onChange={(e) =>
                handleUpdateMaterialItem(item.id, 'quantity', e.target.value)
              }
              placeholder='0'
              className='text-center w-full border-blue-300 focus:border-blue-500'
            />
          </div>
          <div className='w-full'>
            <label className='text-xs text-slate-500'>Price/Unit ($)</label>
            <Input
              type='number'
              value={item.price}
              onChange={(e) =>
                handleUpdateMaterialItem(item.id, 'price', e.target.value)
              }
              placeholder='0.00'
              className='text-center w-full border-blue-300 focus:border-blue-500'
            />
          </div>
          <div className='col-span-2 w-full'>
            <label className='text-xs text-slate-500'>Total</label>
            <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
              $
              {(
                (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0)
              ).toFixed(2)}
            </div>
          </div>
        </div>
      </div>
    ),
    [handleUpdateMaterialItem, handleDeleteMaterialItem]
  );

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-center'>
        <h2 className='text-2xl font-bold text-slate-800'>
          Materials & Supplies
        </h2>
        <div className='text-right'>
          <p className='font-bold text-blue-600 text-lg'>
            ${materialTotal.toFixed(2)}
          </p>
        </div>
      </div>

      <div className='space-y-4'>
        {/* Plumbing */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsPlumbingOpen(!isPlumbingOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isPlumbingOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Plumbing
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${plumbingTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isPlumbingOpen && (
              <>
                {plumbingItems.length > 0 ? (
                  <div className='space-y-2'>
                    {plumbingItems.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No plumbing materials added yet. Select tasks in Design section.
                  </p>
                )}
              </>
            )}
          </CardContent>
        </Card>

        {/* Electrical */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsElectricalOpen(!isElectricalOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isElectricalOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Electrical
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${electricalTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isElectricalOpen && (
              <>
                {electricalItems.length > 0 ? (
                  <div className='space-y-2'>
                    {electricalItems.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No electrical materials added yet. Select tasks in Design section.
                  </p>
                )}
              </>
            )}
          </CardContent>
        </Card>

        {/* Custom Items */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsCustomOpen(!isCustomOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isCustomOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Custom Items
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${customTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isCustomOpen && (
              <>
                {customItems.length > 0 ? (
                  <div className='space-y-2'>
                    {customItems.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No custom materials added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddMaterialItem}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
