// Core data types for estimate workflows

// ============================================================================
// WORKFLOW-SPECIFIC DTOs
// ============================================================================

// Demolition Workflow DTOs
export interface DemolitionChoices {
  removeFlooring: 'yes' | 'no';
  removeShowerWall: 'yes' | 'no';
  removeShowerBase: 'yes' | 'no';
  removeTub: 'yes' | 'no';
  removeVanity: 'yes' | 'no';
  removeToilet: 'yes' | 'no';
  removeAccessories: 'yes' | 'no';
  removeWall: 'yes' | 'no';
}

export interface DemolitionDesignData {
  demolitionChoices: DemolitionChoices;
  debrisDisposal: 'yes' | 'no';
  isDemolitionFlatFee: 'yes' | 'no';
  flatFeeAmount: string;
  flatFeeDescription: string;
}

// Shower Walls Workflow DTOs
export interface ShowerWallsMeasurements {
  length: string;
  width: string;
  height: string;
}

export interface ShowerWallsDesignData {
  measurements: ShowerWallsMeasurements;
  wallType: 'tile' | 'panels' | 'paint';
  tileType?: string;
  panelType?: string;
  paintType?: string;
  waterproofing: 'yes' | 'no';
  groutType?: string;
  trimType?: string;
}

// Shower Base Workflow DTOs
export interface ShowerBaseMeasurements {
  length: string;
  width: string;
  depth: string;
}

export interface ShowerBaseDesignData {
  measurements: ShowerBaseMeasurements;
  baseType: 'tile' | 'panels' | 'acrylic';
  waterproofing: 'yes' | 'no';
  drainType: 'center' | 'corner';
  slopeType: 'standard' | 'custom';
}

// Floors Workflow DTOs
export interface FloorDesignData {
  measurements: {
    width: number;
    length: number;
    extraMeasurements: Array<{
      id: string;
      name: string;
      width: number;
      length: number;
    }>;
  };
  design: {
    tilePattern: string;
    notes: string;
  };
  construction: {
    selectedPrepTasks: string[];
    plywoodThickness: string;
    constructionNotes: string;
  };
}

// Finishings Workflow DTOs
export interface FinishingsDesignData {
  designChoices: {
    selectedFinishes: string[];
    paintColors: string[];
    fixtures: string[];
  };
  finishingsScope: {
    selectedScopes: string[];
    customScope: string;
  };
  accentWalls: {
    hasAccentWall: boolean;
    paintType: string;
    wallLocations: string[];
  };
}

// Structural Workflow DTOs
export interface StructuralDesignData {
  choices: {
    electrical: string[];
    plumbing: string[];
    ventilation: string[];
    structural: string[];
  };
}

// Trades Workflow DTOs
export interface TradesDesignData {
  choices: {
    electrical: Array<{ id: string; quantity: string }>;
    plumbing: Array<{ id: string; quantity: string }>;
    hvac: Array<{ id: string; quantity: string }>;
    flooring: Array<{ id: string; quantity: string }>;
    tile: Array<{ id: string; quantity: string }>;
    paint: Array<{ id: string; quantity: string }>;
  };
}

// Union type for all workflow design data
export type WorkflowDesignData =
  | DemolitionDesignData
  | ShowerWallsDesignData
  | ShowerBaseDesignData
  | FloorDesignData
  | FinishingsDesignData
  | StructuralDesignData
  | TradesDesignData;

// ============================================================================
// CORE WORKFLOW TYPES
// ============================================================================

export interface LaborItem {
  id: string;
  name: string;
  hours: string;
  rate: string;
  flatPrice?: string;
  pricingMode?: 'flat' | 'hourly';
  quantity?: number;
  taskId?: string;
  scope?: string;
  category?: 'design' | 'construction' | 'general';
  isAutoGenerated?: boolean;
  color?: string;
}

export interface MaterialItem {
  id: string;
  name: string;
  quantity: string;
  price: string;
  unit: string;
  scope?: string;
  category?: 'design' | 'construction' | 'general';
  isAutoGenerated?: boolean;
  color?: string;
}

export interface FlatFeeItem {
  id: string;
  name: string;
  unitPrice: string;
  description?: string;
}

export interface WorkflowNotes {
  contractorNotes: string;
  clientNotes: string;
}

export interface WorkflowEstimate {
  laborTotal: number;
  materialsTotal: number;
  grandTotal: number;
  lastUpdated: string;
}

// Base workflow data structure
export interface WorkflowData<TDesign = WorkflowDesignData> {
  design?: TDesign;
  labor: {
    hourlyItems: LaborItem[];
    flatFeeItems: FlatFeeItem[];
  };
  materials: {
    items: MaterialItem[];
  };
  notes: WorkflowNotes;
  estimate: WorkflowEstimate;
}

// Note: Workflow-specific design data interfaces are defined above in the DTOs section

// Complete workflow interfaces
export interface DemolitionWorkflow {
  design: DemolitionDesignData;
  workflow: WorkflowData;
}

export interface ShowerWallsWorkflow {
  design: ShowerWallsDesignData;
  workflow: WorkflowData;
}

export interface ShowerBaseWorkflow {
  design: ShowerBaseDesignData;
  workflow: WorkflowData;
}

export interface FloorWorkflow {
  design: FloorDesignData;
  workflow: WorkflowData;
}

export interface FinishingsWorkflow {
  design: FinishingsDesignData;
  workflow: WorkflowData;
}

export interface StructuralWorkflow {
  design: StructuralDesignData;
  workflow: WorkflowData;
}

export interface TradesWorkflow {
  design: TradesDesignData;
  workflow: WorkflowData;
}

// Main estimate data structure
export interface EstimateData {
  // Project metadata
  projectId: string;
  projectNotes: string;
  lastUpdated: string;

  // Workflows
  workflows: {
    demolition: DemolitionWorkflow;
    showerWalls: ShowerWallsWorkflow;
    showerBase: ShowerBaseWorkflow;
    floors: FloorWorkflow;
    finishings: FinishingsWorkflow;
    structural: StructuralWorkflow;
    trade: TradesWorkflow;
  };

  // Overall estimate summary
  estimate: {
    totalLabor: number;
    totalMaterials: number;
    grandTotal: number;
    breakdown: Array<{
      workflow: string;
      name: string;
      laborCost: number;
      materialsCost: number;
      total: number;
    }>;
  };
}

// Helper types for workflow management
export type WorkflowType = keyof EstimateData['workflows'];
export type SectionType = 'design' | 'labor' | 'materials';

// Workflow state management interface
export interface UseWorkflowReturn<
  TDesign = unknown,
  TWorkflow = WorkflowData
> {
  design: TDesign;
  workflow: TWorkflow;
  actions: {
    updateDesign: (updates: Partial<TDesign>) => void;
    addLaborItem: (item: Omit<LaborItem, 'id'>) => void;
    updateLaborItem: (id: string, updates: Partial<LaborItem>) => void;
    deleteLaborItem: (id: string) => void;
    setLaborItems: (items: LaborItem[]) => void;
    addMaterialItem: (item: Omit<MaterialItem, 'id'>) => void;
    updateMaterialItem: (id: string, updates: Partial<MaterialItem>) => void;
    deleteMaterialItem: (id: string) => void;
    setMaterialItems: (items: MaterialItem[]) => void;
    addFlatFeeItem: (item: Omit<FlatFeeItem, 'id'>) => void;
    updateFlatFeeItem: (id: string, updates: Partial<FlatFeeItem>) => void;
    deleteFlatFeeItem: (id: string) => void;
    setFlatFeeItems: (items: FlatFeeItem[]) => void;
    updateNotes: (notes: Partial<WorkflowNotes>) => void;
  };
  totals: {
    laborTotal: number;
    materialsTotal: number;
    grandTotal: number;
  };
  getData: () => { design: TDesign; workflow: TWorkflow };
  setData: (data: { design: TDesign; workflow: TWorkflow }) => void;
}
