'use client';

import React, {
  useMemo,
  useCallback,
  useState,
  useEffect,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { SHOWER_WALLS_LABOR_ITEMS } from '@/lib/constants';
import {
  LaborItem as ContextLaborItem,
  FlatFeeItem as ContextFlatFeeItem,
} from '@/types/estimate';

type LaborItem = ContextLaborItem & { source?: string };
type FlatFeeItem = ContextFlatFeeItem & {
  source?: string;
  isAutoGenerated?: boolean;
};

interface ShowerWallsDesignData {
  walls: Array<{
    id: string;
    name: string;
    height: { ft: number; inch: number };
    width: { ft: number; inch: number };
  }>;
  design: {
    clientSuppliesBase: 'No' | 'Yes';
    tileSize: string;
    customTileWidth?: string;
    customTileLength?: string;
    tilePattern: string;
    customTilePatternName?: string;
    niche: string;
    showerDoor: string;
    waterproofingSystem: string;
    customWaterproofingName?: string;
    grabBar: string;
    repairWalls: boolean;
    reinsulateWalls: boolean;
    notes?: string;
    constructionNotes?: string;
  };
}

export default function ShowerWallsLaborSection() {
  const {
    getDesignData,
    getLaborItems,
    getFlatFeeItems,
    setLaborItems,
    isReloading,
  } = useEstimateWorkflowContext();

  // Get design data from context
  const designData = getDesignData(
    'showerWalls'
  ) as ShowerWallsDesignData | null;
  const walls = useMemo(() => designData?.walls || [], [designData]);
  const design = useMemo(
    () =>
      designData?.design || {
        clientSuppliesBase: 'No',
        tileSize: 'Select tile size',
        tilePattern: 'Select Tile Pattern',
        niche: 'None',
        showerDoor: 'None',
        waterproofingSystem: 'None / Select System...',
        grabBar: '0',
        repairWalls: false,
        reinsulateWalls: false,
      },
    [designData]
  );

  // Get contractor hourly rate (default to 85.00 as per business logic)
  const contractorHourlyRate = 85.0;

  // Get context data
  const contextLaborItems = getLaborItems('showerWalls');
  const contextFlatFeeItems = getFlatFeeItems('showerWalls');

  // Local state for immediate UI updates
  const [localLaborItems, setLocalLaborItems] = useState<LaborItem[]>([]);
  const [localFlatFeeItems, setLocalFlatFeeItems] = useState<FlatFeeItem[]>([]);
  const [isShowerWallsOpen, setIsShowerWallsOpen] = useState(true);

  // Refs to track user actions and prevent auto-generation interference
  const isUserActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Calculate total square footage
  const totalSqft = useMemo(() => {
    return walls.reduce((total, wall) => {
      const heightInFeet = wall.height.ft + wall.height.inch / 12;
      const widthInFeet = wall.width.ft + wall.width.inch / 12;
      return total + heightInFeet * widthInFeet;
    }, 0);
  }, [walls]);

  // Calculate waste factor based on tile pattern
  const wasteFactor = useMemo(() => {
    switch (design.tilePattern) {
      case 'Herringbone':
        return 1.25;
      case '1/2 Offset':
      case '1/3 Offset':
        return 1.15;
      default:
        return 1.1;
    }
  }, [design.tilePattern]);

  // Calculate tile needed
  const tileNeeded = useMemo(() => {
    if (design.tileSize === 'Select tile size') return 0;
    return totalSqft * wasteFactor;
  }, [totalSqft, wasteFactor, design.tileSize]);

  // Helper function to generate labor items based on shower walls design
  const generateLaborItems = useCallback(
    (designData: ShowerWallsDesignData): LaborItem[] => {
      const laborItems: LaborItem[] = [];
      const { walls, design } = designData;
      const totalSqft = walls.reduce((total, wall) => {
        const heightInFeet = wall.height.ft + wall.height.inch / 12;
        const widthInFeet = wall.width.ft + wall.width.inch / 12;
        return total + heightInFeet * widthInFeet;
      }, 0);

      const laborItemsConfig = SHOWER_WALLS_LABOR_ITEMS(contractorHourlyRate);

      // Only generate tiling flow if tile size is selected
      if (design.tileSize !== 'Select tile size') {
        // Base tiling speed
        const baseRate = design.tileSize.includes('Subway') ? 7 : 10;

        // Pattern modifier
        let patternModifier = 1.0;
        if (
          design.tilePattern === '1/2 Offset' ||
          design.tilePattern === '1/3 Offset'
        ) {
          patternModifier = 1.15;
        } else if (design.tilePattern === 'Herringbone') {
          patternModifier = 1.3;
        }

        // Calculate tiling hours
        const tilingHours = (totalSqft / baseRate) * patternModifier;

        // Add tiling flow items
        laborItems.push({
          ...laborItemsConfig.boarding,
          hours: (totalSqft / 30).toFixed(2),
        });

        const patternName =
          design.tilePattern === 'Select Tile Pattern'
            ? ''
            : ` (${design.tilePattern})`;
        laborItems.push({
          ...laborItemsConfig.tiling,
          name: `Tiling Walls${patternName}`,
          hours: tilingHours.toFixed(2),
        });

        laborItems.push({
          ...laborItemsConfig.grouting,
          hours: (totalSqft / 40).toFixed(2),
        });

        laborItems.push(laborItemsConfig.silicone);
      }

      // Add features & conditions
      if (design.niche !== 'None') {
        const nicheSize =
          design.niche === 'Custom Size' ? ' (Custom)' : ` (${design.niche})`;
        laborItems.push({
          ...laborItemsConfig.niche,
          name: `Niche Installation${nicheSize}`,
        });
      }

      if (design.showerDoor !== 'None') {
        const doorType =
          design.showerDoor === 'Custom Glass'
            ? ' (Custom)'
            : ` (${design.showerDoor})`;
        laborItems.push({
          ...laborItemsConfig.door,
          name: `Shower Door Installation${doorType}`,
        });
        laborItems.push(laborItemsConfig.doorBlocking);
      }

      const grabBarCount = parseInt(design.grabBar) || 0;
      if (grabBarCount > 0) {
        laborItems.push({
          ...laborItemsConfig.grabBar,
          name: `Install ${grabBarCount} Grab Bar${
            grabBarCount > 1 ? 's' : ''
          }`,
          hours: (1.5 * grabBarCount).toFixed(2),
        });
      }

      if (design.repairWalls) {
        laborItems.push(laborItemsConfig.repair);
      }

      if (design.reinsulateWalls) {
        laborItems.push(laborItemsConfig.reinsulate);
      }

      // Add waterproofing labor
      if (design.waterproofingSystem !== 'None / Select System...') {
        const wpName =
          design.waterproofingSystem === 'Other' &&
          design.customWaterproofingName
            ? design.customWaterproofingName
            : design.waterproofingSystem;

        let wpHours = totalSqft / 40; // Default
        switch (design.waterproofingSystem) {
          case 'Schluter®-KERDI System':
            wpHours = totalSqft / 40;
            break;
          case 'RedGard® Waterproofing Membrane':
          case 'LATICRETE® HYDRO BAN':
            wpHours = totalSqft / 60;
            break;
          case 'Drywall and Kerdi membrane':
            wpHours = totalSqft / 25;
            break;
        }

        laborItems.push({
          ...laborItemsConfig.waterproofing,
          name: `Waterproofing: ${wpName}`,
          hours: wpHours.toFixed(2),
        });
      }

      return laborItems;
    },
    [contractorHourlyRate]
  );

  // Sync local state with context
  useEffect(() => {
    setLocalLaborItems(contextLaborItems);
    setLocalFlatFeeItems(contextFlatFeeItems);
  }, [contextLaborItems, contextFlatFeeItems]);

  // Auto-generate labor items when design changes
  useEffect(() => {
    // Don't run if user is currently making changes or if we're reloading data
    if (isUserActionRef.current || isReloading) return;

    // If we have data from context (Supabase), never override it with defaults
    if (contextLaborItems && contextLaborItems.length > 0) {
      return;
    }

    // Create a key for the current design to prevent reprocessing
    const designKey = JSON.stringify({
      walls,
      design,
      totalSqft,
    });
    if (processedChoicesRef.current === designKey) {
      return;
    }

    const currentLabor = localLaborItems || [];
    const existingAutoItems = currentLabor.filter(
      (item) => item.source === 'calculated'
    );

    // Only generate if we have design data and no existing auto items
    if (designData && existingAutoItems.length === 0) {
      const newAutoItems = generateLaborItems(designData);

      if (newAutoItems.length > 0) {
        setLaborItems('showerWalls', newAutoItems);
        processedChoicesRef.current = designKey;
      }
    }
  }, [
    walls,
    design,
    totalSqft,
    generateLaborItems,
    localLaborItems,
    contextLaborItems,
    isReloading,
    setLaborItems,
    designData,
  ]);

  // Handlers for labor items
  const handleAddLaborItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `custom-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      name: 'Custom Labor Item',
      hours: '1',
      rate: contractorHourlyRate.toString(),
      source: 'custom',
    };

    isUserActionRef.current = true;
    setLocalLaborItems((prev) => [...prev, newItem]);

    setTimeout(() => {
      setLaborItems('showerWalls', [...localLaborItems, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localLaborItems, setLaborItems, contractorHourlyRate]);

  const handleLaborItemChange = useCallback(
    (id: string, field: keyof LaborItem, value: string) => {
      isUserActionRef.current = true;

      setLocalLaborItems((prev) =>
        prev.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        )
      );

      setTimeout(() => {
        const updatedItems = localLaborItems.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        );
        setLaborItems('showerWalls', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, setLaborItems]
  );

  const handleDeleteLaborItem = useCallback(
    (id: string) => {
      isUserActionRef.current = true;

      setLocalLaborItems((prev) => prev.filter((item) => item.id !== id));

      setTimeout(() => {
        const updatedItems = localLaborItems.filter((item) => item.id !== id);
        setLaborItems('showerWalls', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, setLaborItems]
  );

  const handleAddFlatFeeItem = useCallback(() => {
    const newItem: FlatFeeItem = {
      id: `flat-fee-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      name: 'Custom Flat Fee Item',
      unitPrice: '0.00',
      description: 'Custom flat fee item',
      source: 'custom',
    };

    isUserActionRef.current = true;
    setLocalFlatFeeItems((prev) => [...prev, newItem]);

    setTimeout(() => {
      // Convert FlatFeeItem to LaborItem for context
      const laborItem: LaborItem = {
        id: newItem.id,
        name: newItem.name,
        hours: '1',
        rate: newItem.unitPrice,
        source: newItem.source,
      };
      setLaborItems('showerWalls', [...localLaborItems, laborItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localLaborItems, setLaborItems]);

  const handleFlatFeeItemChange = useCallback(
    (id: string, field: keyof FlatFeeItem, value: string) => {
      isUserActionRef.current = true;

      setLocalFlatFeeItems((prev) =>
        prev.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        )
      );

      setTimeout(() => {
        // Convert FlatFeeItem changes to LaborItem for context
        const updatedItems = localLaborItems.map((item) => {
          if (item.id === id) {
            const flatFeeItem = localFlatFeeItems.find((f) => f.id === id);
            if (flatFeeItem) {
              return {
                ...item,
                name: flatFeeItem.name,
                rate: flatFeeItem.unitPrice,
              };
            }
          }
          return item;
        });
        setLaborItems('showerWalls', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, localFlatFeeItems, setLaborItems]
  );

  const handleDeleteFlatFeeItem = useCallback(
    (id: string) => {
      isUserActionRef.current = true;

      setLocalFlatFeeItems((prev) => prev.filter((item) => item.id !== id));

      setTimeout(() => {
        const updatedItems = localLaborItems.filter((item) => item.id !== id);
        setLaborItems('showerWalls', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, setLaborItems]
  );

  const laborItems = localLaborItems;
  const flatFeeItems = localFlatFeeItems;

  const renderLaborItem = useCallback(
    (item: LaborItem) => {
      return (
        <div
          key={item.id}
          className={`p-3 rounded-lg border shadow-sm w-full ${
            item.isAutoGenerated
              ? 'bg-blue-50 border-blue-200'
              : 'bg-white border-slate-200'
          }`}
        >
          <div className='flex items-center gap-2 mb-2 w-full'>
            <Input
              type='text'
              value={item.name}
              onChange={(e) =>
                handleLaborItemChange(item.id, 'name', e.target.value)
              }
              placeholder='Labor Task'
              className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full`}
            />
            <Button
              onClick={() => handleDeleteLaborItem(item.id)}
              variant='ghost'
              size='sm'
              className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
            >
              <Trash2 size={16} />
            </Button>
          </div>
          <div className='grid grid-cols-3 gap-3'>
            <div className='w-full'>
              <label className='text-xs text-slate-500'>Hours</label>
              <Input
                type='number'
                value={item.hours}
                onChange={(e) =>
                  handleLaborItemChange(item.id, 'hours', e.target.value)
                }
                placeholder='0'
                className='text-center w-full border-blue-300 focus:border-blue-500'
              />
            </div>
            <div className='w-full'>
              <label className='text-xs text-slate-500'>Rate ($/hr)</label>
              <Input
                type='number'
                value={item.rate}
                onChange={(e) =>
                  handleLaborItemChange(item.id, 'rate', e.target.value)
                }
                placeholder='0'
                className='text-center w-full border-blue-300 focus:border-blue-500'
              />
            </div>
            <div className='w-full'>
              <label className='text-xs text-slate-500'>Total</label>
              <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
                $
                {(
                  (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0)
                ).toFixed(2)}
              </div>
            </div>
          </div>
        </div>
      );
    },
    [handleLaborItemChange, handleDeleteLaborItem]
  );

  const renderFlatFeeItem = useCallback(
    (item: FlatFeeItem) => {
      return (
        <div
          key={item.id}
          className={`p-3 rounded-lg border shadow-sm w-full ${
            item.isAutoGenerated
              ? 'bg-blue-50 border-blue-200'
              : 'bg-white border-slate-200'
          }`}
        >
          <div className='flex items-center gap-2 mb-2 w-full'>
            <Input
              type='text'
              value={item.name}
              onChange={(e) =>
                handleFlatFeeItemChange(item.id, 'name', e.target.value)
              }
              placeholder='Flat Fee Task'
              className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full`}
            />
            <Button
              onClick={() => handleDeleteFlatFeeItem(item.id)}
              variant='ghost'
              size='sm'
              className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
            >
              <Trash2 size={16} />
            </Button>
          </div>
          <div className='w-full'>
            <label className='text-xs text-slate-500'>Total ($)</label>
            <Input
              type='number'
              value={item.unitPrice}
              onChange={(e) =>
                handleFlatFeeItemChange(item.id, 'unitPrice', e.target.value)
              }
              placeholder='0.00'
              className='text-center w-full border-b-2 border-t-0 border-l-0 border-r-0 border-blue-500 focus:border-blue-500'
            />
          </div>
        </div>
      );
    },
    [handleFlatFeeItemChange, handleDeleteFlatFeeItem]
  );

  const laborTotal = laborItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0),
    0
  );
  const totalHours = laborItems.reduce(
    (sum, item) => sum + (parseFloat(item.hours) || 0),
    0
  );
  const flatFeeTotal = flatFeeItems.reduce(
    (sum, item) => sum + (parseFloat(item.unitPrice) || 0),
    0
  );

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-baseline'>
        <h2 className='text-2xl font-bold text-slate-800'>Labor</h2>
      </div>

      <div className='space-y-4'>
        {/* Hourly Labor Section */}
        {laborItems.length > 0 && (
          <Card>
            <CardContent className='p-3 space-y-3'>
              <div
                className='flex justify-between items-center cursor-pointer'
                onClick={() => setIsShowerWallsOpen(!isShowerWallsOpen)}
              >
                <div className='flex items-center gap-2 justify-between w-full'>
                  <div className='flex items-center gap-2'>
                    {isShowerWallsOpen ? (
                      <ChevronDown className='h-4 w-4 text-slate-600' />
                    ) : (
                      <ChevronRight className='h-4 w-4 text-slate-600' />
                    )}
                    <h3 className='text-lg font-semibold text-slate-700'>
                      Hourly Labor
                    </h3>
                  </div>
                  <span className='text-sm text-slate-500'>
                    {totalHours.toFixed(1)} hrs
                  </span>
                  <p className='font-bold text-blue-600 text-sm'>
                    ${laborTotal.toFixed(2)}
                  </p>
                </div>
              </div>
              {isShowerWallsOpen && (
                <>
                  {laborItems.map(renderLaborItem)}
                  <div className='flex justify-center'>
                    <Button
                      onClick={handleAddLaborItem}
                      variant='default'
                      className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                    >
                      <Plus size={16} />
                      Add Item
                    </Button>
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        )}

        {/* Flat Fee Section */}
        {flatFeeItems.length > 0 && (
          <Card>
            <CardContent className='p-3 space-y-3'>
              <div
                className='flex justify-between items-center cursor-pointer'
                onClick={() => setIsShowerWallsOpen(!isShowerWallsOpen)}
              >
                <div className='flex items-center gap-2'>
                  {isShowerWallsOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Flat Fee Items
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${flatFeeTotal.toFixed(2)}
                </p>
              </div>
              {isShowerWallsOpen && (
                <>
                  {flatFeeItems.map(renderFlatFeeItem)}
                  <div className='flex justify-center'>
                    <Button
                      onClick={handleAddFlatFeeItem}
                      variant='default'
                      className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                    >
                      <Plus size={16} />
                      Add Item
                    </Button>
                  </div>
                </>
              )}
            </CardContent>
          </Card>
        )}

        {/* Show add buttons when no items exist */}
        {laborItems.length === 0 && flatFeeItems.length === 0 && (
          <Card>
            <CardContent className='p-3 space-y-3'>
              <p className='text-sm text-slate-500 text-center py-4'>
                No labor items added yet.
              </p>
              <div className='flex justify-center gap-2'>
                <Button
                  onClick={handleAddLaborItem}
                  variant='default'
                  className='w-auto flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                >
                  <Plus size={16} />
                  Add Hourly Item
                </Button>
                <Button
                  onClick={handleAddFlatFeeItem}
                  variant='default'
                  className='w-auto flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                >
                  <Plus size={16} />
                  Add Flat Fee
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
