'use client';

import React, {
  useMemo,
  useCallback,
  useState,
  useEffect,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { useContractorContext } from '@/contexts/ContractorContext';
import { FLOORS_LABOR_ITEMS } from '@/lib/constants';
import {
  LaborItem as ContextLaborItem,
  FlatFeeItem as ContextFlatFeeItem,
} from '@/types/estimate';

type LaborItem = ContextLaborItem & {
  source?: string;
  isAutoGenerated?: boolean;
};
type FlatFeeItem = ContextFlatFeeItem & {
  source?: string;
  isAutoGenerated?: boolean;
};

interface FloorsDesignData {
  width: string;
  length: string;
  extraMeasurements: Array<{
    id: number;
    label: string;
    width: string;
    length: string;
  }>;
  clientSuppliesTiles: boolean;
  selectedTileSizeOption: string;
  tileSize: { width: string; length: string };
  tilePattern: string;
  customPattern: string;
  isHeatedFloor: boolean;
  heatedFloorType: string;
  customHeatedFloorName: string;
  selectedPrepTasks: string[];
  plywoodThickness: string;
  [key: string]: unknown;
}

export default function FloorsLaborSection() {
  const {
    getDesignData,
    getLaborItems,
    getFlatFeeItems,
    setLaborItems,
    isReloading,
  } = useEstimateWorkflowContext();

  const designData = getDesignData('floors') as FloorsDesignData | null;
  const design = useMemo(
    () =>
      designData || {
        width: '',
        length: '',
        extraMeasurements: [],
        clientSuppliesTiles: false,
        selectedTileSizeOption: 'select_option',
        tileSize: { width: '', length: '' },
        tilePattern: 'select_option',
        customPattern: '',
        isHeatedFloor: false,
        heatedFloorType: 'schluter',
        customHeatedFloorName: '',
        selectedPrepTasks: [],
        plywoodThickness: '3/4',
      },
    [designData]
  );

  const { hourlyRate: contractorHourlyRate } = useContractorContext();
  const contextLaborItems = getLaborItems('floors');
  const contextFlatFeeItems = getFlatFeeItems('floors');
  const [localLaborItems, setLocalLaborItems] = useState<LaborItem[]>([]);
  const [localFlatFeeItems, setLocalFlatFeeItems] = useState<FlatFeeItem[]>([]);
  const [isDesignOpen, setIsDesignOpen] = useState(true);
  const [isHeatedFloorOpen, setIsHeatedFloorOpen] = useState(true);
  const [isConstructionOpen, setIsConstructionOpen] = useState(true);
  const isUserActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  const totalSqFt = useMemo(() => {
    let totalArea = 0;
    const mainWidth = parseFloat(design.width) || 0;
    const mainLength = parseFloat(design.length) || 0;
    if (mainWidth > 0 && mainLength > 0)
      totalArea += (mainWidth * mainLength) / 144;

    // Add safety check for extraMeasurements
    if (design.extraMeasurements && Array.isArray(design.extraMeasurements)) {
      design.extraMeasurements.forEach((m) => {
        const sideWidth = parseFloat(m.width) || 0;
        const sideLength = parseFloat(m.length) || 0;
        if (sideWidth > 0 && sideLength > 0)
          totalArea += (sideWidth * sideLength) / 144;
      });
    }

    return totalArea;
  }, [design.width, design.length, design.extraMeasurements]);

  useEffect(() => {
    setLocalLaborItems(contextLaborItems);
    setLocalFlatFeeItems(contextFlatFeeItems);
  }, [contextLaborItems, contextFlatFeeItems]);

  const generateLaborItems = useCallback(() => {
    const laborItems: LaborItem[] = [];
    const flatFeeItems: FlatFeeItem[] = [];
    const laborItemsMap = FLOORS_LABOR_ITEMS(contractorHourlyRate);

    if (totalSqFt > 0) {
      const tileHours = Math.max(1, totalSqFt / 3).toFixed(2);
      laborItems.push({
        ...laborItemsMap.tileFloor,
        id: `lab-floor-tile-${Date.now()}`,
        hours: tileHours,
        isAutoGenerated: true,
      });
      const groutHours = Math.max(1, totalSqFt / 30).toFixed(2);
      laborItems.push({
        ...laborItemsMap.groutFloor,
        id: `lab-floor-grout-${Date.now()}`,
        hours: groutHours,
        isAutoGenerated: true,
      });
    }

    // Add safety check for selectedPrepTasks
    if (design.selectedPrepTasks && Array.isArray(design.selectedPrepTasks)) {
      design.selectedPrepTasks.forEach((task) => {
        let taskItem: LaborItem | null = null;
        switch (task) {
          case 'self_leveling':
            const levelingHours = Math.max(1, totalSqFt / 75).toFixed(2);
            taskItem = {
              ...laborItemsMap.selfLeveling,
              id: `lab-floor-leveling-${Date.now()}`,
              hours: levelingHours,
              isAutoGenerated: true,
            };
            break;
          case 'ditra':
            const ditraHours = Math.max(1, totalSqFt / 100).toFixed(2);
            taskItem = {
              ...laborItemsMap.installDitra,
              id: `lab-floor-ditra-${Date.now()}`,
              hours: ditraHours,
              isAutoGenerated: true,
            };
            break;
          case 'ditra_xl':
            const ditraXLHours = Math.max(1, totalSqFt / 100).toFixed(2);
            taskItem = {
              ...laborItemsMap.installDitraXL,
              id: `lab-floor-ditra-xl-${Date.now()}`,
              hours: ditraXLHours,
              isAutoGenerated: true,
            };
            break;
          case 'add_plywood':
            const plywoodHours = Math.max(1, totalSqFt / 50).toFixed(2);
            taskItem = {
              ...laborItemsMap.installPlywood,
              id: `lab-floor-plywood-${Date.now()}`,
              name: `Install ${design.plywoodThickness}" Plywood Subfloor`,
              hours: plywoodHours,
              rate: contractorHourlyRate.toString(),
              scope: 'construction',
              source: 'auto',
              isAutoGenerated: true,
            };
            break;
          case 'repair_subfloor':
            taskItem = {
              ...laborItemsMap.repairSubfloor,
              id: `lab-floor-repair-subfloor-${Date.now()}`,
              isAutoGenerated: true,
            };
            break;
          case 'repair_joist':
            taskItem = {
              ...laborItemsMap.repairJoist,
              id: `lab-floor-repair-joist-${Date.now()}`,
              isAutoGenerated: true,
            };
            break;
        }
        if (taskItem) laborItems.push(taskItem);
      });
    }

    if (design.isHeatedFloor && totalSqFt > 0) {
      const heatedFloorHours = (2 + totalSqFt / 20).toFixed(2);
      let systemName = 'Heated Floor System';
      if (design.heatedFloorType === 'schluter')
        systemName = 'Schluter-DITRA-HEAT System';
      else if (design.heatedFloorType === 'nuheat')
        systemName = 'Nuheat Cable System';
      else if (
        design.heatedFloorType === 'custom' &&
        design.customHeatedFloorName
      )
        systemName = design.customHeatedFloorName;
      laborItems.push({
        ...laborItemsMap.installHeatedFloor,
        id: `lab-floor-heated-${Date.now()}`,
        name: `Install ${systemName}`,
        hours: heatedFloorHours,
        isAutoGenerated: true,
      });
    }

    return { laborItems, flatFeeItems };
  }, [design, totalSqFt, contractorHourlyRate]);

  useEffect(() => {
    if (isUserActionRef.current || isReloading) return;
    const choicesKey = `${design.width}-${design.length}-${
      design.selectedPrepTasks ? design.selectedPrepTasks.join(',') : ''
    }-${design.isHeatedFloor}-${design.heatedFloorType}-${
      design.plywoodThickness
    }`;
    if (processedChoicesRef.current === choicesKey) return;
    if (contextLaborItems && contextLaborItems.length > 0) return;
    const currentLabor = localLaborItems || [];
    const existingAutoItems = currentLabor.filter(
      (item) => (item as LaborItem).source === 'auto'
    );
    if (existingAutoItems.length > 0) return;
    const { laborItems } = generateLaborItems();
    if (laborItems.length > 0) setLaborItems('floors', laborItems);
    processedChoicesRef.current = choicesKey;
  }, [
    design,
    generateLaborItems,
    setLaborItems,
    contextLaborItems,
    localLaborItems,
    isReloading,
  ]);

  const handleAddDesignLaborItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `labor-design-${Date.now()}-${Math.random()
        .toString(36)
        .substr(2, 9)}`,
      name: '',
      hours: '1',
      rate: contractorHourlyRate.toString(),
      scope: 'design',
      source: 'custom',
      isAutoGenerated: false,
    };
    isUserActionRef.current = true;
    setLocalLaborItems((prev) => [...prev, newItem]);
    setTimeout(() => {
      setLaborItems('floors', [...localLaborItems, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localLaborItems, setLaborItems, contractorHourlyRate]);

  const handleAddHeatedFloorLaborItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `labor-heated-${Date.now()}-${Math.random()
        .toString(36)
        .substr(2, 9)}`,
      name: '',
      hours: '1',
      rate: contractorHourlyRate.toString(),
      scope: 'heated_floor',
      source: 'custom',
      isAutoGenerated: false,
    };
    isUserActionRef.current = true;
    setLocalLaborItems((prev) => [...prev, newItem]);
    setTimeout(() => {
      setLaborItems('floors', [...localLaborItems, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localLaborItems, setLaborItems, contractorHourlyRate]);

  const handleAddConstructionLaborItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `labor-construction-${Date.now()}-${Math.random()
        .toString(36)
        .substr(2, 9)}`,
      name: '',
      hours: '1',
      rate: contractorHourlyRate.toString(),
      scope: 'construction',
      source: 'custom',
      isAutoGenerated: false,
    };
    isUserActionRef.current = true;
    setLocalLaborItems((prev) => [...prev, newItem]);
    setTimeout(() => {
      setLaborItems('floors', [...localLaborItems, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localLaborItems, setLaborItems, contractorHourlyRate]);

  const handleLaborItemChange = useCallback(
    (id: string, field: keyof LaborItem, value: string) => {
      isUserActionRef.current = true;
      setLocalLaborItems((prev) =>
        prev.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        )
      );
      setTimeout(() => {
        const updatedItems = localLaborItems.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        );
        setLaborItems('floors', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, setLaborItems]
  );

  const handleDeleteLaborItem = useCallback(
    (id: string) => {
      isUserActionRef.current = true;
      setLocalLaborItems((prev) => prev.filter((item) => item.id !== id));
      setTimeout(() => {
        const updatedItems = localLaborItems.filter((item) => item.id !== id);
        setLaborItems('floors', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, setLaborItems]
  );

  const handleAddFlatFeeItem = useCallback(() => {
    const newItem: LaborItem = {
      id: `flat-fee-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      name: '',
      hours: '0',
      rate: '0',
      scope: 'construction',
      source: 'custom',
      isAutoGenerated: false,
    };
    isUserActionRef.current = true;
    setLocalFlatFeeItems((prev) => [
      ...prev,
      newItem as unknown as FlatFeeItem,
    ]);
    setTimeout(() => {
      setLaborItems('floors', [...localLaborItems, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localLaborItems, setLaborItems]);

  const handleFlatFeeItemChange = useCallback(
    (id: string, field: keyof FlatFeeItem, value: string) => {
      isUserActionRef.current = true;
      setLocalFlatFeeItems((prev) =>
        prev.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        )
      );
      setTimeout(() => {
        const updatedItems = localLaborItems.map((item) => {
          if (item.id === id) {
            const flatFeeItem = localFlatFeeItems.find((f) => f.id === id);
            if (flatFeeItem) {
              return {
                ...item,
                name: flatFeeItem.name,
                rate: flatFeeItem.unitPrice,
              };
            }
          }
          return item;
        });
        setLaborItems('floors', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, localFlatFeeItems, setLaborItems]
  );

  const handleDeleteFlatFeeItem = useCallback(
    (id: string) => {
      isUserActionRef.current = true;
      setLocalFlatFeeItems((prev) => prev.filter((item) => item.id !== id));
      setTimeout(() => {
        const updatedItems = localLaborItems.filter((item) => item.id !== id);
        setLaborItems('floors', updatedItems);
        isUserActionRef.current = false;
      }, 100);
    },
    [localLaborItems, setLaborItems]
  );

  const flatFeeItems = localFlatFeeItems;

  // Separate labor items by scope
  const designLaborItems = useMemo(() => {
    return localLaborItems.filter((item) => item.scope === 'design');
  }, [localLaborItems]);

  const heatedFloorLaborItems = useMemo(() => {
    return localLaborItems.filter(
      (item) =>
        item.scope === 'heated_floor' ||
        item.name.toLowerCase().includes('heated') ||
        item.name.toLowerCase().includes('thermostat') ||
        item.name.toLowerCase().includes('schluter-ditra-heat') ||
        item.name.toLowerCase().includes('nuheat')
    );
  }, [localLaborItems]);

  const constructionLaborItems = useMemo(() => {
    return localLaborItems.filter(
      (item) =>
        item.scope === 'construction' &&
        !item.name.toLowerCase().includes('heated') &&
        !item.name.toLowerCase().includes('thermostat') &&
        !item.name.toLowerCase().includes('schluter-ditra-heat') &&
        !item.name.toLowerCase().includes('nuheat')
    );
  }, [localLaborItems]);

  // Calculate totals for each category
  const designTotalHours = designLaborItems.reduce(
    (sum, item) => sum + (parseFloat(item.hours) || 0),
    0
  );
  const designLaborTotal = designLaborItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0),
    0
  );

  const heatedFloorTotalHours = heatedFloorLaborItems.reduce(
    (sum, item) => sum + (parseFloat(item.hours) || 0),
    0
  );
  const heatedFloorLaborTotal = heatedFloorLaborItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0),
    0
  );

  const constructionTotalHours = constructionLaborItems.reduce(
    (sum, item) => sum + (parseFloat(item.hours) || 0),
    0
  );
  const constructionLaborTotal = constructionLaborItems.reduce(
    (sum, item) =>
      sum + (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0),
    0
  );

  const renderLaborItem = useCallback(
    (item: LaborItem) => {
      return (
        <div
          key={item.id}
          className={`p-3 rounded-lg border shadow-sm w-full ${
            item.isAutoGenerated
              ? 'bg-white border-blue-200'
              : 'bg-white border-slate-200'
          }`}
        >
          <div className='flex items-center gap-2 mb-2 w-full'>
            <Input
              type='text'
              value={item.name}
              onChange={(e) =>
                handleLaborItemChange(item.id, 'name', e.target.value)
              }
              placeholder='Labor Task'
              className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full`}
            />
            <Button
              onClick={() => handleDeleteLaborItem(item.id)}
              variant='ghost'
              size='sm'
              className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
            >
              <Trash2 size={16} />
            </Button>
          </div>
          <div className='grid grid-cols-3 gap-3'>
            <div className='w-full'>
              <label className='text-xs text-slate-500'>Hours</label>
              <Input
                type='number'
                value={item.hours}
                onChange={(e) =>
                  handleLaborItemChange(item.id, 'hours', e.target.value)
                }
                placeholder='0'
                className='text-center w-full border-blue-300 focus:border-blue-500'
              />
            </div>
            <div className='w-full'>
              <label className='text-xs text-slate-500'>Rate ($/hr)</label>
              <Input
                type='number'
                value={item.rate}
                onChange={(e) =>
                  handleLaborItemChange(item.id, 'rate', e.target.value)
                }
                placeholder='0'
                className='text-center w-full border-blue-300 focus:border-blue-500'
              />
            </div>
            <div className='w-full'>
              <label className='text-xs text-slate-500'>Total</label>
              <div className='w-full p-2 text-center font-semibold text-slate-800 bg-white rounded-md'>
                $
                {(
                  (parseFloat(item.hours) || 0) * (parseFloat(item.rate) || 0)
                ).toFixed(2)}
              </div>
            </div>
          </div>
        </div>
      );
    },
    [handleLaborItemChange, handleDeleteLaborItem]
  );

  const renderFlatFeeItem = useCallback(
    (item: FlatFeeItem) => {
      return (
        <div
          key={item.id}
          className={`p-3 rounded-lg border shadow-sm w-full ${
            item.isAutoGenerated
              ? 'bg-blue-50 border-blue-200'
              : 'bg-white border-slate-200'
          }`}
        >
          <div className='flex items-center gap-2 mb-2 w-full'>
            <Input
              type='text'
              value={item.name}
              onChange={(e) =>
                handleFlatFeeItemChange(item.id, 'name', e.target.value)
              }
              placeholder='Flat Fee Task'
              className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none w-44 sm:w-full`}
            />
            <Button
              onClick={() => handleDeleteFlatFeeItem(item.id)}
              variant='ghost'
              size='sm'
              className='text-red-500 hover:text-red-700 p-1 h-auto flex-shrink-0'
            >
              <Trash2 size={16} />
            </Button>
          </div>
          <div className='w-full'>
            <label className='text-xs text-slate-500'>Total ($)</label>
            <Input
              type='number'
              value={item.unitPrice}
              onChange={(e) =>
                handleFlatFeeItemChange(item.id, 'unitPrice', e.target.value)
              }
              placeholder='0.00'
              className='text-center w-full border-b-2 border-t-0 border-l-0 border-r-0 border-blue-500 focus:border-blue-500'
            />
          </div>
        </div>
      );
    },
    [handleFlatFeeItemChange, handleDeleteFlatFeeItem]
  );

  const flatFeeTotal = flatFeeItems.reduce(
    (sum, item) => sum + (parseFloat(item.unitPrice) || 0),
    0
  );

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-baseline'>
        <h2 className='text-2xl font-bold text-slate-800'>Labor</h2>
      </div>

      <div className='space-y-4'>
        {/* Design Labor Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsDesignOpen(!isDesignOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isDesignOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Design Labor
                  </h3>
                </div>
                <span className='text-sm text-slate-500'>
                  {designTotalHours.toFixed(1)} hrs
                </span>
                <p className='font-bold text-blue-600 text-sm'>
                  ${designLaborTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isDesignOpen && (
              <>
                {designLaborItems.length > 0 ? (
                  <div className='space-y-2'>
                    {designLaborItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No design labor items added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddDesignLaborItem}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        {/* Heated Floor Labor Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsHeatedFloorOpen(!isHeatedFloorOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isHeatedFloorOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Heated Floor Labor
                  </h3>
                </div>
                <span className='text-sm text-slate-500'>
                  {heatedFloorTotalHours.toFixed(1)} hrs
                </span>
                <p className='font-bold text-blue-600 text-sm'>
                  ${heatedFloorLaborTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isHeatedFloorOpen && (
              <>
                {heatedFloorLaborItems.length > 0 ? (
                  <div className='space-y-2'>
                    {heatedFloorLaborItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No heated floor labor items added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddHeatedFloorLaborItem}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        {/* Construction Labor Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsConstructionOpen(!isConstructionOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isConstructionOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Construction Labor
                  </h3>
                </div>
                <span className='text-sm text-slate-500'>
                  {constructionTotalHours.toFixed(1)} hrs
                </span>
                <p className='font-bold text-blue-600 text-sm'>
                  ${constructionLaborTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isConstructionOpen && (
              <>
                {constructionLaborItems.length > 0 ? (
                  <div className='space-y-2'>
                    {constructionLaborItems.map(renderLaborItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No construction labor items added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddConstructionLaborItem}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        {/* Flat Fee Section (remains unchanged) */}
        {flatFeeItems.length > 0 && (
          <Card>
            <CardContent className='p-3 space-y-3'>
              <div className='flex justify-between items-center'>
                <h3 className='text-lg font-semibold text-slate-700'>
                  Flat Fee Items
                </h3>
                <p className='font-bold text-blue-600 text-sm'>
                  ${flatFeeTotal.toFixed(2)}
                </p>
              </div>
              <div className='space-y-2'>
                {flatFeeItems.map(renderFlatFeeItem)}
              </div>
              <div className='flex justify-center'>
                <Button
                  onClick={handleAddFlatFeeItem}
                  variant='default'
                  className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                >
                  <Plus size={16} />
                  Add Item
                </Button>
              </div>
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
