'use client';

import React, {
  useMemo,
  useCallback,
  useState,
  useEffect,
  useRef,
} from 'react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Plus, Trash2, ChevronDown, ChevronRight } from 'lucide-react';
import { useEstimateWorkflowContext } from '@/contexts/EstimateWorkflowContext';
import { SHOWER_BASE_MATERIALS_ITEMS } from '@/lib/constants';
import { MaterialItem as ContextMaterialItem } from '@/types/estimate';

type MaterialItem = ContextMaterialItem & {
  source?: string;
  isAutoGenerated?: boolean;
};

interface ShowerBaseDesignData {
  width: string;
  length: string;
  baseType: string;
  drainType: string;
  waterproofingSystem: string;
  entryType: string;
  subfloorRepair: boolean;
  joistModification: boolean;
  clientSuppliesBase: string;
  installationBy: string;
  [key: string]: unknown;
}

export default function ShowerBaseMaterialsSection() {
  const { getDesignData, getMaterialItems, setMaterialItems, isReloading } =
    useEstimateWorkflowContext();

  // Get design data from context
  const designData = getDesignData('showerBase') as ShowerBaseDesignData | null;
  const design = useMemo(
    () =>
      designData || {
        width: '',
        length: '',
        baseType: 'Select base type',
        drainType: 'regular',
        waterproofingSystem: 'none',
        entryType: 'curb',
        subfloorRepair: false,
        joistModification: false,
        clientSuppliesBase: 'No',
        installationBy: 'Me',
      },
    [designData]
  );

  // Get context data
  const contextMaterials = getMaterialItems('showerBase');

  // Local state for immediate UI updates
  const [localMaterials, setLocalMaterials] = useState<MaterialItem[]>([]);
  const [isDesignOpen, setIsDesignOpen] = useState(true);
  const [isConstructionOpen, setIsConstructionOpen] = useState(true);

  // Refs to track user actions and prevent auto-generation interference
  const isUserActionRef = useRef(false);
  const processedChoicesRef = useRef<string>('');

  // Sync local state with context
  useEffect(() => {
    setLocalMaterials(contextMaterials);
  }, [contextMaterials]);

  // Generate materials based on design choices
  const generateMaterials = useCallback(() => {
    const materials: MaterialItem[] = [];

    const baseType = design.baseType;
    const drainType = design.drainType;
    const waterproofingSystem = design.waterproofingSystem;
    const subfloorRepair = design.subfloorRepair;
    const joistModification = design.joistModification;
    const clientSuppliesBase = design.clientSuppliesBase;

    const materialsMap = SHOWER_BASE_MATERIALS_ITEMS;

    // Base Type Materials
    if (baseType === 'Tub') {
      if (clientSuppliesBase === 'No') {
        // Client does NOT supply: add material cost ($550)
        materials.push({
          ...materialsMap.tub,
          id: `mat-base-tub-${Date.now()}`,
        });
      } else {
        // Client supplies: add note-only item (no cost)
        materials.push({
          id: `mat-base-tub-supplied-${Date.now()}`,
          name: 'Tub supplied by client',
          quantity: '0',
          unit: '',
          price: '0',
          scope: 'design' as const,
          source: 'auto' as const,
          isAutoGenerated: true,
        });
      }
    } else if (baseType === 'Acrylic Base') {
      if (clientSuppliesBase === 'No') {
        // Client does NOT supply: add material cost ($500)
        materials.push({
          ...materialsMap.acrylicBase,
          id: `mat-base-acrylic-${Date.now()}`,
        });
      } else {
        // Client supplies: add note-only item (no cost)
        materials.push({
          id: `mat-base-acrylic-supplied-${Date.now()}`,
          name: 'Acrylic Base supplied by client',
          quantity: '0',
          unit: '',
          price: '0',
          scope: 'design' as const,
          source: 'auto' as const,
          isAutoGenerated: true,
        });
      }
    } else if (baseType === 'Tiled Base') {
      // Get entry type and calculate base sq ft
      const entryType = design.entryType || 'curb';
      const baseLengthIn = parseFloat(design.length || '0');
      const baseWidthIn = parseFloat(design.width || '0');
      const baseSqFt = (baseLengthIn * baseWidthIn) / 144;

      // ===== DESIGN MATERIALS =====
      // Shower Floor Tile (Mosaic) with 15% waste
      if (baseSqFt > 0) {
        const tileQty = Math.ceil(baseSqFt * 1.15);
        materials.push({
          id: `mat-base-floor-tile-${Date.now()}`,
          name: 'Shower Floor Tile (Mosaic)',
          quantity: tileQty.toString(),
          unit: 'sq ft',
          price: '20',
          scope: 'design' as const,
          source: 'auto' as const,
          isAutoGenerated: true,
        });
        // Floor Grout
        materials.push({
          id: `mat-base-floor-grout-${Date.now()}`,
          name: 'Floor Grout',
          quantity: '1',
          unit: 'bag',
          price: '35',
          scope: 'design' as const,
          source: 'auto' as const,
          isAutoGenerated: true,
        });
      }

      // Drain Materials (Design)
      if (drainType === 'regular') {
        materials.push({
          ...materialsMap.standardDrain,
          id: `mat-base-drain-standard-${Date.now()}`,
        });
      } else if (drainType === 'linear') {
        materials.push({
          ...materialsMap.linearDrain,
          id: `mat-base-drain-linear-${Date.now()}`,
        });
      }

      // ===== CONSTRUCTION MATERIALS =====
      // Entry Type Materials
      if (entryType === 'curbless') {
        materials.push({
          ...materialsMap.plywoodRecessedFloor,
          id: `mat-base-plywood-recessed-${Date.now()}`,
        });
        materials.push({
          ...materialsMap.lumberJoistCleats,
          id: `mat-base-lumber-joist-cleats-${Date.now()}`,
        });
        materials.push({
          ...materialsMap.constructionAdhesive,
          id: `mat-base-construction-adhesive-${Date.now()}`,
        });
      } else {
        materials.push({
          ...materialsMap.lumberCurb,
          id: `mat-base-lumber-curb-${Date.now()}`,
        });
      }

      // Waterproofing System Materials (Construction)
      if (waterproofingSystem === 'schluter') {
        // Schluter kit depends on drain type
        if (drainType === 'linear') {
          materials.push({
            ...materialsMap.schluterKitLinear,
            id: `mat-base-schluter-kit-linear-${Date.now()}`,
          });
        } else {
          materials.push({
            ...materialsMap.schluterKitCenter,
            id: `mat-base-schluter-kit-center-${Date.now()}`,
          });
        }
        materials.push({
          ...materialsMap.schluterThinset,
          id: `mat-base-schluter-thinset-${Date.now()}`,
        });
      } else if (waterproofingSystem === 'mortar') {
        // Mortar Bed System - calculate mortar quantity
        const mortarQty = Math.ceil(baseSqFt / 4) + 1;
        materials.push({
          ...materialsMap.mortarMix,
          id: `mat-base-mortar-mix-${Date.now()}`,
          quantity: mortarQty.toString(),
        });
        materials.push({
          ...materialsMap.pvcPanLiner,
          id: `mat-base-pvc-pan-liner-${Date.now()}`,
        });
        materials.push({
          ...materialsMap.drainWaterproofingAccessories,
          id: `mat-base-drain-accessories-${Date.now()}`,
        });
      } else if (waterproofingSystem === 'wedi') {
        materials.push({
          ...materialsMap.wediFundoKit,
          id: `mat-base-wedi-fundo-kit-${Date.now()}`,
        });
        // Calculate sealant quantity based on area
        const sealantQty = baseSqFt <= 20 ? 2 : 2 + Math.ceil((baseSqFt - 20) / 15);
        materials.push({
          ...materialsMap.wediJointSealant,
          id: `mat-base-wedi-sealant-${Date.now()}`,
          quantity: sealantQty.toString(),
        });
      } else if (waterproofingSystem === 'laticrete') {
        materials.push({
          ...materialsMap.laticretePreSlopedPan,
          id: `mat-base-laticrete-pan-${Date.now()}`,
        });
        // Calculate sealant quantity based on area
        const sealantQty = baseSqFt <= 20 ? 2 : 2 + Math.ceil((baseSqFt - 20) / 15);
        materials.push({
          ...materialsMap.laticreteAdhesiveSealant,
          id: `mat-base-laticrete-adhesive-${Date.now()}`,
          quantity: sealantQty.toString(),
        });
        materials.push({
          ...materialsMap.hydrobanliquidMembrane,
          id: `mat-base-hydroban-membrane-${Date.now()}`,
        });
      }
    }

    // General Construction Materials
    if (subfloorRepair) {
      materials.push({
        ...materialsMap.subfloorPlywood,
        id: `mat-base-subfloor-${Date.now()}`,
      });
    }

    if (joistModification) {
      materials.push({
        ...materialsMap.joistLumber,
        id: `mat-base-joist-${Date.now()}`,
      });
    }

    return materials;
  }, [design]);

  // Auto-generate materials when design changes
  useEffect(() => {
    if (isUserActionRef.current || isReloading) return;

    // Skip if base type not selected
    if (design.baseType === 'Select base type') return;

    const choicesKey = `${design.baseType}-${design.drainType}-${design.waterproofingSystem}-${design.subfloorRepair}-${design.joistModification}-${design.clientSuppliesBase}-${design.entryType}-${design.width}-${design.length}`;

    if (processedChoicesRef.current === choicesKey) return;

    // Generate new auto items based on current design
    const newAutoItems = generateMaterials();

    // Get existing custom items (items added by user, not auto-generated)
    const existingItems = (contextMaterials || localMaterials || []) as MaterialItem[];
    const customItems = existingItems.filter(
      (item) => item.source === 'custom' || item.id.startsWith('material-design-') || item.id.startsWith('material-construction-')
    );

    // Combine custom items with new auto-generated items
    const updatedItems = [...customItems, ...newAutoItems];

    // Update material items
    setMaterialItems('showerBase', updatedItems);

    processedChoicesRef.current = choicesKey;
  }, [
    design,
    generateMaterials,
    setMaterialItems,
    contextMaterials,
    localMaterials,
    isReloading,
  ]);

  // Handle adding new materials

  const handleAddDesignMaterial = useCallback(() => {
    const newItem: MaterialItem = {
      id: `material-design-${Date.now()}-${Math.random()
        .toString(36)
        .substring(2, 11)}`,
      name: 'Custom Design Material',
      quantity: '1',
      unit: '',
      price: '0',
      scope: 'design',
      source: 'custom',
      isAutoGenerated: false,
    };

    isUserActionRef.current = true;
    setLocalMaterials((prev) => [...prev, newItem]);

    setTimeout(() => {
      setMaterialItems('showerBase', [...localMaterials, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localMaterials, setMaterialItems]);

  const handleAddConstructionMaterial = useCallback(() => {
    const newItem: MaterialItem = {
      id: `material-construction-${Date.now()}-${Math.random()
        .toString(36)
        .substring(2, 11)}`,
      name: 'Custom Construction Material',
      quantity: '1',
      unit: '',
      price: '0',
      scope: 'construction',
      source: 'custom',
      isAutoGenerated: false,
    };

    isUserActionRef.current = true;
    setLocalMaterials((prev) => [...prev, newItem]);

    setTimeout(() => {
      setMaterialItems('showerBase', [...localMaterials, newItem]);
      isUserActionRef.current = false;
    }, 100);
  }, [localMaterials, setMaterialItems]);

  // Handle material changes
  const handleMaterialChange = useCallback(
    (id: string, field: keyof MaterialItem, value: string) => {
      isUserActionRef.current = true;

      setLocalMaterials((prev) =>
        prev.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        )
      );

      setTimeout(() => {
        const updatedMaterials = localMaterials.map((item) =>
          item.id === id ? { ...item, [field]: value } : item
        );
        setMaterialItems('showerBase', updatedMaterials);
        isUserActionRef.current = false;
      }, 100);
    },
    [localMaterials, setMaterialItems]
  );

  // Handle deleting material
  const handleDeleteMaterial = useCallback(
    (id: string) => {
      isUserActionRef.current = true;

      setLocalMaterials((prev) => prev.filter((item) => item.id !== id));

      setTimeout(() => {
        const updatedMaterials = localMaterials.filter(
          (item) => item.id !== id
        );
        setMaterialItems('showerBase', updatedMaterials);
        isUserActionRef.current = false;
      }, 100);
    },
    [localMaterials, setMaterialItems]
  );

  const materials = localMaterials;

  const renderMaterialItem = useCallback(
    (material: MaterialItem) => {
      return (
        <div
          key={material.id}
          className={`p-3 bg-white rounded-lg border border-slate-300`}
        >
          <div className='flex items-center gap-2 mb-2'>
            <Input
              type='text'
              value={material.name}
              onChange={(e) =>
                handleMaterialChange(material.id, 'name', e.target.value)
              }
              placeholder='Supply Name'
              className={`border-b-2 border-t-0 border-l-0 border-r-0 bg-transparent border-blue-300 focus:border-blue-500 focus:outline-none`}
            />
            <Button
              onClick={() => handleDeleteMaterial(material.id)}
              variant='ghost'
              size='sm'
              className='text-red-500 hover:text-red-700 p-1 h-auto'
            >
              <Trash2 size={16} />
            </Button>
          </div>
          <div className='grid grid-cols-2 gap-3'>
            <div>
              <label className='text-xs text-slate-500'>Quantity{material.unit ? ` (${material.unit})` : ''}</label>
              <Input
                type='number'
                value={material.quantity}
                onChange={(e) =>
                  handleMaterialChange(material.id, 'quantity', e.target.value)
                }
                placeholder='0'
                className={`text-center border-blue-300 focus:border-blue-500`}
              />
            </div>
            <div>
              <label className='text-xs text-slate-500'>Price/Unit ($)</label>
              <Input
                type='number'
                value={material.price}
                onChange={(e) =>
                  handleMaterialChange(material.id, 'price', e.target.value)
                }
                placeholder='0.00'
                className={`text-center border-blue-300 focus:border-blue-500`}
              />
            </div>
            <div className='col-span-2'>
              <label className='text-xs text-slate-500'>Total</label>
              <div className='w-full p-2 text-center font-semibold text-slate-800 bg-slate-50 rounded-md'>
                $
                {(
                  (parseFloat(material.quantity) || 0) *
                  (parseFloat(material.price) || 0)
                ).toFixed(2)}
              </div>
            </div>
          </div>
        </div>
      );
    },
    [handleMaterialChange, handleDeleteMaterial]
  );

  // Separate materials by scope
  const designMaterials = useMemo(() => {
    return materials.filter((item) => item.scope === 'design');
  }, [materials]);

  const constructionMaterials = useMemo(() => {
    return materials.filter((item) => item.scope === 'construction');
  }, [materials]);

  // Calculate totals for design materials
  const designTotal = designMaterials.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  // Calculate totals for construction materials
  const constructionTotal = constructionMaterials.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  // Calculate overall total (for backward compatibility)
  const total = materials.reduce(
    (sum, item) =>
      sum + (parseFloat(item.quantity) || 0) * (parseFloat(item.price) || 0),
    0
  );

  return (
    <div className='space-y-5'>
      <div className='flex justify-between items-center'>
        <h2 className='text-2xl font-bold text-slate-800'>
          Materials & Supplies
        </h2>
        <div className='text-right'>
          <p className='font-bold text-blue-600 text-lg'>${total.toFixed(2)}</p>
        </div>
      </div>

      <div className='space-y-4'>
        {/* Design Materials Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsDesignOpen(!isDesignOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isDesignOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Design Materials
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${designTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isDesignOpen && (
              <>
                {designMaterials.length > 0 ? (
                  <div className='space-y-2'>
                    {designMaterials.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No design materials added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddDesignMaterial}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>

        {/* Construction Materials Section */}
        <Card>
          <CardContent className='p-3 space-y-3'>
            <div
              className='flex justify-between items-center cursor-pointer'
              onClick={() => setIsConstructionOpen(!isConstructionOpen)}
            >
              <div className='flex items-center gap-2 justify-between w-full'>
                <div className='flex items-center gap-2'>
                  {isConstructionOpen ? (
                    <ChevronDown className='h-4 w-4 text-slate-600' />
                  ) : (
                    <ChevronRight className='h-4 w-4 text-slate-600' />
                  )}
                  <h3 className='text-lg font-semibold text-slate-700'>
                    Construction Materials
                  </h3>
                </div>
                <p className='font-bold text-blue-600 text-sm'>
                  ${constructionTotal.toFixed(2)}
                </p>
              </div>
            </div>
            {isConstructionOpen && (
              <>
                {constructionMaterials.length > 0 ? (
                  <div className='space-y-2'>
                    {constructionMaterials.map(renderMaterialItem)}
                  </div>
                ) : (
                  <p className='text-sm text-slate-500 text-center py-4'>
                    No construction materials added yet.
                  </p>
                )}
                <div className='flex justify-center'>
                  <Button
                    onClick={handleAddConstructionMaterial}
                    variant='default'
                    className='w-auto mt-2 flex items-center justify-center gap-2 py-2.5 px-4 text-white font-semibold border-blue-200'
                  >
                    <Plus size={16} />
                    Add Item
                  </Button>
                </div>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
